name: MinGW

on:
  pull_request:
  push:
    branches: mingw
    paths-ignore:
    - '.circleci/**'
    - '.github/actions/spelling/**'
    - 'docs/**'
    - 'packages**'
    - .cirrus.yml
    - .clang-format
    - .gitignore
    - .travis.yml
    - AUTHORS
    - COPYRIGHT
    - ChangeLog.md
    - LICENSE
    - README.md
    - appveyor.yml

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: fetch tags
      run: git fetch --unshallow --tags --prune --force
    - name: append PATH
      run: echo 'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin' >> $GITHUB_PATH
    - name: update mingw64
      # wanna version >= 10.2
      run: choco upgrade mingw -y --no-progress && refreshenv
    - name: build-make
      shell: bash
      run: |
        CC=gcc CXX=g++ make MDBX_BUILD_OPTIONS=-DMDBX_DEBUG=1 all build-test tools-static
    - name: configure-dll
      shell: bash
      run: |
        mkdir build-dll && cd build-dll && \
        cmake -G "MinGW Makefiles" -DMDBX_BUILD_SHARED_LIBRARY:BOOL=ON -DMDBX_INSTALL_STATIC:BOOL=OFF -DMDBX_ENABLE_TESTS:BOOL=ON ..
    - name: build-dll
      shell: bash
      run: cd build-dll && cmake --build .
    - name: test-dll
      shell: bash
      run: |
        export "PATH=/c/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH" && \
        cd build-dll && \
        ./mdbx_test.exe --progress --console=no --pathname=test.db --dont-cleanup-after basic && \
        ./mdbx_chk.exe -nvv test.db
    - name: configure-static
      shell: bash
      run: |
        mkdir build-static && cd build-static && \
        cmake -G "MinGW Makefiles" -DMDBX_BUILD_SHARED_LIBRARY:BOOL=OFF -DMDBX_INSTALL_STATIC:BOOL=ON -DMDBX_ENABLE_TESTS:BOOL=ON ..
    - name: build-static
      shell: bash
      run: |
        cd build-static && cmake --build .
    - name: run-test
      shell: bash
      run: |
        export "PATH=/c/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH" && \
        cd build-static && \
        ./mdbx_test.exe --progress --console=no --pathname=test.db --dont-cleanup-after basic && \
        ./mdbx_chk.exe -nvv test.db
