{{! x86 AVX-512VL Keccak-f[1600] — arch-specific assembly }}
{{! Uses vpternlogq (3-way XOR, Chi), vprolq (rotate), EVEX 32 YMM regs }}
{{! Instruction mnemonics come from .env file via ENVIRON }}
/*
 * dap_keccak_f1600_{{FUNC_SUFFIX}}.S — AUTO-GENERATED by dap_tpl
 *
 * x86-64 Keccak-f[1600] with Pi absorbed into register addressing.
 * Fully unrolled — zero Pi rename moves across all 24 rounds.
 *
 * Key techniques:
 *   - {{INSN_XOR3}} for 3-way XOR (Theta)
 *   - {{INSN_CHI}} for Chi: a ^ (~b & c)
 *   - {{INSN_ROL64}} for Rho rotations
 *   - 32 YMM registers via EVEX — zero spills
 *
 * Register allocation:
 *   ymm0 – ymm24 : 25 state lanes
 *   ymm25– ymm29 : 5 temporaries (Theta C[0..4])
 *   ymm30, ymm31 : 2 temporaries (Chi row processing)
 *
 * Copyright: DeM Labs Inc. 2026
 * License: GNU GPL v3
 * @generated
 */

.text

{{! ===== 1x permutation wrapper ===== }}
.globl  dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.type   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rdi),  {{REG_1X_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}},  ({{STRIDE_1X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, .-dap_hash_keccak_permute_{{FUNC_SUFFIX}}

{{! ===== 4x permutation wrapper (interleaved layout) ===== }}
.globl  dap_keccak_x4_permute_{{FUNC_SUFFIX}}
.type   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_x4_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_4X}}   ({{STRIDE_4X}}*{{i}})(%rdi),  {{REG_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_4X}}   {{REG_PREFIX}}{{i}},  ({{STRIDE_4X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, .-dap_keccak_x4_permute_{{FUNC_SUFFIX}}

{{! ===== Core permutation: 24 fully-unrolled rounds ===== }}
{{! Pi absorbed into precomputed MAP_N register mappings }}
.balign 64
.Lpermute_f1600:
{{#for rnd in ROUNDS}}
{{#set M}}{{rnd|resolve|MAP_}}{{/set}}
    /* ---- Round {{rnd}} ---- */
{{! == Theta step 1: C[x] = lane[0+x] ^ lane[5+x] ^ lane[10+x] == }}
{{#for x in COLS}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{M|at|x}}, {{REG_PREFIX}}{{x|math|$+25}}
    {{INSN_XOR3}}, {{REG_PREFIX}}{{M|at|x+5}}, {{REG_PREFIX}}{{M|at|x+10}}, {{REG_PREFIX}}{{x|math|$+25}}
{{/for}}
{{! == Theta step 2: C[x] ^= lane[15+x] ^ lane[20+x] == }}
{{#for x in COLS}}
    {{INSN_XOR3}}, {{REG_PREFIX}}{{M|at|x+15}}, {{REG_PREFIX}}{{M|at|x+20}}, {{REG_PREFIX}}{{x|math|$+25}}
{{/for}}
{{! == Theta step 3: D[x] = C[(x+4)%5] ^ ROL(C[(x+1)%5], 1); state ^= D == }}
{{#for x in COLS}}
    {{INSN_ROL64}}      $1, {{REG_PREFIX}}{{x|math|($+1)%5+25}}, {{REG_PREFIX}}30
{{#for y in COLS}}
    {{INSN_XOR3}}, {{REG_PREFIX}}30, {{REG_PREFIX}}{{x|math|($+4)%5+25}}, {{REG_PREFIX}}{{M|at|x+5*y}}
{{/for}}
{{/for}}
{{! == Rho: rotate each lane by its fixed offset == }}
{{#for p in LANES}}
{{#set rho_val}}{{RHO|at|p}}{{/set}}{{#if rho_val != 0}}
    {{INSN_ROL64}}      ${{rho_val}}, {{REG_PREFIX}}{{M|at|p}}, {{REG_PREFIX}}{{M|at|p}}
{{/if}}
{{/for}}
{{! == Chi: a[x] ^= ~a[x+1] & a[x+2], row by row == }}
{{#for ri in COLS}}
{{#set ROW}}{{ri|resolve|CHI_ROW_}}{{/set}}
{{#set L0}}{{ROW|at|0}}{{/set}}{{#set L1}}{{ROW|at|1}}{{/set}}{{#set L2}}{{ROW|at|2}}{{/set}}{{#set L3}}{{ROW|at|3}}{{/set}}{{#set L4}}{{ROW|at|4}}{{/set}}
{{#set ra}}{{M|at|L0}}{{/set}}{{#set rb}}{{M|at|L1}}{{/set}}{{#set rc}}{{M|at|L2}}{{/set}}{{#set rd}}{{M|at|L3}}{{/set}}{{#set re}}{{M|at|L4}}{{/set}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}30
    {{INSN_CHI}}, {{REG_PREFIX}}{{rc}}, {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}30
{{#if ri == 0}}
    {{INSN_XOR_BC}}      .Lrc+{{rnd|math|$*8}}(%rip){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
{{/if}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}31
    {{INSN_CHI}}, {{REG_PREFIX}}{{rd}}, {{REG_PREFIX}}{{rc}}, {{REG_PREFIX}}31
    {{INSN_CHI}}, {{REG_PREFIX}}{{re}}, {{REG_PREFIX}}{{rd}}, {{REG_PREFIX}}{{rc}}
    {{INSN_CHI}}, {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}{{re}}, {{REG_PREFIX}}{{rd}}
    {{INSN_CHI}}, {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}{{re}}
    {{INSN_MOV}}   {{REG_PREFIX}}30, {{REG_PREFIX}}{{ra}}
    {{INSN_MOV}}   {{REG_PREFIX}}31, {{REG_PREFIX}}{{rb}}
{{/for}}
{{/for}}
    ret
.size   .Lpermute_f1600, .-.Lpermute_f1600

{{! ===== Round constants ===== }}
.section .rodata
.balign 64
.Lrc:
{{#for rc in RC_LIST}}
    .quad   {{rc}}
{{/for}}

.section .note.GNU-stack,"",@progbits
