{{! x86 AVX-512VL Keccak-f[1600] — prepare-theta variant }}
{{! Pre-computed D with vpxorq + column parity accumulated during Chi. }}
{{! Reduces FP0/FP1 pressure from 89 to 54 ops/round on Zen4.        }}
/*
 * dap_keccak_f1600_{{FUNC_SUFFIX}}.S — AUTO-GENERATED by dap_tpl
 *
 * x86-64 Keccak-f[1600] — prepare-theta optimisation.
 *
 * Key differences from the baseline looped variant:
 *   1. Theta D = C[(x+4)%5] ^ ROL(C[(x+1)%5],1) computed once per column,
 *      applied via vpxorq (FP0-3) instead of vpternlogq (FP0/1 only).
 *   2. Column parity C[0..4] accumulated DURING Chi (prepare-theta),
 *      eliminating the 10 vpternlogq recalculation at the top of every round.
 *   3. Net savings: ~35 FP0/1 uops per round → 27 cycles/round vs 44.5.
 *
 * Register allocation (identical to baseline):
 *   ymm0 – ymm24  : 25 state lanes
 *   ymm25 – ymm29  : 5 column parity C[0..4] (carried across rounds)
 *   ymm30, ymm31   : scratch
 *   rcx             : loop counter
 *   r8              : round constant pointer
 *
 * Copyright: DeM Labs Inc. 2026
 * License: GNU GPL v3
 * @generated
 */

.text

{{! ===== 1x permutation wrapper ===== }}
.globl  dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.type   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rdi),  {{REG_1X_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}},  ({{STRIDE_1X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, .-dap_hash_keccak_permute_{{FUNC_SUFFIX}}

{{! ===== 4x permutation wrapper (interleaved layout) ===== }}
.globl  dap_keccak_x4_permute_{{FUNC_SUFFIX}}
.type   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_x4_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_4X}}   ({{STRIDE_4X}}*{{i}})(%rdi),  {{REG_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_4X}}   {{REG_PREFIX}}{{i}},  ({{STRIDE_4X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, .-dap_keccak_x4_permute_{{FUNC_SUFFIX}}

{{! ===== Core permutation: prepare-theta, 2-round unrolled (12 iters) ===== }}
.balign 64
.Lpermute_f1600:

    /* ================================================================ */
    /* Initial column parity: C[x] = state[x] ^ state[x+5] ^ ...       */
    /* Uses vpxorq chain (FP0-3) instead of vpternlogq (FP0/1).        */
    /* ================================================================ */

    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}25
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}26
    {{INSN_MOV}}    {{REG_PREFIX}}2,  {{REG_PREFIX}}27
    {{INSN_MOV}}    {{REG_PREFIX}}3,  {{REG_PREFIX}}28
    {{INSN_MOV}}    {{REG_PREFIX}}4,  {{REG_PREFIX}}29

    {{INSN_XOR_BC}} {{REG_PREFIX}}5,  {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}6,  {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}7,  {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}8,  {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}9,  {{REG_PREFIX}}29, {{REG_PREFIX}}29

    {{INSN_XOR_BC}} {{REG_PREFIX}}10, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}11, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}12, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}13, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}14, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    {{INSN_XOR_BC}} {{REG_PREFIX}}15, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}16, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}17, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}18, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}19, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    {{INSN_XOR_BC}} {{REG_PREFIX}}20, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}21, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}22, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}23, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}24, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    leaq    .Lrc(%rip), %r8
    movl    $12, %ecx
.balign 32
.Lround:

    /* ================================================================ */
    /* Round N (even): RC at (%r8)                                      */
    /* ================================================================ */

    /* --- Theta: D[x] = C[(x+4)%5] ^ ROL(C[(x+1)%5], 1) ----------- */
    /* Pre-compute D into ymm30, apply to 5 lanes via vpxorq.          */

    /* D[0] = C[4] ^ ROL(C[1], 1) → apply to lanes 0,5,10,15,20 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}26, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}29, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}0,  {{REG_PREFIX}}0
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}5,  {{REG_PREFIX}}5
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}10, {{REG_PREFIX}}10
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}15, {{REG_PREFIX}}15
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}20, {{REG_PREFIX}}20

    /* D[1] = C[0] ^ ROL(C[2], 1) → apply to lanes 1,6,11,16,21 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}27, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}25, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}1,  {{REG_PREFIX}}1
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}6,  {{REG_PREFIX}}6
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}11, {{REG_PREFIX}}11
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}16, {{REG_PREFIX}}16
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}21, {{REG_PREFIX}}21

    /* D[2] = C[1] ^ ROL(C[3], 1) → apply to lanes 2,7,12,17,22 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}28, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}26, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}2,  {{REG_PREFIX}}2
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}7,  {{REG_PREFIX}}7
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}12, {{REG_PREFIX}}12
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}17, {{REG_PREFIX}}17
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}22, {{REG_PREFIX}}22

    /* D[3] = C[2] ^ ROL(C[4], 1) → apply to lanes 3,8,13,18,23 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}29, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}27, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}3,  {{REG_PREFIX}}3
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}8,  {{REG_PREFIX}}8
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}13, {{REG_PREFIX}}13
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}18, {{REG_PREFIX}}18
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}23, {{REG_PREFIX}}23

    /* D[4] = C[3] ^ ROL(C[0], 1) → apply to lanes 4,9,14,19,24 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}25, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}28, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}4,  {{REG_PREFIX}}4
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}9,  {{REG_PREFIX}}9
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}14, {{REG_PREFIX}}14
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}19, {{REG_PREFIX}}19
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}24, {{REG_PREFIX}}24

    /* --- Fused Rho + Pi: 24-cycle ---------------------------------- */

    {{INSN_ROL64}}  $1,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_ROL64}}  $44, {{REG_PREFIX}}6,  {{REG_PREFIX}}1
    {{INSN_ROL64}}  $20, {{REG_PREFIX}}9,  {{REG_PREFIX}}6
    {{INSN_ROL64}}  $61, {{REG_PREFIX}}22, {{REG_PREFIX}}9
    {{INSN_ROL64}}  $39, {{REG_PREFIX}}14, {{REG_PREFIX}}22
    {{INSN_ROL64}}  $18, {{REG_PREFIX}}20, {{REG_PREFIX}}14
    {{INSN_ROL64}}  $62, {{REG_PREFIX}}2,  {{REG_PREFIX}}20
    {{INSN_ROL64}}  $43, {{REG_PREFIX}}12, {{REG_PREFIX}}2
    {{INSN_ROL64}}  $25, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_ROL64}}  $8,  {{REG_PREFIX}}19, {{REG_PREFIX}}13
    {{INSN_ROL64}}  $56, {{REG_PREFIX}}23, {{REG_PREFIX}}19
    {{INSN_ROL64}}  $41, {{REG_PREFIX}}15, {{REG_PREFIX}}23
    {{INSN_ROL64}}  $27, {{REG_PREFIX}}4,  {{REG_PREFIX}}15
    {{INSN_ROL64}}  $14, {{REG_PREFIX}}24, {{REG_PREFIX}}4
    {{INSN_ROL64}}  $2,  {{REG_PREFIX}}21, {{REG_PREFIX}}24
    {{INSN_ROL64}}  $55, {{REG_PREFIX}}8,  {{REG_PREFIX}}21
    {{INSN_ROL64}}  $45, {{REG_PREFIX}}16, {{REG_PREFIX}}8
    {{INSN_ROL64}}  $36, {{REG_PREFIX}}5,  {{REG_PREFIX}}16
    {{INSN_ROL64}}  $28, {{REG_PREFIX}}3,  {{REG_PREFIX}}5
    {{INSN_ROL64}}  $21, {{REG_PREFIX}}18, {{REG_PREFIX}}3
    {{INSN_ROL64}}  $15, {{REG_PREFIX}}17, {{REG_PREFIX}}18
    {{INSN_ROL64}}  $10, {{REG_PREFIX}}11, {{REG_PREFIX}}17
    {{INSN_ROL64}}  $6,  {{REG_PREFIX}}7,  {{REG_PREFIX}}11
    {{INSN_ROL64}}  $3,  {{REG_PREFIX}}10, {{REG_PREFIX}}7
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10

    /* --- Chi + Iota + prepare-theta (accumulate C for next round) -- */

    /* Row 0: lanes 0,1,2,3,4 — Chi + Iota on lane 0 */
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}2,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_XOR_BC}} (%r8){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}3,  {{REG_PREFIX}}2,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}4,  {{REG_PREFIX}}3,  {{REG_PREFIX}}2
    {{INSN_CHI}},   {{REG_PREFIX}}0,  {{REG_PREFIX}}4,  {{REG_PREFIX}}3
    {{INSN_CHI}},   {{REG_PREFIX}}1,  {{REG_PREFIX}}0,  {{REG_PREFIX}}4
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}0
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}1
    /* C[x] = lane[x] (init from row 0) */
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}25
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}26
    {{INSN_MOV}}    {{REG_PREFIX}}2,  {{REG_PREFIX}}27
    {{INSN_MOV}}    {{REG_PREFIX}}3,  {{REG_PREFIX}}28
    {{INSN_MOV}}    {{REG_PREFIX}}4,  {{REG_PREFIX}}29

    /* Row 1: lanes 5,6,7,8,9 */
    {{INSN_MOV}}    {{REG_PREFIX}}5,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}6,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}7,  {{REG_PREFIX}}6,  {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}8,  {{REG_PREFIX}}7,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}9,  {{REG_PREFIX}}8,  {{REG_PREFIX}}7
    {{INSN_CHI}},   {{REG_PREFIX}}5,  {{REG_PREFIX}}9,  {{REG_PREFIX}}8
    {{INSN_CHI}},   {{REG_PREFIX}}6,  {{REG_PREFIX}}5,  {{REG_PREFIX}}9
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}5
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}6
    /* C[x] ^= lane[x+5] */
    {{INSN_XOR_BC}} {{REG_PREFIX}}5,  {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}6,  {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}7,  {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}8,  {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}9,  {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 2: lanes 10,11,12,13,14 */
    {{INSN_MOV}}    {{REG_PREFIX}}10, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}11, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}12, {{REG_PREFIX}}11, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}13, {{REG_PREFIX}}12, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}14, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_CHI}},   {{REG_PREFIX}}10, {{REG_PREFIX}}14, {{REG_PREFIX}}13
    {{INSN_CHI}},   {{REG_PREFIX}}11, {{REG_PREFIX}}10, {{REG_PREFIX}}14
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}11
    /* C[x] ^= lane[x+10] */
    {{INSN_XOR_BC}} {{REG_PREFIX}}10, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}11, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}12, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}13, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}14, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 3: lanes 15,16,17,18,19 */
    {{INSN_MOV}}    {{REG_PREFIX}}15, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}16, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}17, {{REG_PREFIX}}16, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}18, {{REG_PREFIX}}17, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}19, {{REG_PREFIX}}18, {{REG_PREFIX}}17
    {{INSN_CHI}},   {{REG_PREFIX}}15, {{REG_PREFIX}}19, {{REG_PREFIX}}18
    {{INSN_CHI}},   {{REG_PREFIX}}16, {{REG_PREFIX}}15, {{REG_PREFIX}}19
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}15
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}16
    /* C[x] ^= lane[x+15] */
    {{INSN_XOR_BC}} {{REG_PREFIX}}15, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}16, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}17, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}18, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}19, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 4: lanes 20,21,22,23,24 */
    {{INSN_MOV}}    {{REG_PREFIX}}20, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}21, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}22, {{REG_PREFIX}}21, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}23, {{REG_PREFIX}}22, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}24, {{REG_PREFIX}}23, {{REG_PREFIX}}22
    {{INSN_CHI}},   {{REG_PREFIX}}20, {{REG_PREFIX}}24, {{REG_PREFIX}}23
    {{INSN_CHI}},   {{REG_PREFIX}}21, {{REG_PREFIX}}20, {{REG_PREFIX}}24
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}20
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}21
    /* C[x] ^= lane[x+20] — parity complete */
    {{INSN_XOR_BC}} {{REG_PREFIX}}20, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}21, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}22, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}23, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}24, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* ================================================================ */
    /* Round N+1 (odd): RC at 8(%r8)                                    */
    /* ================================================================ */

    /* --- Theta: D via pre-computed + vpxorq ------------------------- */

    /* D[0] = C[4] ^ ROL(C[1], 1) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}26, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}29, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}0,  {{REG_PREFIX}}0
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}5,  {{REG_PREFIX}}5
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}10, {{REG_PREFIX}}10
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}15, {{REG_PREFIX}}15
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}20, {{REG_PREFIX}}20

    /* D[1] = C[0] ^ ROL(C[2], 1) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}27, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}25, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}1,  {{REG_PREFIX}}1
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}6,  {{REG_PREFIX}}6
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}11, {{REG_PREFIX}}11
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}16, {{REG_PREFIX}}16
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}21, {{REG_PREFIX}}21

    /* D[2] = C[1] ^ ROL(C[3], 1) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}28, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}26, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}2,  {{REG_PREFIX}}2
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}7,  {{REG_PREFIX}}7
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}12, {{REG_PREFIX}}12
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}17, {{REG_PREFIX}}17
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}22, {{REG_PREFIX}}22

    /* D[3] = C[2] ^ ROL(C[4], 1) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}29, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}27, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}3,  {{REG_PREFIX}}3
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}8,  {{REG_PREFIX}}8
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}13, {{REG_PREFIX}}13
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}18, {{REG_PREFIX}}18
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}23, {{REG_PREFIX}}23

    /* D[4] = C[3] ^ ROL(C[0], 1) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}25, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}28, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}4,  {{REG_PREFIX}}4
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}9,  {{REG_PREFIX}}9
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}14, {{REG_PREFIX}}14
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}19, {{REG_PREFIX}}19
    {{INSN_XOR_BC}} {{REG_PREFIX}}30, {{REG_PREFIX}}24, {{REG_PREFIX}}24

    /* --- Fused Rho+Pi ---------------------------------------------- */
    {{INSN_ROL64}}  $1,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_ROL64}}  $44, {{REG_PREFIX}}6,  {{REG_PREFIX}}1
    {{INSN_ROL64}}  $20, {{REG_PREFIX}}9,  {{REG_PREFIX}}6
    {{INSN_ROL64}}  $61, {{REG_PREFIX}}22, {{REG_PREFIX}}9
    {{INSN_ROL64}}  $39, {{REG_PREFIX}}14, {{REG_PREFIX}}22
    {{INSN_ROL64}}  $18, {{REG_PREFIX}}20, {{REG_PREFIX}}14
    {{INSN_ROL64}}  $62, {{REG_PREFIX}}2,  {{REG_PREFIX}}20
    {{INSN_ROL64}}  $43, {{REG_PREFIX}}12, {{REG_PREFIX}}2
    {{INSN_ROL64}}  $25, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_ROL64}}  $8,  {{REG_PREFIX}}19, {{REG_PREFIX}}13
    {{INSN_ROL64}}  $56, {{REG_PREFIX}}23, {{REG_PREFIX}}19
    {{INSN_ROL64}}  $41, {{REG_PREFIX}}15, {{REG_PREFIX}}23
    {{INSN_ROL64}}  $27, {{REG_PREFIX}}4,  {{REG_PREFIX}}15
    {{INSN_ROL64}}  $14, {{REG_PREFIX}}24, {{REG_PREFIX}}4
    {{INSN_ROL64}}  $2,  {{REG_PREFIX}}21, {{REG_PREFIX}}24
    {{INSN_ROL64}}  $55, {{REG_PREFIX}}8,  {{REG_PREFIX}}21
    {{INSN_ROL64}}  $45, {{REG_PREFIX}}16, {{REG_PREFIX}}8
    {{INSN_ROL64}}  $36, {{REG_PREFIX}}5,  {{REG_PREFIX}}16
    {{INSN_ROL64}}  $28, {{REG_PREFIX}}3,  {{REG_PREFIX}}5
    {{INSN_ROL64}}  $21, {{REG_PREFIX}}18, {{REG_PREFIX}}3
    {{INSN_ROL64}}  $15, {{REG_PREFIX}}17, {{REG_PREFIX}}18
    {{INSN_ROL64}}  $10, {{REG_PREFIX}}11, {{REG_PREFIX}}17
    {{INSN_ROL64}}  $6,  {{REG_PREFIX}}7,  {{REG_PREFIX}}11
    {{INSN_ROL64}}  $3,  {{REG_PREFIX}}10, {{REG_PREFIX}}7
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10

    /* --- Chi + Iota (RC at 8(%r8)) + prepare-theta ----------------- */

    /* Row 0 + Iota */
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}2,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_XOR_BC}} 8(%r8){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}3,  {{REG_PREFIX}}2,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}4,  {{REG_PREFIX}}3,  {{REG_PREFIX}}2
    {{INSN_CHI}},   {{REG_PREFIX}}0,  {{REG_PREFIX}}4,  {{REG_PREFIX}}3
    {{INSN_CHI}},   {{REG_PREFIX}}1,  {{REG_PREFIX}}0,  {{REG_PREFIX}}4
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}0
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}1
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}25
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}26
    {{INSN_MOV}}    {{REG_PREFIX}}2,  {{REG_PREFIX}}27
    {{INSN_MOV}}    {{REG_PREFIX}}3,  {{REG_PREFIX}}28
    {{INSN_MOV}}    {{REG_PREFIX}}4,  {{REG_PREFIX}}29

    /* Row 1 */
    {{INSN_MOV}}    {{REG_PREFIX}}5,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}6,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}7,  {{REG_PREFIX}}6,  {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}8,  {{REG_PREFIX}}7,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}9,  {{REG_PREFIX}}8,  {{REG_PREFIX}}7
    {{INSN_CHI}},   {{REG_PREFIX}}5,  {{REG_PREFIX}}9,  {{REG_PREFIX}}8
    {{INSN_CHI}},   {{REG_PREFIX}}6,  {{REG_PREFIX}}5,  {{REG_PREFIX}}9
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}5
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}6
    {{INSN_XOR_BC}} {{REG_PREFIX}}5,  {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}6,  {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}7,  {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}8,  {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}9,  {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 2 */
    {{INSN_MOV}}    {{REG_PREFIX}}10, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}11, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}12, {{REG_PREFIX}}11, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}13, {{REG_PREFIX}}12, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}14, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_CHI}},   {{REG_PREFIX}}10, {{REG_PREFIX}}14, {{REG_PREFIX}}13
    {{INSN_CHI}},   {{REG_PREFIX}}11, {{REG_PREFIX}}10, {{REG_PREFIX}}14
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}11
    {{INSN_XOR_BC}} {{REG_PREFIX}}10, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}11, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}12, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}13, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}14, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 3 */
    {{INSN_MOV}}    {{REG_PREFIX}}15, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}16, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}17, {{REG_PREFIX}}16, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}18, {{REG_PREFIX}}17, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}19, {{REG_PREFIX}}18, {{REG_PREFIX}}17
    {{INSN_CHI}},   {{REG_PREFIX}}15, {{REG_PREFIX}}19, {{REG_PREFIX}}18
    {{INSN_CHI}},   {{REG_PREFIX}}16, {{REG_PREFIX}}15, {{REG_PREFIX}}19
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}15
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}16
    {{INSN_XOR_BC}} {{REG_PREFIX}}15, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}16, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}17, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}18, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}19, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Row 4 */
    {{INSN_MOV}}    {{REG_PREFIX}}20, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}21, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}22, {{REG_PREFIX}}21, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}23, {{REG_PREFIX}}22, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}24, {{REG_PREFIX}}23, {{REG_PREFIX}}22
    {{INSN_CHI}},   {{REG_PREFIX}}20, {{REG_PREFIX}}24, {{REG_PREFIX}}23
    {{INSN_CHI}},   {{REG_PREFIX}}21, {{REG_PREFIX}}20, {{REG_PREFIX}}24
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}20
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}21
    {{INSN_XOR_BC}} {{REG_PREFIX}}20, {{REG_PREFIX}}25, {{REG_PREFIX}}25
    {{INSN_XOR_BC}} {{REG_PREFIX}}21, {{REG_PREFIX}}26, {{REG_PREFIX}}26
    {{INSN_XOR_BC}} {{REG_PREFIX}}22, {{REG_PREFIX}}27, {{REG_PREFIX}}27
    {{INSN_XOR_BC}} {{REG_PREFIX}}23, {{REG_PREFIX}}28, {{REG_PREFIX}}28
    {{INSN_XOR_BC}} {{REG_PREFIX}}24, {{REG_PREFIX}}29, {{REG_PREFIX}}29

    /* Advance RC by 2 rounds, decrement loop counter */
    addq    $16, %r8
    decl    %ecx
    jnz     .Lround

    ret
.size   .Lpermute_f1600, .-.Lpermute_f1600

{{! ===== Register-resident sponge absorb functions ===== }}

{{#set WORDS_136=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16}}
{{#set WORDS_168=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20}}
{{#set WORDS_72=0|1|2|3|4|5|6|7|8}}

{{#set SPONGE_RATES=136|168|72}}
{{#for SRATE in SPONGE_RATES}}
{{#set SWORDS}}{{SRATE|resolve|WORDS_}}{{/set}}

.globl  dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}
.type   dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}:
    pushq   %rbp
    pushq   %rbx
    pushq   %r12
    pushq   %r13
    pushq   %r14
    movq    %rdi, %rbp
    movq    %rsi, %r12
    movq    %rdx, %r13
    movzbl  %cl,  %r14d
    vpxorq  %xmm0, %xmm0, %xmm0
{{#for i in 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24}}
    vmovdqa64 %ymm0, %ymm{{i}}
{{/for}}
.Labsorb_full_{{SRATE}}:
    cmpq    ${{SRATE}}, %r13
    jb      .Labsorb_pad_{{SRATE}}
{{#for w in SWORDS}}
    vmovq   {{w|math|$*8}}(%r12), {{REG_1X_PREFIX}}30
    vpxorq  {{REG_PREFIX}}30, {{REG_PREFIX}}{{w}}, {{REG_PREFIX}}{{w}}
{{/for}}
    addq    ${{SRATE}}, %r12
    subq    ${{SRATE}}, %r13
    call    .Lpermute_f1600
    jmp     .Labsorb_full_{{SRATE}}
.Labsorb_pad_{{SRATE}}:
    subq    $224, %rsp
    vpxorq  %ymm30, %ymm30, %ymm30
    vmovdqu64 %ymm30, 0(%rsp)
    vmovdqu64 %ymm30, 32(%rsp)
    vmovdqu64 %ymm30, 64(%rsp)
    vmovdqu64 %ymm30, 96(%rsp)
    vmovdqu64 %ymm30, 128(%rsp)
    vmovdqu64 %ymm30, 160(%rsp)
    vmovdqu64 %ymm30, 192(%rsp)
    movq    %r13, %rcx
    leaq    (%rsp), %rdi
    movq    %r12, %rsi
    rep     movsb
    movb    %r14b, (%rsp,%r13)
    xorb    $0x80, {{SRATE|math|$-1}}(%rsp)
{{#for w in SWORDS}}
    vmovq   {{w|math|$*8}}(%rsp), {{REG_1X_PREFIX}}30
    vpxorq  {{REG_PREFIX}}30, {{REG_PREFIX}}{{w}}, {{REG_PREFIX}}{{w}}
{{/for}}
    addq    $224, %rsp
    call    .Lpermute_f1600
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}}, ({{STRIDE_1X}}*{{i}})(%rbp)
{{/for}}
    popq    %r14
    popq    %r13
    popq    %r12
    popq    %rbx
    popq    %rbp
    ret
.size   dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}, .-dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}

.globl  dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}
.type   dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}:
    pushq   %rbp
    pushq   %rbx
    pushq   %r12
    movq    %rdi, %rbp
    movq    %rsi, %r12
    movq    %rdx, %rbx
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rbp), {{REG_1X_PREFIX}}{{i}}
{{/for}}
.Lsqueeze_loop_{{SRATE}}:
    testq   %rbx, %rbx
    jz      .Lsqueeze_done_{{SRATE}}
    call    .Lpermute_f1600
{{#for w in SWORDS}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{w}}, {{w|math|$*8}}(%r12)
{{/for}}
    addq    ${{SRATE}}, %r12
    decq    %rbx
    jmp     .Lsqueeze_loop_{{SRATE}}
.Lsqueeze_done_{{SRATE}}:
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}}, ({{STRIDE_1X}}*{{i}})(%rbp)
{{/for}}
    popq    %r12
    popq    %rbx
    popq    %rbp
    ret
.size   dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}, .-dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}

{{/for}}

{{! ===== Round constants ===== }}
.section .rodata
.balign 64
.Lrc:
{{#for rc in RC_LIST}}
    .quad   {{rc}}
{{/for}}

.section .note.GNU-stack,"",@progbits
