{{! x86 AVX-512VL Keccak-f[1600] — compact looped assembly with fused Rho+Pi }}
{{! Uses vpternlogq (3-way XOR, Chi), vprolq (rotate), EVEX 32 YMM regs }}
{{! Instruction mnemonics come from .env file via ENVIRON }}
/*
 * dap_keccak_f1600_{{FUNC_SUFFIX}}.S — AUTO-GENERATED by dap_tpl
 *
 * x86-64 Keccak-f[1600] — compact looped with fused Rho+Pi.
 *
 * Key optimizations vs fully-unrolled:
 *   - Looped 24 rounds — ~750 bytes vs 18.8 KB (25x smaller → L1I friendly)
 *   - Fused Rho+Pi: vprolq with different src/dst walks Pi cycles (26 ops vs 49)
 *   - Theta D+apply via vpternlogq $0x96 (saves 5 vpxorq per round)
 *   - Zero-latency register rename for Pi cycle moves on Zen4
 *
 * Per-round instruction count: ~117 (was 144 in separate Rho+Pi version)
 *
 * Register allocation:
 *   ymm0 – ymm24  : 25 state lanes (identity order at loop entry)
 *   ymm25 – ymm29  : 5 Theta column parity temporaries
 *   ymm30, ymm31   : scratch (fused Rho+Pi save, Chi row)
 *   rcx             : round counter
 *   r8              : round constant pointer
 *
 * Copyright: DeM Labs Inc. 2026
 * License: GNU GPL v3
 * @generated
 */

.text

{{! ===== 1x permutation wrapper ===== }}
.globl  dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.type   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rdi),  {{REG_1X_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}},  ({{STRIDE_1X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, .-dap_hash_keccak_permute_{{FUNC_SUFFIX}}

{{! ===== 4x permutation wrapper (interleaved layout) ===== }}
.globl  dap_keccak_x4_permute_{{FUNC_SUFFIX}}
.type   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_x4_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_4X}}   ({{STRIDE_4X}}*{{i}})(%rdi),  {{REG_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_4X}}   {{REG_PREFIX}}{{i}},  ({{STRIDE_4X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, .-dap_keccak_x4_permute_{{FUNC_SUFFIX}}

{{! ===== Core permutation: 2-round unrolled loop (12 iters), fused Rho+Pi ===== }}
.balign 64
.Lpermute_f1600:
    leaq    .Lrc(%rip), %r8
    movl    $12, %ecx
.balign 32
.Lround:

    /* ================================================================ */
    /* Round N (even): RC at (%r8)                                      */
    /* ================================================================ */

    /* C[x] = A[x] ^ A[x+5] ^ A[x+10] ^ A[x+15] ^ A[x+20] */
    {{INSN_MOV}}    {{REG_PREFIX}}0, {{REG_PREFIX}}25
    {{INSN_XOR3}},  {{REG_PREFIX}}5, {{REG_PREFIX}}10, {{REG_PREFIX}}25
    {{INSN_XOR3}},  {{REG_PREFIX}}15, {{REG_PREFIX}}20, {{REG_PREFIX}}25

    {{INSN_MOV}}    {{REG_PREFIX}}1, {{REG_PREFIX}}26
    {{INSN_XOR3}},  {{REG_PREFIX}}6, {{REG_PREFIX}}11, {{REG_PREFIX}}26
    {{INSN_XOR3}},  {{REG_PREFIX}}16, {{REG_PREFIX}}21, {{REG_PREFIX}}26

    {{INSN_MOV}}    {{REG_PREFIX}}2, {{REG_PREFIX}}27
    {{INSN_XOR3}},  {{REG_PREFIX}}7, {{REG_PREFIX}}12, {{REG_PREFIX}}27
    {{INSN_XOR3}},  {{REG_PREFIX}}17, {{REG_PREFIX}}22, {{REG_PREFIX}}27

    {{INSN_MOV}}    {{REG_PREFIX}}3, {{REG_PREFIX}}28
    {{INSN_XOR3}},  {{REG_PREFIX}}8, {{REG_PREFIX}}13, {{REG_PREFIX}}28
    {{INSN_XOR3}},  {{REG_PREFIX}}18, {{REG_PREFIX}}23, {{REG_PREFIX}}28

    {{INSN_MOV}}    {{REG_PREFIX}}4, {{REG_PREFIX}}29
    {{INSN_XOR3}},  {{REG_PREFIX}}9, {{REG_PREFIX}}14, {{REG_PREFIX}}29
    {{INSN_XOR3}},  {{REG_PREFIX}}19, {{REG_PREFIX}}24, {{REG_PREFIX}}29

    /* D[x] = C[(x+4)%5] ^ ROL64(C[(x+1)%5], 1); apply via vpternlogq */

    /* D[0]: tmp=ROL(C[1],1), apply to col 0 (A[0,5,10,15,20]) */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}26, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}0
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}5
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}10
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}15
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}20

    /* D[1]: tmp=ROL(C[2],1), apply to col 1 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}27, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}1
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}6
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}11
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}16
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}21

    /* D[2]: tmp=ROL(C[3],1), apply to col 2 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}28, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}2
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}7
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}12
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}17
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}22

    /* D[3]: tmp=ROL(C[4],1), apply to col 3 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}29, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}3
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}8
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}13
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}18
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}23

    /* D[4]: tmp=ROL(C[0],1), apply to col 4 */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}25, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}4
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}9
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}14
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}19
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}24

    /* ================================================================ */
    /* Fused Rho + Pi: vprolq with different src/dst walks Pi cycle.    */
    /* Pi: B[x,y] = A[(x+3y)%5, x]; flat pi(i) maps lane i → dest.    */
    /* Single 24-cycle (lane 0 is fixed with rho=0):                    */
    /*   1→10→7→11→17→18→3→5→16→8→21→24→4→15→23→19→13→12→2→20→14→22→9→6→1 */
    /* Walk backward: save first, cascade, restore last.                */
    /* ================================================================ */

    {{INSN_ROL64}}  $1,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30   /* save ROL(lane1, rho[1])  */
    {{INSN_ROL64}}  $44, {{REG_PREFIX}}6,  {{REG_PREFIX}}1    /* pi(6)=1   */
    {{INSN_ROL64}}  $20, {{REG_PREFIX}}9,  {{REG_PREFIX}}6    /* pi(9)=6   */
    {{INSN_ROL64}}  $61, {{REG_PREFIX}}22, {{REG_PREFIX}}9    /* pi(22)=9  */
    {{INSN_ROL64}}  $39, {{REG_PREFIX}}14, {{REG_PREFIX}}22   /* pi(14)=22 */
    {{INSN_ROL64}}  $18, {{REG_PREFIX}}20, {{REG_PREFIX}}14   /* pi(20)=14 */
    {{INSN_ROL64}}  $62, {{REG_PREFIX}}2,  {{REG_PREFIX}}20   /* pi(2)=20  */
    {{INSN_ROL64}}  $43, {{REG_PREFIX}}12, {{REG_PREFIX}}2    /* pi(12)=2  */
    {{INSN_ROL64}}  $25, {{REG_PREFIX}}13, {{REG_PREFIX}}12   /* pi(13)=12 */
    {{INSN_ROL64}}  $8,  {{REG_PREFIX}}19, {{REG_PREFIX}}13   /* pi(19)=13 */
    {{INSN_ROL64}}  $56, {{REG_PREFIX}}23, {{REG_PREFIX}}19   /* pi(23)=19 */
    {{INSN_ROL64}}  $41, {{REG_PREFIX}}15, {{REG_PREFIX}}23   /* pi(15)=23 */
    {{INSN_ROL64}}  $27, {{REG_PREFIX}}4,  {{REG_PREFIX}}15   /* pi(4)=15  */
    {{INSN_ROL64}}  $14, {{REG_PREFIX}}24, {{REG_PREFIX}}4    /* pi(24)=4  */
    {{INSN_ROL64}}  $2,  {{REG_PREFIX}}21, {{REG_PREFIX}}24   /* pi(21)=24 */
    {{INSN_ROL64}}  $55, {{REG_PREFIX}}8,  {{REG_PREFIX}}21   /* pi(8)=21  */
    {{INSN_ROL64}}  $45, {{REG_PREFIX}}16, {{REG_PREFIX}}8    /* pi(16)=8  */
    {{INSN_ROL64}}  $36, {{REG_PREFIX}}5,  {{REG_PREFIX}}16   /* pi(5)=16  */
    {{INSN_ROL64}}  $28, {{REG_PREFIX}}3,  {{REG_PREFIX}}5    /* pi(3)=5   */
    {{INSN_ROL64}}  $21, {{REG_PREFIX}}18, {{REG_PREFIX}}3    /* pi(18)=3  */
    {{INSN_ROL64}}  $15, {{REG_PREFIX}}17, {{REG_PREFIX}}18   /* pi(17)=18 */
    {{INSN_ROL64}}  $10, {{REG_PREFIX}}11, {{REG_PREFIX}}17   /* pi(11)=17 */
    {{INSN_ROL64}}  $6,  {{REG_PREFIX}}7,  {{REG_PREFIX}}11   /* pi(7)=11  */
    {{INSN_ROL64}}  $3,  {{REG_PREFIX}}10, {{REG_PREFIX}}7    /* pi(10)=7  */
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10        /* pi(1)=10  */

    /* ================================================================ */
    /* Chi + Iota: row by row, a[x] ^= ~a[x+1] & a[x+2]              */
    /* Row 0 also XORs round constant into lane 0 (Iota).              */
    /* ================================================================ */

    /* Row 0: lanes 0,1,2,3,4 */
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}2,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_XOR_BC}} (%r8){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}3,  {{REG_PREFIX}}2,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}4,  {{REG_PREFIX}}3,  {{REG_PREFIX}}2
    {{INSN_CHI}},   {{REG_PREFIX}}0,  {{REG_PREFIX}}4,  {{REG_PREFIX}}3
    {{INSN_CHI}},   {{REG_PREFIX}}1,  {{REG_PREFIX}}0,  {{REG_PREFIX}}4
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}0
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}1

    /* Row 1: lanes 5,6,7,8,9 */
    {{INSN_MOV}}    {{REG_PREFIX}}5,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}6,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}7,  {{REG_PREFIX}}6,  {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}8,  {{REG_PREFIX}}7,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}9,  {{REG_PREFIX}}8,  {{REG_PREFIX}}7
    {{INSN_CHI}},   {{REG_PREFIX}}5,  {{REG_PREFIX}}9,  {{REG_PREFIX}}8
    {{INSN_CHI}},   {{REG_PREFIX}}6,  {{REG_PREFIX}}5,  {{REG_PREFIX}}9
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}5
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}6

    /* Row 2: lanes 10,11,12,13,14 */
    {{INSN_MOV}}    {{REG_PREFIX}}10, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}11, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}12, {{REG_PREFIX}}11, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}13, {{REG_PREFIX}}12, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}14, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_CHI}},   {{REG_PREFIX}}10, {{REG_PREFIX}}14, {{REG_PREFIX}}13
    {{INSN_CHI}},   {{REG_PREFIX}}11, {{REG_PREFIX}}10, {{REG_PREFIX}}14
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}11

    /* Row 3: lanes 15,16,17,18,19 */
    {{INSN_MOV}}    {{REG_PREFIX}}15, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}16, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}17, {{REG_PREFIX}}16, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}18, {{REG_PREFIX}}17, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}19, {{REG_PREFIX}}18, {{REG_PREFIX}}17
    {{INSN_CHI}},   {{REG_PREFIX}}15, {{REG_PREFIX}}19, {{REG_PREFIX}}18
    {{INSN_CHI}},   {{REG_PREFIX}}16, {{REG_PREFIX}}15, {{REG_PREFIX}}19
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}15
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}16

    /* Row 4: lanes 20,21,22,23,24 */
    {{INSN_MOV}}    {{REG_PREFIX}}20, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}21, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}22, {{REG_PREFIX}}21, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}23, {{REG_PREFIX}}22, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}24, {{REG_PREFIX}}23, {{REG_PREFIX}}22
    {{INSN_CHI}},   {{REG_PREFIX}}20, {{REG_PREFIX}}24, {{REG_PREFIX}}23
    {{INSN_CHI}},   {{REG_PREFIX}}21, {{REG_PREFIX}}20, {{REG_PREFIX}}24
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}20
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}21

    /* ================================================================ */
    /* Round N+1 (odd): RC at 8(%r8)                                    */
    /* ================================================================ */

    /* Theta: column parity */
    {{INSN_MOV}}    {{REG_PREFIX}}0, {{REG_PREFIX}}25
    {{INSN_XOR3}},  {{REG_PREFIX}}5, {{REG_PREFIX}}10, {{REG_PREFIX}}25
    {{INSN_XOR3}},  {{REG_PREFIX}}15, {{REG_PREFIX}}20, {{REG_PREFIX}}25

    {{INSN_MOV}}    {{REG_PREFIX}}1, {{REG_PREFIX}}26
    {{INSN_XOR3}},  {{REG_PREFIX}}6, {{REG_PREFIX}}11, {{REG_PREFIX}}26
    {{INSN_XOR3}},  {{REG_PREFIX}}16, {{REG_PREFIX}}21, {{REG_PREFIX}}26

    {{INSN_MOV}}    {{REG_PREFIX}}2, {{REG_PREFIX}}27
    {{INSN_XOR3}},  {{REG_PREFIX}}7, {{REG_PREFIX}}12, {{REG_PREFIX}}27
    {{INSN_XOR3}},  {{REG_PREFIX}}17, {{REG_PREFIX}}22, {{REG_PREFIX}}27

    {{INSN_MOV}}    {{REG_PREFIX}}3, {{REG_PREFIX}}28
    {{INSN_XOR3}},  {{REG_PREFIX}}8, {{REG_PREFIX}}13, {{REG_PREFIX}}28
    {{INSN_XOR3}},  {{REG_PREFIX}}18, {{REG_PREFIX}}23, {{REG_PREFIX}}28

    {{INSN_MOV}}    {{REG_PREFIX}}4, {{REG_PREFIX}}29
    {{INSN_XOR3}},  {{REG_PREFIX}}9, {{REG_PREFIX}}14, {{REG_PREFIX}}29
    {{INSN_XOR3}},  {{REG_PREFIX}}19, {{REG_PREFIX}}24, {{REG_PREFIX}}29

    /* Theta D+apply via vpternlogq */
    {{INSN_ROL64}}  $1, {{REG_PREFIX}}26, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}0
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}5
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}10
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}15
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}29, {{REG_PREFIX}}20

    {{INSN_ROL64}}  $1, {{REG_PREFIX}}27, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}1
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}6
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}11
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}16
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}25, {{REG_PREFIX}}21

    {{INSN_ROL64}}  $1, {{REG_PREFIX}}28, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}2
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}7
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}12
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}17
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}26, {{REG_PREFIX}}22

    {{INSN_ROL64}}  $1, {{REG_PREFIX}}29, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}3
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}8
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}13
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}18
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}27, {{REG_PREFIX}}23

    {{INSN_ROL64}}  $1, {{REG_PREFIX}}25, {{REG_PREFIX}}30
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}4
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}9
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}14
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}19
    {{INSN_XOR3}},  {{REG_PREFIX}}30, {{REG_PREFIX}}28, {{REG_PREFIX}}24

    /* Fused Rho+Pi: 24-cycle */
    {{INSN_ROL64}}  $1,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_ROL64}}  $44, {{REG_PREFIX}}6,  {{REG_PREFIX}}1
    {{INSN_ROL64}}  $20, {{REG_PREFIX}}9,  {{REG_PREFIX}}6
    {{INSN_ROL64}}  $61, {{REG_PREFIX}}22, {{REG_PREFIX}}9
    {{INSN_ROL64}}  $39, {{REG_PREFIX}}14, {{REG_PREFIX}}22
    {{INSN_ROL64}}  $18, {{REG_PREFIX}}20, {{REG_PREFIX}}14
    {{INSN_ROL64}}  $62, {{REG_PREFIX}}2,  {{REG_PREFIX}}20
    {{INSN_ROL64}}  $43, {{REG_PREFIX}}12, {{REG_PREFIX}}2
    {{INSN_ROL64}}  $25, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_ROL64}}  $8,  {{REG_PREFIX}}19, {{REG_PREFIX}}13
    {{INSN_ROL64}}  $56, {{REG_PREFIX}}23, {{REG_PREFIX}}19
    {{INSN_ROL64}}  $41, {{REG_PREFIX}}15, {{REG_PREFIX}}23
    {{INSN_ROL64}}  $27, {{REG_PREFIX}}4,  {{REG_PREFIX}}15
    {{INSN_ROL64}}  $14, {{REG_PREFIX}}24, {{REG_PREFIX}}4
    {{INSN_ROL64}}  $2,  {{REG_PREFIX}}21, {{REG_PREFIX}}24
    {{INSN_ROL64}}  $55, {{REG_PREFIX}}8,  {{REG_PREFIX}}21
    {{INSN_ROL64}}  $45, {{REG_PREFIX}}16, {{REG_PREFIX}}8
    {{INSN_ROL64}}  $36, {{REG_PREFIX}}5,  {{REG_PREFIX}}16
    {{INSN_ROL64}}  $28, {{REG_PREFIX}}3,  {{REG_PREFIX}}5
    {{INSN_ROL64}}  $21, {{REG_PREFIX}}18, {{REG_PREFIX}}3
    {{INSN_ROL64}}  $15, {{REG_PREFIX}}17, {{REG_PREFIX}}18
    {{INSN_ROL64}}  $10, {{REG_PREFIX}}11, {{REG_PREFIX}}17
    {{INSN_ROL64}}  $6,  {{REG_PREFIX}}7,  {{REG_PREFIX}}11
    {{INSN_ROL64}}  $3,  {{REG_PREFIX}}10, {{REG_PREFIX}}7
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10

    /* Chi + Iota (RC at 8(%r8)) */
    {{INSN_MOV}}    {{REG_PREFIX}}0,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}1,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}2,  {{REG_PREFIX}}1,  {{REG_PREFIX}}30
    {{INSN_XOR_BC}} 8(%r8){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}3,  {{REG_PREFIX}}2,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}4,  {{REG_PREFIX}}3,  {{REG_PREFIX}}2
    {{INSN_CHI}},   {{REG_PREFIX}}0,  {{REG_PREFIX}}4,  {{REG_PREFIX}}3
    {{INSN_CHI}},   {{REG_PREFIX}}1,  {{REG_PREFIX}}0,  {{REG_PREFIX}}4
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}0
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}1

    {{INSN_MOV}}    {{REG_PREFIX}}5,  {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}6,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}7,  {{REG_PREFIX}}6,  {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}8,  {{REG_PREFIX}}7,  {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}9,  {{REG_PREFIX}}8,  {{REG_PREFIX}}7
    {{INSN_CHI}},   {{REG_PREFIX}}5,  {{REG_PREFIX}}9,  {{REG_PREFIX}}8
    {{INSN_CHI}},   {{REG_PREFIX}}6,  {{REG_PREFIX}}5,  {{REG_PREFIX}}9
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}5
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}6

    {{INSN_MOV}}    {{REG_PREFIX}}10, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}11, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}12, {{REG_PREFIX}}11, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}13, {{REG_PREFIX}}12, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}14, {{REG_PREFIX}}13, {{REG_PREFIX}}12
    {{INSN_CHI}},   {{REG_PREFIX}}10, {{REG_PREFIX}}14, {{REG_PREFIX}}13
    {{INSN_CHI}},   {{REG_PREFIX}}11, {{REG_PREFIX}}10, {{REG_PREFIX}}14
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}10
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}11

    {{INSN_MOV}}    {{REG_PREFIX}}15, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}16, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}17, {{REG_PREFIX}}16, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}18, {{REG_PREFIX}}17, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}19, {{REG_PREFIX}}18, {{REG_PREFIX}}17
    {{INSN_CHI}},   {{REG_PREFIX}}15, {{REG_PREFIX}}19, {{REG_PREFIX}}18
    {{INSN_CHI}},   {{REG_PREFIX}}16, {{REG_PREFIX}}15, {{REG_PREFIX}}19
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}15
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}16

    {{INSN_MOV}}    {{REG_PREFIX}}20, {{REG_PREFIX}}30
    {{INSN_MOV}}    {{REG_PREFIX}}21, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}22, {{REG_PREFIX}}21, {{REG_PREFIX}}30
    {{INSN_CHI}},   {{REG_PREFIX}}23, {{REG_PREFIX}}22, {{REG_PREFIX}}31
    {{INSN_CHI}},   {{REG_PREFIX}}24, {{REG_PREFIX}}23, {{REG_PREFIX}}22
    {{INSN_CHI}},   {{REG_PREFIX}}20, {{REG_PREFIX}}24, {{REG_PREFIX}}23
    {{INSN_CHI}},   {{REG_PREFIX}}21, {{REG_PREFIX}}20, {{REG_PREFIX}}24
    {{INSN_MOV}}    {{REG_PREFIX}}30, {{REG_PREFIX}}20
    {{INSN_MOV}}    {{REG_PREFIX}}31, {{REG_PREFIX}}21

    /* Loop: advance RC by 2 rounds (16 bytes), decrement */
    addq    $16, %r8
    decl    %ecx
    jnz     .Lround

    ret
.size   .Lpermute_f1600, .-.Lpermute_f1600

{{! ===== Register-resident sponge absorb functions ===== }}

{{#set WORDS_136=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16}}
{{#set WORDS_168=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20}}
{{#set WORDS_72=0|1|2|3|4|5|6|7|8}}

{{#set SPONGE_RATES=136|168|72}}
{{#for SRATE in SPONGE_RATES}}
{{#set SWORDS}}{{SRATE|resolve|WORDS_}}{{/set}}

.globl  dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}
.type   dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}:
    pushq   %rbp
    pushq   %rbx
    pushq   %r12
    pushq   %r13
    pushq   %r14
    movq    %rdi, %rbp
    movq    %rsi, %r12
    movq    %rdx, %r13
    movzbl  %cl,  %r14d
    vpxorq  %xmm0, %xmm0, %xmm0
{{#for i in 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24}}
    vmovdqa64 %ymm0, %ymm{{i}}
{{/for}}
.Labsorb_full_{{SRATE}}:
    cmpq    ${{SRATE}}, %r13
    jb      .Labsorb_pad_{{SRATE}}
{{#for w in SWORDS}}
    vmovq   {{w|math|$*8}}(%r12), {{REG_1X_PREFIX}}30
    vpxorq  {{REG_PREFIX}}30, {{REG_PREFIX}}{{w}}, {{REG_PREFIX}}{{w}}
{{/for}}
    addq    ${{SRATE}}, %r12
    subq    ${{SRATE}}, %r13
    call    .Lpermute_f1600
    jmp     .Labsorb_full_{{SRATE}}
.Labsorb_pad_{{SRATE}}:
    subq    $224, %rsp
    vpxorq  %ymm30, %ymm30, %ymm30
    vmovdqu64 %ymm30, 0(%rsp)
    vmovdqu64 %ymm30, 32(%rsp)
    vmovdqu64 %ymm30, 64(%rsp)
    vmovdqu64 %ymm30, 96(%rsp)
    vmovdqu64 %ymm30, 128(%rsp)
    vmovdqu64 %ymm30, 160(%rsp)
    vmovdqu64 %ymm30, 192(%rsp)
    movq    %r13, %rcx
    leaq    (%rsp), %rdi
    movq    %r12, %rsi
    rep     movsb
    movb    %r14b, (%rsp,%r13)
    xorb    $0x80, {{SRATE|math|$-1}}(%rsp)
{{#for w in SWORDS}}
    vmovq   {{w|math|$*8}}(%rsp), {{REG_1X_PREFIX}}30
    vpxorq  {{REG_PREFIX}}30, {{REG_PREFIX}}{{w}}, {{REG_PREFIX}}{{w}}
{{/for}}
    addq    $224, %rsp
    call    .Lpermute_f1600
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}}, ({{STRIDE_1X}}*{{i}})(%rbp)
{{/for}}
    popq    %r14
    popq    %r13
    popq    %r12
    popq    %rbx
    popq    %rbp
    ret
.size   dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}, .-dap_keccak_absorb_{{SRATE}}_{{FUNC_SUFFIX}}

.globl  dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}
.type   dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}:
    pushq   %rbp
    pushq   %rbx
    pushq   %r12
    movq    %rdi, %rbp
    movq    %rsi, %r12
    movq    %rdx, %rbx
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rbp), {{REG_1X_PREFIX}}{{i}}
{{/for}}
.Lsqueeze_loop_{{SRATE}}:
    testq   %rbx, %rbx
    jz      .Lsqueeze_done_{{SRATE}}
    call    .Lpermute_f1600
{{#for w in SWORDS}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{w}}, {{w|math|$*8}}(%r12)
{{/for}}
    addq    ${{SRATE}}, %r12
    decq    %rbx
    jmp     .Lsqueeze_loop_{{SRATE}}
.Lsqueeze_done_{{SRATE}}:
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}}, ({{STRIDE_1X}}*{{i}})(%rbp)
{{/for}}
    popq    %r12
    popq    %rbx
    popq    %rbp
    ret
.size   dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}, .-dap_keccak_squeeze_{{SRATE}}_{{FUNC_SUFFIX}}

{{/for}}

{{! ===== Round constants ===== }}
.section .rodata
.balign 64
.Lrc:
{{#for rc in RC_LIST}}
    .quad   {{rc}}
{{/for}}

.section .note.GNU-stack,"",@progbits
