
# dap-sdk CMake Configuration
# Generated by PackageComponents.cmake

# Provide legacy FindXXX.cmake compatibility
@PACKAGE_INIT@

# Define library location
set(dap-sdk_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include/dap-sdk")
set(dap-sdk_LIBRARIES dap-sdk)

# Create imported target if not exists
if(NOT TARGET dap-sdk)
    add_library(dap-sdk SHARED IMPORTED)
    set_target_properties(dap-sdk PROPERTIES
        IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../../../lib/libdap-sdk.so"
        INTERFACE_INCLUDE_DIRECTORIES "${dap-sdk_INCLUDE_DIRS}"
    )
endif()

message(STATUS "Found dap-sdk: ${dap-sdk_LIBRARIES}")
