// Auto-generated main include file for all custom mocks
// Generated by dap_mock_autowrap.sh
// Do not modify manually
// No custom mocks found - only includes macros header

#include "{{BASENAME}}_mock_macros.h"

