// Auto-generated mock header for {{FUNC_NAME}}
// Generated by dap_mock_autowrap.sh
// Do not modify manually

#ifndef {{GUARD_NAME}}
#define {{GUARD_NAME}}

// Include necessary headers
#include <stdbool.h>
#include <stdint.h>
#include "dap_common.h"
#include "dap_server.h"
#include "dap_events.h"
#include "dap_config.h"
#include "dap_mock.h"

// External declaration of real function
extern {{RETURN_TYPE}} __real_{{FUNC_NAME}}({{PARAM_DECL}});

// Static declaration of mock implementation
static {{RETURN_TYPE}} __mock_impl_{{FUNC_NAME}}({{PARAM_DECL}});

// Wrapper function
{{WRAPPER_FUNCTION_SIGNATURE}} {
    void **__wrap_args = {{PARAM_ARRAY}};
    int __wrap_args_count = {{PARAM_COUNT}};
{{RESULT_DECLARATION}}
    dap_mock_function_state_t *__wrap_mock_state = dap_mock_find("{{FUNC_NAME}}");
    bool __wrap_mock_enabled = dap_mock_prepare_call(__wrap_mock_state, __wrap_args, __wrap_args_count);
    if (__wrap_mock_enabled) {
{{MOCK_IMPL_CALL}}
{{RETURN_VALUE_OVERRIDE}}
{{RECORD_CALL}}
    } else {
{{REAL_FUNCTION_CALL}}
    }
{{RETURN_STATEMENT}}
}

// Declaration for mock implementation
static {{RETURN_TYPE}} __mock_impl_{{FUNC_NAME}}({{PARAM_DECL}});

#endif // {{GUARD_NAME}}
