// ============================================================================
// MAP_N macro definitions - Generated from PARAM_COUNTS_ARRAY
// ============================================================================
// Each MAP_N macro uses two-level expansion for proper PARAM() preprocessing:
//   Level 1: _DAP_MOCK_MAP_N(macro, ...) forces __VA_ARGS__ expansion
//   Level 2: _DAP_MOCK_MAP_N_IMPL(macro, type1, name1, ...) applies macro()
//
// Generated by dap_mock_autowrap.sh via dap_tpl

{{AWK:}}
BEGIN {
    data = "{{PARAM_COUNTS_ARRAY_PIPE}}"
    n = split(data, counts, "|")
    for (c_idx = 1; c_idx <= n; c_idx++) {
        count = counts[c_idx] + 0

        if (count == 0) {
            printf "#define _DAP_MOCK_MAP_0(macro) \\\n    \n\n"
        } else {
            # Level 1: forces __VA_ARGS__ expansion (PARAM macros expand here)
            printf "#define _DAP_MOCK_MAP_%d(macro, ...) ", count
            printf "_DAP_MOCK_MAP_%d_IMPL(macro, __VA_ARGS__)\n", count

            # Level 2: receives expanded arguments
            printf "#define _DAP_MOCK_MAP_%d_IMPL(macro", count
            for (i = 1; i <= count; i++) {
                printf ", type%d, name%d", i, i
            }
            printf ") \\\n    "
            for (i = 1; i <= count; i++) {
                if (i > 1) printf ", "
                printf "macro(type%d, name%d)", i, i
            }
            printf "\n\n"
        }
    }
}
{{/AWK}}
