/**
 * Auto-generated mock macros for DAP_MOCK_WRAPPER_CUSTOM
 * Generated by dap_mock_autowrap.sh
 * 
 * This file contains only the macros needed for this specific test target.
 * Do not modify manually - it will be regenerated.
 * 
 * This file is included via CMake's -include flag before dap_mock.h
 * No include guards needed - file is included unconditionally via -include
 * 
 * Note: dap_mock_linker_wrapper.h is included via #include in dap_mock.h
 */

// Include standard headers for size_t and other basic types
#include <stddef.h>

// Include base macros we need from dap_mock_linker_wrapper.h
// Since this file is included first, we need the base macros here
#ifndef _DAP_MOCK_NARGS_DEFINED
#define _DAP_MOCK_NARGS_DEFINED

// Dynamically generated _DAP_MOCK_NARGS supporting up to {{MAX_ARGS_COUNT}} arguments
// Full implementation - always uses parameter list (never simplified version)
#define _DAP_MOCK_NARGS_IMPL({{NARGS_IMPL_PARAMS}}, N, ...) N
#define _DAP_MOCK_NARGS(...) _DAP_MOCK_NARGS_IMPL(__VA_ARGS__{{NARGS_SEQUENCE}})

#define _DAP_MOCK_IS_EMPTY(...) \
    (_DAP_MOCK_NARGS(__VA_ARGS__) == 0)
#endif // _DAP_MOCK_NARGS_DEFINED


// ============================================================================
// MAP infrastructure macros (core, routing, counting, conditionals)
// ============================================================================
{{#include "mock_map_macros.h.tpl"}}

// ============================================================================
// MAP_N macro definitions
// ============================================================================
{{#include "mock_map_n.h.tpl"}}

// ============================================================================
// Return type dispatcher macros
// ============================================================================
{{#if RETURN_TYPE_MACROS_FILE}}
{{#include RETURN_TYPE_MACROS_FILE}}
{{/if}}

// ============================================================================
// Simple wrapper macros
// ============================================================================
{{#if SIMPLE_WRAPPER_MACROS_FILE}}
{{#include SIMPLE_WRAPPER_MACROS_FILE}}
{{/if}}

// ============================================================================
// Function-specific wrapper macros
// ============================================================================
{{#if FUNCTION_WRAPPERS_FILE}}
{{#include FUNCTION_WRAPPERS_FILE}}
{{/if}}
