// Auto-generated dyld interposition for macOS
// This file redirects function calls to __wrap_ implementations
// Generated by dap_mock_autowrap using dap_tpl
//
// Dyld interposition is the proper way to intercept function calls on macOS.
// It works at runtime before the program starts, replacing function pointers
// in the dynamic symbol table.
//
// References:
// - Apple TN2123: https://developer.apple.com/library/archive/technotes/tn2123/
// - dyld source: https://opensource.apple.com/source/dyld/

#ifdef __APPLE__
#include <stddef.h>

// Dyld interposition structure
// This structure is placed in __DATA,__interpose section
// and processed by dyld during library load
typedef struct {
    const void* replacement;  // Pointer to replacement function (__wrap_)
    const void* original;     // Pointer to original function
} interpose_t;

{{#if MOCK_FUNCTIONS}}
{{#for func in MOCK_FUNCTIONS|newline}}
// Interpose for {{func}}
// Declare both original and wrapper functions
extern void {{func}}(void);
extern void __wrap_{{func}}(void);

// Register interposition with dyld
// The __attribute__((used)) ensures this symbol is not stripped
// The section directive places it in the special __interpose section
__attribute__((used, section("__DATA,__interpose")))
static const interpose_t interpose_{{func}} = {
    (const void*)&__wrap_{{func}},  // Replacement function
    (const void*)&{{func}}           // Original function
};

{{/for}}
{{else}}
// No functions to interpose
#warning "No mock functions defined for dyld interposition"
{{/if}}

#endif // __APPLE__
