// Auto-generated main include file for all custom mocks
// Generated by dap_mock_autowrap.sh
// Do not modify manually

#include "{{BASENAME}}_mock_macros.h"

{{#if CUSTOM_MOCKS_LIST}}
    {{#for mock_entry in CUSTOM_MOCKS_LIST}}
        {{mock_entry|split|pipe}}
        {{#set func_name={{mock_entry|part|1}}}}
        {{#if func_name}}
            {{#if WRAPPER_FUNCTIONS}}
                {{#if func_name|in_list|WRAPPER_FUNCTIONS}}
                    {{#set should_include=0}}
                {{else}}
                    {{#set should_include=1}}
                {{/if}}
            {{else}}
                {{#set should_include=1}}
            {{/if}}
            {{#if should_include|ne|0}}
#include "custom_mocks/{{func_name}}_mock.h"
            {{/if}}
        {{/if}}
    {{/for}}
{{/if}}
