/**
 * Auto-generated mock macros for DAP_MOCK_WRAPPER_CUSTOM
 * Generated by dap_mock_autowrap.sh
 * 
 * This file contains only the macros needed for this specific test target.
 * Do not modify manually - it will be regenerated.
 * 
 * This file is included via CMake's -include flag before dap_mock_linker_wrapper.h
 * No include guards needed - file is included unconditionally via -include
 */

// Include standard headers for size_t and other basic types
#include <stddef.h>

// Include base macros we need from dap_mock_linker_wrapper.h
// Since this file is included first, we need the base macros here
#ifndef _DAP_MOCK_NARGS_DEFINED
#define _DAP_MOCK_NARGS_DEFINED
// Dynamically generated _DAP_MOCK_NARGS supporting up to {{MAX_ARGS_COUNT}} arguments
{{#if NARGS_SEQUENCE}}
#define _DAP_MOCK_NARGS(...) \
    _DAP_MOCK_NARGS_IMPL(__VA_ARGS__{{NARGS_SEQUENCE}})
{{else}}
#define _DAP_MOCK_NARGS(...) \
    _DAP_MOCK_NARGS_IMPL(__VA_ARGS__, 0)
{{/if}}

{{#if NARGS_IMPL_PARAMS}}
#define _DAP_MOCK_NARGS_IMPL({{NARGS_IMPL_PARAMS}}, N, ...) N
{{else}}
#define _DAP_MOCK_NARGS_IMPL(N, ...) N
{{/if}}

#define _DAP_MOCK_IS_EMPTY(...) \
    (_DAP_MOCK_NARGS(__VA_ARGS__) == 0)
#endif // _DAP_MOCK_NARGS_DEFINED


{{#if MAP_MACROS_DATA}}
    {{#for map_entry in MAP_MACROS_DATA}}
        {{map_entry|split|pipe}}
        {{#set map_count={{map_entry|part|0}}}}
        {{#set map_macro={{map_entry|part|1}}}}
        {{#if map_macro}}
{{map_macro}}
        {{/if}}
    {{/for}}
{{/if}}

{{#if RETURN_TYPE_MACROS_FILE}}
{{#include RETURN_TYPE_MACROS_FILE}}
{{/if}}

{{#if SIMPLE_WRAPPER_MACROS_FILE}}
{{#include SIMPLE_WRAPPER_MACROS_FILE}}
{{/if}}

{{#if MAP_MACROS_CONTENT_FILE}}
{{#include MAP_MACROS_CONTENT_FILE}}
{{/if}}
