#!/bin/bash
# Generate output files (wrap, cmake, macros, templates)

# Source common utilities (but don't initialize yet - that's done in main script)
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${LIB_DIR}/dap_mock_common.sh"

# Generate linker response file with --wrap options (platform-aware)
# macOS: check for ld64.lld (LLVM linker with --wrap support) or use empty file
# Linux/other: uses --wrap=func (GNU ld)
generate_wrap_file() {
    local wrap_file="$1"
    local mock_functions="$2"
    
    > "$wrap_file"  # Clear file
    if [ -n "$mock_functions" ]; then
        local func_count=$(echo "$mock_functions" | wc -l)
        
        # Detect platform using CMAKE_SYSTEM_NAME (passed from CMake)
        # Fallback to OSTYPE if CMAKE_SYSTEM_NAME not set
        local system_name="${CMAKE_SYSTEM_NAME:-${OSTYPE}}"
        
        if [[ "$system_name" == "Darwin"* ]] || [[ "$system_name" == "darwin"* ]]; then
            # macOS: Use ld64 native -alias feature
            # Note: -alias creates both __wrap_ symbols, so we DON'T generate trampolines
            # because they would conflict (duplicate symbols)
            
            echo "$mock_functions" | while read func; do
                # Generate -alias to redirect calls (Mach-O symbols have underscore prefix)
                # Note: For response file (@file), we write raw linker options WITHOUT -Wl, prefix
                # CMake will add -Wl,@file which passes the file content to linker
                echo "-alias _${func} ___wrap_${func}" >> "$wrap_file"
            done
            
            print_success "Generated $func_count -alias options (macOS ld64)"
        else
            # Linux/BSD: Use --wrap=func (GNU ld)
            echo "$mock_functions" | while read func; do
                # Note: For -Wl,@file usage, we need just --wrap=func (without -Wl,)
                echo "--wrap=$func" >> "$wrap_file"
            done
            print_success "Generated $func_count --wrap options (GNU ld)"
        fi
    else
        # Create truly empty file - linker response files cannot contain comments
        > "$wrap_file"
        print_info "Created empty wrap file (no mocks to wrap)"
    fi
}

# Generate CMake integration file
generate_cmake_file() {
    local cmake_file="$1"
    local mock_functions="$2"
    
    cat > "$cmake_file" << EOF
# Auto-generated mock configuration
# Generated by dap_mock_autowrap.sh

# Wrapped functions:
EOF

    if [ -n "$mock_functions" ]; then
        echo "$mock_functions" | while read func; do
            echo "#   - $func" >> "$cmake_file"
        done
    else
        echo "#   (none - no mocks declared)" >> "$cmake_file"
    fi
    
    print_success "Generated CMake integration"
}

# Generate macros header file
# Usage: generate_macros_file <macros_file> [custom_mocks_file]
generate_macros_file() {
    # CRITICAL: Save PARAM_COUNTS_ARRAY to local variable IMMEDIATELY to avoid corruption
    # Global PARAM_COUNTS_ARRAY may be corrupted by template processing functions
    local -a local_param_counts=("${PARAM_COUNTS_ARRAY[@]}")
    
    local macros_file="$1"
    local custom_mocks_file="${2:-${TMP_CUSTOM_MOCKS}}"
    local return_type_macros_file="${macros_file}.return_types"
    local simple_wrapper_macros_file="${macros_file}.simple_wrappers"
    local function_wrappers_file="${macros_file}.function_wrappers"
    
    # Generate return type macros using types module
    source "${LIB_DIR}/dap_mock_types.sh"
    generate_return_type_macros "$return_type_macros_file"
    
    # Generate function-specific wrapper macros (if custom_mocks_file is available)
    if [ -n "$custom_mocks_file" ] && [ -f "$custom_mocks_file" ]; then
        generate_function_wrappers "$function_wrappers_file" "$custom_mocks_file"
    else
        > "$function_wrappers_file"
    fi
    
    # Generate simple wrapper macros (if needed)
    > "$simple_wrapper_macros_file"
    
    # Prepare template data
    prepare_nargs_data "$MAX_ARGS_COUNT"
    prepare_map_count_params_by_count_data "$MAX_ARGS_COUNT"
    prepare_map_count_params_helper_data "$MAX_ARGS_COUNT"
    prepare_map_impl_cond_1_data "$MAX_ARGS_COUNT" "${PARAM_COUNTS_ARRAY[@]}"
    prepare_map_impl_cond_data "${PARAM_COUNTS_ARRAY[@]}"
    # NOTE: prepare_map_macros_data() is NO LONGER USED - we generate macros directly now
    # prepare_map_macros_data "${PARAM_COUNTS_ARRAY[@]}"
    
    # Generate mock_map_macros content with template language constructs
    RETURN_TYPE_MACROS_FILE="$return_type_macros_file" \
    SIMPLE_WRAPPER_MACROS_FILE="$simple_wrapper_macros_file" \
    # Convert PARAM_COUNTS_ARRAY to pipe-separated string for dap_tpl for loop
    # dap_tpl for_evaluator expects pipe-separated or newline-separated arrays
    PARAM_COUNTS_ARRAY_PIPE=$(IFS='|'; echo "${PARAM_COUNTS_ARRAY[*]}")
    
    # NOTE: DO NOT set PARAM_COUNTS_ARRAY in environment here - it will corrupt the global array!
    # The template only needs PARAM_COUNTS_ARRAY_PIPE (passed as argument below)
    MAX_ARGS_COUNT="$MAX_ARGS_COUNT" \
    MAP_COUNT_PARAMS_BY_COUNT_DATA="$MAP_COUNT_PARAMS_BY_COUNT_DATA" \
    MAP_COUNT_PARAMS_HELPER_DATA="$MAP_COUNT_PARAMS_HELPER_DATA" \
    MAP_IMPL_COND_1_DATA="$MAP_IMPL_COND_1_DATA" \
    MAP_IMPL_COND_DATA="$MAP_IMPL_COND_DATA" \
    replace_template_placeholders_with_mocking \
        "${TEMPLATES_DIR}/mock_map_macros.h.tpl" \
        "${macros_file}.map_content" \
        "RETURN_TYPE_MACROS_FILE=$return_type_macros_file" \
        "SIMPLE_WRAPPER_MACROS_FILE=$simple_wrapper_macros_file" \
        "PARAM_COUNTS_ARRAY=$PARAM_COUNTS_ARRAY_PIPE" \
        "MAX_ARGS_COUNT=$MAX_ARGS_COUNT" \
        "MAP_COUNT_PARAMS_BY_COUNT_DATA=$MAP_COUNT_PARAMS_BY_COUNT_DATA" \
        "MAP_COUNT_PARAMS_HELPER_DATA=$MAP_COUNT_PARAMS_HELPER_DATA" \
        "MAP_IMPL_COND_1_DATA=$MAP_IMPL_COND_1_DATA" \
        "MAP_IMPL_COND_DATA=$MAP_IMPL_COND_DATA"
    
    # Export file paths for template processing
    export RETURN_TYPE_MACROS_FILE="$return_type_macros_file"
    export SIMPLE_WRAPPER_MACROS_FILE="$simple_wrapper_macros_file"
    export FUNCTION_WRAPPERS_FILE="$function_wrappers_file"
    export MAP_MACROS_CONTENT_FILE="${macros_file}.map_content"
    
    # Verify files exist before template processing
    if [ ! -f "$RETURN_TYPE_MACROS_FILE" ]; then
        print_error "RETURN_TYPE_MACROS_FILE does not exist: $RETURN_TYPE_MACROS_FILE"
        return 1
    fi
    
    # Save file paths before they might be overwritten in function calls
    local saved_return_type_macros_file="$RETURN_TYPE_MACROS_FILE"
    local saved_simple_wrapper_macros_file="$SIMPLE_WRAPPER_MACROS_FILE"
    
    # DIRECT GENERATION - bypass dap_tpl for huge MAP_MACROS_DATA
    # Generate header manually to avoid passing 805+ lines through AWK (mawk buffer overflow)
    
    # Write file header
    cat > "$macros_file" << 'EOF_HEADER'
/**
 * Auto-generated mock macros for DAP_MOCK_WRAPPER_CUSTOM
 * Generated by dap_mock_autowrap.sh
 * 
 * This file contains only the macros needed for this specific test target.
 * Do not modify manually - it will be regenerated.
 * 
 * This file is included via CMake's -include flag before dap_mock.h
 * No include guards needed - file is included unconditionally via -include
 * 
 * Note: dap_mock_linker_wrapper.h is included via #include in dap_mock.h
 */

// Include standard headers for size_t and other basic types
#include <stddef.h>

// Include base macros we need from dap_mock_linker_wrapper.h
// Since this file is included first, we need the base macros here
#ifndef _DAP_MOCK_NARGS_DEFINED
#define _DAP_MOCK_NARGS_DEFINED

EOF_HEADER

    # Generate NARGS macros
    echo "// Dynamically generated _DAP_MOCK_NARGS supporting up to $MAX_ARGS_COUNT arguments" >> "$macros_file"
    echo "// Full implementation - always uses parameter list (never simplified version)" >> "$macros_file"
    echo "#define _DAP_MOCK_NARGS_IMPL($NARGS_IMPL_PARAMS, N, ...) N" >> "$macros_file"
    echo "#define _DAP_MOCK_NARGS(...) _DAP_MOCK_NARGS_IMPL(__VA_ARGS__$NARGS_SEQUENCE)" >> "$macros_file"
    echo "" >> "$macros_file"
    echo "#define _DAP_MOCK_IS_EMPTY(...) \\" >> "$macros_file"
    echo "    (_DAP_MOCK_NARGS(__VA_ARGS__) == 0)" >> "$macros_file"
    echo "#endif // _DAP_MOCK_NARGS_DEFINED" >> "$macros_file"
    echo "" >> "$macros_file"
    echo "" >> "$macros_file"
    
    # Generate MAP macros directly - NO dap_tpl, NO AWK
    # This is the key fix for mawk buffer overflow (no sprintf limits)
    for count in "${local_param_counts[@]}"; do
        [ -z "$count" ] && continue
        generate_single_map_macro "$count" >> "$macros_file"
        echo "" >> "$macros_file"
    done
    
    # Append return type macros if they exist
    if [ -n "$saved_return_type_macros_file" ] && [ -f "$saved_return_type_macros_file" ] && [ -s "$saved_return_type_macros_file" ]; then
        cat "$saved_return_type_macros_file" >> "$macros_file"
    fi
    
    # Append simple wrapper macros if they exist
    if [ -n "$saved_simple_wrapper_macros_file" ] && [ -f "$saved_simple_wrapper_macros_file" ] && [ -s "$saved_simple_wrapper_macros_file" ]; then
        cat "$saved_simple_wrapper_macros_file" >> "$macros_file"
    fi
    
    # Append function wrappers if they exist
    if [ -n "$function_wrappers_file" ] && [ -f "$function_wrappers_file" ] && [ -s "$function_wrappers_file" ]; then
        cat "$function_wrappers_file" >> "$macros_file"
    fi
    
    # Clean up temporary files AFTER template processing is complete
    # Note: map_content file is included via {{#include}}, so it must exist during template processing
    # It will be cleaned up after the final template is generated
    rm -f "$return_type_macros_file" "$simple_wrapper_macros_file"
    # Keep map_content file for now - it's needed for include processing
    # It will be cleaned up later if needed
    
    print_success "Generated macros header with ${#local_param_counts[@]} parameter count(s)"
    if [ -n "$RETURN_TYPES" ]; then
        local return_types_count=$(echo "$RETURN_TYPES" | wc -w)
        print_success "Generated specialized macros for $return_types_count return type(s): $RETURN_TYPES"
    fi
}

# Generate dap_mock_linker_wrapper.h from template
generate_linker_wrapper_header() {
    local linker_wrapper_file="$1"
    
    # Prepare ORIGINAL_TYPES_DATA as string for template (normalized|original pairs)
    local ORIGINAL_TYPES_DATA=""
    if [ -n "$RETURN_TYPES_PAIRS" ]; then
        ORIGINAL_TYPES_DATA="$RETURN_TYPES_PAIRS"
        # Debug: verify ORIGINAL_TYPES_DATA contains expected types
        [ "$VERBOSE" = "1" ] && echo "DEBUG generate_linker_wrapper_header: RETURN_TYPES_PAIRS=[$RETURN_TYPES_PAIRS]" >&2
        [ "$VERBOSE" = "1" ] && echo "DEBUG generate_linker_wrapper_header: ORIGINAL_TYPES_DATA=[$ORIGINAL_TYPES_DATA]" >&2
    fi
    
    # Generate linker wrapper header from template
    # The template contains only base macros - dispatcher macros are generated separately
    replace_template_placeholders_with_mocking \
        "${TEMPLATES_DIR}/dap_mock_linker_wrapper.h.tpl" \
        "$linker_wrapper_file"
    
    print_success "Generated linker wrapper header"
}

# Generate wrapper template file
generate_template_file() {
    local template_file="$1"
    local mock_functions="$2"
    local wrapper_functions="$3"
    
    if [ -z "$mock_functions" ]; then
        print_info "No mocks declared - skipping template generation"
        return 0
    elif [ -n "$wrapper_functions" ]; then
        local missing_functions=$(comm -23 <(echo "$mock_functions" | sort) <(echo "$wrapper_functions" | sort))
        
        if [ -z "$missing_functions" ]; then
            print_success "All wrappers are defined"
            return 0
        else
            local missing_count=$(echo "$missing_functions" | wc -l)
            print_warning "Missing wrappers for $missing_count functions"
            print_info "Generating template: $template_file"
            
            # Generate template file using main template
            MISSING_FUNCTIONS="$missing_functions" \
            replace_template_placeholders_with_mocking \
                "${TEMPLATES_DIR}/wrapper_template.h.tpl" \
                "$template_file"
            
            # Show missing functions
            echo "$missing_functions" | while read func; do
                [ -z "$func" ] && continue
                echo "   ⚠️  $func"
            done
            
            print_success "Template generated with $missing_count function stubs"
        fi
    else
        # No wrappers found but mocks exist - generate template for all
        local func_count=$(echo "$mock_functions" | wc -l)
        print_warning "No wrappers found for $func_count functions"
        print_info "Generating template: $template_file"
        
        # Generate template file using main template
        MISSING_FUNCTIONS="$mock_functions" \
        replace_template_placeholders_with_mocking \
            "${TEMPLATES_DIR}/wrapper_template.h.tpl" \
            "$template_file"
        
        # Show missing functions
        echo "$mock_functions" | while read func; do
            [ -z "$func" ] && continue
            echo "   ⚠️  $func"
        done
        
        print_success "Template generated with $func_count function stubs"
    fi
}

# Generate custom mock headers for each custom mock declaration
# Usage: generate_custom_mock_headers <output_dir> <basename> <custom_mocks_file> <wrapper_functions>
generate_custom_mock_headers() {
    local output_dir="$1"
    local basename="$2"
    local custom_mocks_file="$3"
    local wrapper_functions="$4"
    local temp_files=()  # Track temporary files for cleanup
    
    if [ ! -f "$custom_mocks_file" ] || [ ! -s "$custom_mocks_file" ]; then
        print_info "No custom mocks found - creating custom mocks header with macros only"
        local main_custom_mocks_file="${output_dir}/${basename}_custom_mocks.h"
        
        # Generate empty main include file manually (no template needed)
        cat > "$main_custom_mocks_file" <<EOF
// Auto-generated main include file for all custom mocks
// Generated by dap_mock_autowrap.sh
// Do not modify manually

#include "${basename}_mock_macros.h"

// No custom mocks found - only includes macros header

EOF
        return 0
    fi
    
    local custom_mocks_count=$(wc -l < "$custom_mocks_file" | tr -d ' ')
    
    # Create directory for custom mock headers
    local custom_mocks_dir="${output_dir}/custom_mocks"
    mkdir -p "$custom_mocks_dir"
    
    # Process each custom mock declaration
    while IFS='|' read -r return_type func_name param_list macro_type; do
        [ -z "$func_name" ] && continue
        
        # Skip if function already has a wrapper defined in source files
        if echo "$wrapper_functions" | grep -q "^${func_name}$"; then
            continue
        fi
        
        # Create header file name based on function name
        local header_file="${custom_mocks_dir}/${func_name}_mock.h"
        
        # Parse parameters from param_list
        local param_decl=""
        local param_names=""
        local param_array=""
        local param_count=0
        
        if [ "$param_list" = "void" ] || [ -z "$param_list" ]; then
            param_decl="void"
            param_names=""
            param_array="NULL"
            param_count=0
        else
            # AWK script already processed PARAM(...) into "type name, type2 name2" format
            # Split by comma to get individual parameters
            local param_decl_parts=()
            local param_name_parts=()
            local param_array_parts=()
            
            # Split param_list by commas
            IFS=',' read -ra PARAMS <<< "$param_list"
            for param in "${PARAMS[@]}"; do
                # Trim whitespace
                param=$(echo "$param" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                [ -z "$param" ] && continue
                
                # Extract last word as parameter name
                local param_name=$(echo "$param" | awk '{print $NF}')
                
                param_decl_parts+=("$param")
                param_name_parts+=("$param_name")
                param_array_parts+=("(void*)(intptr_t)$param_name")
            done
            
            # Join parameters with proper formatting
            if [ ${#param_decl_parts[@]} -gt 0 ]; then
                param_decl=$(IFS=', '; echo "${param_decl_parts[*]}")
                param_names=$(IFS=', '; echo "${param_name_parts[*]}")
                param_array="((void*[]){$(IFS=', '; echo "${param_array_parts[*]}")})"
                param_count=${#param_decl_parts[@]}
            else
                param_decl="void"
                param_names=""
                param_array="NULL"
                param_count=0
            fi
        fi
        
        # Prepare template variables
        local guard_name="${func_name^^}_MOCK_H"
        local wrapper_signature=""
        local result_declaration=""
        local mock_impl_call=""
        local real_function_call=""
        local return_value_override=""
        local record_call=""
        local return_statement=""
        local return_value_override_file=""
        local record_call_file=""
        
        if [ "$return_type" = "void" ]; then
            wrapper_signature="void __wrap_${func_name}($param_decl)"
            result_declaration=""
            if [ "$param_count" -eq 0 ]; then
                mock_impl_call="        __mock_impl_${func_name}();"
                real_function_call="        __real_${func_name}();"
            else
                mock_impl_call="        __mock_impl_${func_name}($param_names);"
                real_function_call="        __real_${func_name}($param_names);"
            fi
            return_value_override=""
            record_call=""
            return_statement=""
        else
            wrapper_signature="$return_type __wrap_${func_name}($param_decl)"
            result_declaration="    $return_type __wrap_result = ($return_type){0};"
            if [ "$param_count" -eq 0 ]; then
                mock_impl_call="        __wrap_result = __mock_impl_${func_name}();"
                real_function_call="        __wrap_result = __real_${func_name}();"
            else
                mock_impl_call="        __wrap_result = __mock_impl_${func_name}($param_names);"
                real_function_call="        __wrap_result = __real_${func_name}($param_names);"
            fi
            # Create temporary files for multi-line values
            return_value_override_file=$(create_temp_file "return_value_override_${func_name}")
            record_call_file=$(create_temp_file "record_call_${func_name}")
            temp_files+=("$return_value_override_file" "$record_call_file")
            {
                echo "        if (__wrap_mock_state && __wrap_mock_state->return_value.ptr) {"
                echo "            __wrap_result = *($return_type*)__wrap_mock_state->return_value.ptr;"
                echo "        }"
            } > "$return_value_override_file"
            echo "        dap_mock_record_call(__wrap_mock_state, __wrap_args, __wrap_args_count, (void*)(intptr_t)__wrap_result);" > "$record_call_file"
            return_value_override="@$return_value_override_file"
            record_call="@$record_call_file"
            return_statement="    return __wrap_result;"
        fi
        
        # Generate header file using template
        replace_template_placeholders_with_mocking \
            "${TEMPLATES_DIR}/custom_mock_header.h.tpl" \
            "$header_file" \
            "FUNC_NAME=$func_name" \
            "RETURN_TYPE=$return_type" \
            "PARAM_DECL=$param_decl" \
            "PARAM_NAMES=$param_names" \
            "PARAM_ARRAY=$param_array" \
            "PARAM_COUNT=$param_count" \
            "GUARD_NAME=$guard_name" \
            "WRAPPER_FUNCTION_SIGNATURE=$wrapper_signature" \
            "RESULT_DECLARATION=$result_declaration" \
            "MOCK_IMPL_CALL=$mock_impl_call" \
            "RETURN_VALUE_OVERRIDE=$return_value_override" \
            "RECORD_CALL=$record_call" \
            "REAL_FUNCTION_CALL=$real_function_call" \
            "RETURN_STATEMENT=$return_statement" \
            "ADDITIONAL_INCLUDES=${DAP_MOCK_ADDITIONAL_INCLUDES:-}"
        
        print_success "Generated mock header: $header_file"
    done < "$custom_mocks_file"
    
    # Clean up temporary files
    cleanup_temp_files "${temp_files[@]}"
    
    # Create main include file that includes all custom mock headers
    local main_custom_mocks_file="${output_dir}/${basename}_custom_mocks.h"
    
    # Generate main include file directly (template has issues with complex data)
    {
        echo "// Auto-generated main include file for all custom mocks"
        echo "// Generated by dap_mock_autowrap.sh"
        echo "// Do not modify manually"
        echo ""
        echo "#include \"${basename}_mock_macros.h\""
        echo ""
        
        # Include each custom mock header (unless already has wrapper)
        while IFS='|' read -r return_type func_name param_list macro_type; do
            [ -z "$func_name" ] && continue
            
            # Skip if function already has a wrapper defined in source files
            if echo "$wrapper_functions" | grep -q "^${func_name}$"; then
                continue
            fi
            
            echo "#include \"custom_mocks/${func_name}_mock.h\""
        done < "$custom_mocks_file"
        
        echo ""
    } > "$main_custom_mocks_file"
    
    print_success "Generated main custom mocks include: $main_custom_mocks_file"
}

# Prepare MAP_IMPL_COND_1_DATA for template generation
# Format: arg_count|param_count|has_count|fallback_count|macro_params
# macro_params should NOT include "macro" - it's already in the macro parameter list
prepare_map_impl_cond_1_data() {
    local max_args_count="$1"
    shift
    local param_counts_array=("$@")
    
    [ -z "$max_args_count" ] && max_args_count=0
    [ "$max_args_count" -lt 0 ] && max_args_count=0
    
    declare -A HAS_PARAM_COUNT
    for count in "${param_counts_array[@]}"; do
        [ -z "$count" ] && continue
        HAS_PARAM_COUNT["$count"]=1
    done
    
    MAP_IMPL_COND_1_DATA=""
    for arg_count in $(seq 1 "$max_args_count"); do
        param_count=$((arg_count / 2))
        
        # Build macro_params starting with p1 (NOT macro - macro is already in parameter list)
        macro_params="p1"
        for j in $(seq 2 "$arg_count"); do
            macro_params="${macro_params}, p${j}"
        done
        
        has_count=0
        if [ "${HAS_PARAM_COUNT[$param_count]:-0}" = "1" ] || [ "$param_count" -eq 0 ]; then
            has_count=1
            fallback_count="$param_count"
        else
            fallback_count=0
            for count in "${param_counts_array[@]}"; do
                [ -z "$count" ] && continue
                if [ "$count" -le "$param_count" ] && [ "$count" -gt "$fallback_count" ]; then
                    fallback_count="$count"
                fi
            done
        fi
        
        if [ -n "$MAP_IMPL_COND_1_DATA" ]; then
            MAP_IMPL_COND_1_DATA="${MAP_IMPL_COND_1_DATA}"$'\n'"${arg_count}|${param_count}|${has_count}|${fallback_count}|${macro_params}"
        else
            MAP_IMPL_COND_1_DATA="${arg_count}|${param_count}|${has_count}|${fallback_count}|${macro_params}"
        fi
    done
}

# Prepare MAP_IMPL_COND_DATA for template generation
prepare_map_impl_cond_data() {
    local param_counts_array=("$@")
    MAP_IMPL_COND_DATA=""
    for count in "${param_counts_array[@]}"; do
        [ -z "$count" ] && continue
        if [ -n "$MAP_IMPL_COND_DATA" ]; then
            MAP_IMPL_COND_DATA="${MAP_IMPL_COND_DATA}"$'\n'"${count}"
        else
            MAP_IMPL_COND_DATA="${count}"
        fi
    done
}

# Generate single MAP macro definition using pure bash (no AWK)
# Avoids mawk sprintf buffer limit (8KB) for large parameter counts
# Usage: generate_single_map_macro COUNT
# Output: #define _DAP_MOCK_MAP_N(macro, ...) macro(type1, name1), macro(type2, name2), ...
generate_single_map_macro() {
    local count="$1"
    
    # Start macro definition
    echo -n "#define _DAP_MOCK_MAP_${count}(macro"
    
    # Generate parameter list: , type1, name1, type2, name2, ...
    for ((i=1; i<=count; i++)); do
        echo -n ", type${i}, name${i}"
    done
    
    # Start macro body
    echo -n ") \\"
    echo ""
    echo -n "    "
    
    if [ "$count" -eq 0 ]; then
        echo ""
    else
        # Generate macro invocations: macro(type1, name1), macro(type2, name2), ...
        for ((i=1; i<=count; i++)); do
            if [ "$i" -gt 1 ]; then
                echo -n ", "
            fi
            echo -n "macro(type${i}, name${i})"
        done
        echo ""
    fi
}

# Prepare MAP_MACROS_DATA for template generation
# Uses pure bash generation to avoid mawk sprintf buffer overflow (8KB limit)
# NOTE: This function is DEPRECATED - macros are now generated directly in generate_macros_file()
# Kept for backward compatibility but does NOT produce pipe-separated data
prepare_map_macros_data() {
    local param_counts_array=("$@")
    
    # Do nothing - direct generation is used now
    # This function is kept to avoid breaking old code that might call it
    MAP_MACROS_DATA=""
}

# Prepare NARGS data for template generation
# Generates data for _DAP_MOCK_NARGS macro generation
# Usage: prepare_nargs_data MAX_ARGS_COUNT
# Output: Sets NARGS_SEQUENCE and NARGS_IMPL_PARAMS variables
# Always generates full implementation (never simplified version)
prepare_nargs_data() {
    local max_args_count="$1"
    [ -z "$max_args_count" ] && max_args_count=0
    [ "$max_args_count" -lt 0 ] && max_args_count=0
    
    # Always ensure minimum of 2 args for full implementation
    # This ensures we always have a proper _DAP_MOCK_NARGS_IMPL definition
    # Minimum needed: _1, _2 for proper macro expansion
    local effective_max_args=$max_args_count
    [ "$effective_max_args" -lt 2 ] && effective_max_args=2
    
    # Prepare NARGS_SEQUENCE (always includes at least 2, 1, 0)
    NARGS_SEQUENCE=""
    for i in $(seq $effective_max_args -1 0); do
        if [ -n "$NARGS_SEQUENCE" ]; then
            NARGS_SEQUENCE="${NARGS_SEQUENCE}, $i"
        else
            NARGS_SEQUENCE=", $i"
        fi
    done
    
    # Prepare NARGS_IMPL_PARAMS (always includes at least _1, _2)
    # Format: single line with comma-separated parameters: _1, _2, _3, ...
    NARGS_IMPL_PARAMS=""
    for i in $(seq 1 $effective_max_args); do
        if [ -n "$NARGS_IMPL_PARAMS" ]; then
            NARGS_IMPL_PARAMS="${NARGS_IMPL_PARAMS}, _$i"
        else
            NARGS_IMPL_PARAMS="_$i"
        fi
    done
}

# Prepare MAP_COUNT_PARAMS_BY_COUNT_DATA for template generation
prepare_map_count_params_by_count_data() {
    local max_args_count="$1"
    [ -z "$max_args_count" ] && max_args_count=2
    [ "$max_args_count" -lt 2 ] && max_args_count=2
    
    MAP_COUNT_PARAMS_BY_COUNT_DATA=""
    for arg_count in $(seq 0 "$max_args_count"); do
        if [ -n "$MAP_COUNT_PARAMS_BY_COUNT_DATA" ]; then
            MAP_COUNT_PARAMS_BY_COUNT_DATA="${MAP_COUNT_PARAMS_BY_COUNT_DATA}"$'\n'"${arg_count}"
        else
            MAP_COUNT_PARAMS_BY_COUNT_DATA="${arg_count}"
        fi
    done
}

# Prepare MAP_COUNT_PARAMS_HELPER_DATA for template generation
# Format: arg_count|param_count
prepare_map_count_params_helper_data() {
    local max_args_count="$1"
    [ -z "$max_args_count" ] && max_args_count=2
    [ "$max_args_count" -lt 2 ] && max_args_count=2
    
    MAP_COUNT_PARAMS_HELPER_DATA=""
    for arg_count in $(seq 0 "$max_args_count"); do
        param_count=$((arg_count / 2))
        if [ -n "$MAP_COUNT_PARAMS_HELPER_DATA" ]; then
            MAP_COUNT_PARAMS_HELPER_DATA="${MAP_COUNT_PARAMS_HELPER_DATA}"$'\n'"${arg_count}|${param_count}"
        else
            MAP_COUNT_PARAMS_HELPER_DATA="${arg_count}|${param_count}"
        fi
    done
}
