#!/bin/bash
# Parse DAP_MOCK_WRAPPER_CUSTOM declarations and extract type information

# Source common utilities (but don't initialize yet - that's done in main script)
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${LIB_DIR}/dap_mock_common.sh"

# Parse source files and extract parameter counts, return types, and all types
# Sets global variables: PARAM_COUNTS_ARRAY, RETURN_TYPES, RETURN_TYPES_PAIRS, ALL_TYPES_PAIRS, ORIGINAL_TYPES
parse_mock_declarations() {
    local source_files=("$@")
    
    local tmp_param_counts=$(create_temp_file "param_counts")
    local tmp_return_types=$(create_temp_file "return_types")
    local tmp_all_types=$(create_temp_file "all_types")
    
    > "$tmp_param_counts"
    > "$tmp_return_types"
    > "$tmp_all_types"
    
    # Filter existing files
    local existing_files=()
    for source_file in "${source_files[@]}"; do
        [ -f "$source_file" ] && existing_files+=("$source_file")
    done
    
    if [ ${#existing_files[@]} -eq 0 ]; then
        PARAM_COUNTS_ARRAY=()
        RETURN_TYPES_PAIRS=""
        ALL_TYPES_PAIRS=""
        ORIGINAL_TYPES=""
        return 0
    fi
    
    # Optimized: single gawk invocation per script for all files (much faster than per-file)
    # Use awk to parse DAP_MOCK_WRAPPER_CUSTOM declarations (and variants)
    # Extract return_type and count PARAM(...) entries between macro and opening brace {
    # Handle multi-line declarations
    gawk -f "${MOCK_AWK_DIR}/count_params.awk" "${existing_files[@]}" > "$tmp_param_counts" 2>/dev/null || true
    
    # Second pass: extract return types (both normalized and original)
    gawk -f "${MOCK_AWK_DIR}/extract_return_types.awk" "${existing_files[@]}" > "$tmp_return_types" 2>/dev/null || true
    
    # Third pass: extract all types (return types + parameter types from PARAM(...))
    gawk -f "${MOCK_AWK_DIR}/extract_all_types.awk" "${existing_files[@]}" > "$tmp_all_types" 2>/dev/null || true
    
    # Process all mock data using single awk script
    # The awk script outputs shell-compatible code that sets all environment variables
    local mock_data_code
    mock_data_code=$(gawk -f "${MOCK_AWK_DIR}/process_mock_data.awk" "$tmp_param_counts" "$tmp_return_types" "$tmp_all_types" 2>/dev/null || cat <<'EOF'
declare -ga PARAM_COUNTS_ARRAY=(0)
declare -gi MAX_ARGS_COUNT=2
RETURN_TYPES=''
RETURN_TYPES_PAIRS=$''
ALL_TYPES_PAIRS=$''
declare -gA ORIGINAL_TYPES
export PARAM_COUNTS_ARRAY
export MAX_ARGS_COUNT
export RETURN_TYPES
export RETURN_TYPES_PAIRS
export ALL_TYPES_PAIRS
export ORIGINAL_TYPES
EOF
    )
    
    # Clean up temporary files
    rm -f "$tmp_param_counts" "$tmp_return_types" "$tmp_all_types"
    
    # Execute the shell code generated by awk script
    # This sets all variables: PARAM_COUNTS_ARRAY, MAX_ARGS_COUNT, RETURN_TYPES,
    # RETURN_TYPES_PAIRS, ALL_TYPES_PAIRS, ORIGINAL_TYPES
    eval "$mock_data_code"
    
    # Ensure minimum values for safety
    if [ ${#PARAM_COUNTS_ARRAY[@]} -eq 0 ] || [ -z "${PARAM_COUNTS_ARRAY[0]}" ]; then
        declare -ga PARAM_COUNTS_ARRAY=(0)
    fi
    [ "$MAX_ARGS_COUNT" -lt 2 ] && declare -gi MAX_ARGS_COUNT=2
    
    print_success "Found parameter counts: ${PARAM_COUNTS_ARRAY[*]}"
}

