/*
 * Authors:
 * Dmitriy A. Gerasimov <gerasimov.dmitriy@demlabs.net>
 * DeM Labs Inc.   https://demlabs.net
 * Copyright  (c) 2026
 * All rights reserved.
 *
 This file is part of DAP (Distributed Applications Platform) the open source project

    DAP (Distributed Applications Platform) is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    DAP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with any DAP based project.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file dap_json_stage1_sse2.c
 * @brief SimdJSON-style Stage 1 tokenization with SSE2 SIMD optimization
 * @details Auto-generated from template using dap_tpl
 * 
 * Performance target: 1+ GB/s (single-core)
 * 
 * @date 2026-01-11
 * @generated
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <emmintrin.h>  // SSE2

#include "dap_common.h"
#include "dap_json.h"
#include "internal/dap_json_stage1.h"
#include "internal/dap_json_stage1_ref.h"

#define LOG_TAG "dap_json_stage1_sse2"

/* ========================================================================== */
/*                    SSE2-SPECIFIC CONFIGURATION                    */
/* ========================================================================== */

// Vector length: runtime for SVE/SVE2, compile-time for others
// Generated by dap_tpl from CHUNK_SIZE_MACRO parameter
#define CHUNK_SIZE_VALUE ((size_t)16)

#define VECTOR_TYPE __m128i
#define MASK_TYPE uint16_t





// ============================================================================
// Non-SVE SIMD (SSE2, AVX2, AVX-512, NEON): Direct vector operations
// ============================================================================

// Unified SIMD operation macros for non-SVE
#define SIMD_LOAD(ptr)           _mm_loadu_si128((const VECTOR_TYPE *)(ptr))
#define SIMD_SET1(val)           _mm_set1_epi8((val))
#define SIMD_CMP_EQ(a, b)        _mm_cmpeq_epi8((a), (b))


// For AVX-512, comparisons return __mmask64, not vector

// For SSE2/AVX2/NEON, comparison returns vector with 0xFF/-1 for matches
#define COMPARISON_RESULT_TYPE   VECTOR_TYPE




/**
 * @brief Bitmap masks for character classification
 */
typedef struct {
    MASK_TYPE structural;   /* { } [ ] : , */
    MASK_TYPE whitespace;   /* space, tab, \r, \n */
    MASK_TYPE quote;        /* " */
    MASK_TYPE backslash;    /* \ */
} dap_json_bitmaps_sse2_t;

/* ========================================================================== */
/*                    SIMD PRIMITIVES - SSE2                         */
/* ========================================================================== */

/**
 * @brief SIMD: Classify chunk into bitmaps
 */

static dap_json_bitmaps_sse2_t s_classify_chunk_sse2(const uint8_t *a_chunk)
{
    dap_json_bitmaps_sse2_t bitmaps = {0};
    
  // ARCH_LOWER == "sve" || == "sve2"

    // ========================================================================
    // Non-SVE: Vector-based comparisons (SSE2, AVX2, AVX-512, NEON)
    // ========================================================================
    
    // Load chunk
    VECTOR_TYPE chunk = _mm_loadu_si128((const VECTOR_TYPE *)a_chunk);
    
    // Create comparison vectors
    VECTOR_TYPE v_space = _mm_set1_epi8(' ');
    VECTOR_TYPE v_tab = _mm_set1_epi8('\t');
    VECTOR_TYPE v_cr = _mm_set1_epi8('\r');
    VECTOR_TYPE v_lf = _mm_set1_epi8('\n');
    VECTOR_TYPE v_quote = _mm_set1_epi8('"');
    VECTOR_TYPE v_backslash = _mm_set1_epi8('\\');
    VECTOR_TYPE v_op_brace = _mm_set1_epi8('{');
    VECTOR_TYPE v_cl_brace = _mm_set1_epi8('}');
    VECTOR_TYPE v_op_bracket = _mm_set1_epi8('[');
    VECTOR_TYPE v_cl_bracket = _mm_set1_epi8(']');
    VECTOR_TYPE v_colon = _mm_set1_epi8(':');
    VECTOR_TYPE v_comma = _mm_set1_epi8(',');
    

    // SSE2/AVX2/NEON: Vector comparisons + movemask
    VECTOR_TYPE whitespace = _mm_or_si128(
        _mm_or_si128(_mm_cmpeq_epi8(chunk, v_space), _mm_cmpeq_epi8(chunk, v_tab)),
        _mm_or_si128(_mm_cmpeq_epi8(chunk, v_cr), _mm_cmpeq_epi8(chunk, v_lf))
    );
    
    VECTOR_TYPE quote = _mm_cmpeq_epi8(chunk, v_quote);
    VECTOR_TYPE backslash = _mm_cmpeq_epi8(chunk, v_backslash);
    
    VECTOR_TYPE structural = _mm_or_si128(
        _mm_or_si128(
            _mm_or_si128(_mm_cmpeq_epi8(chunk, v_op_brace), _mm_cmpeq_epi8(chunk, v_cl_brace)),
            _mm_or_si128(_mm_cmpeq_epi8(chunk, v_op_bracket), _mm_cmpeq_epi8(chunk, v_cl_bracket))
        ),
        _mm_or_si128(_mm_cmpeq_epi8(chunk, v_colon), _mm_cmpeq_epi8(chunk, v_comma))
    );
    
    // Convert to bitmasks
    bitmaps.whitespace = (MASK_TYPE)_mm_movemask_epi8(whitespace);
    bitmaps.quote = (MASK_TYPE)_mm_movemask_epi8(quote);
    bitmaps.backslash = (MASK_TYPE)_mm_movemask_epi8(backslash);
    bitmaps.structural = (MASK_TYPE)_mm_movemask_epi8(structural);
  // USE_AVX512_MASK
  // ARCH_LOWER != "sve" && != "sve2"
    
    return bitmaps;
}

/* ========================================================================== */
/*                    SIMD STRING SCANNING - SSE2                    */
/* ========================================================================== */

/**
 * @brief SIMD-optimized string scanner (CRITICAL HOTSPOT - 27.6% CPU → ~5-8%)
 * @details Fast-path для strings без escapes (99% случаев):
 *          - Параллельный поиск closing quote через SIMD
 *          - Zero overhead для simple strings
 *          - Fallback to scalar для escape sequences
 * 
 * Algorithm:
 *   1. SIMD scan: найти quote OR backslash в чанках (16/32/64 bytes/iter)
 *   2. Fast path: quote найдена раньше backslash → return immediately
 *   3. Slow path: backslash найдена → fallback к reference scanner
 * 
 * Performance gain: 3-5x vs scalar
 * Expected impact: 27.6% CPU → ~5-8% (overall +20-25% throughput)
 */

static size_t s_scan_string_fast_sse2(
    dap_json_stage1_t *a_stage1,
    size_t a_start_pos
)
{
    const uint8_t *l_input = a_stage1->input;
    const size_t l_len = a_stage1->input_len;
    size_t l_pos = a_start_pos + 1;  // Skip opening quote
    
    const size_t chunk_size = CHUNK_SIZE_VALUE;
    

    // ========================================================================
    // x86 (SSE2/AVX2/AVX-512) & ARM NEON: Vector-based scanning
    // Fixed vector length: 16/32/64 bytes per iteration
    // ========================================================================
    VECTOR_TYPE v_quote = SIMD_SET1('"');
    VECTOR_TYPE v_backslash = SIMD_SET1('\\');
    
    // SIMD scan: parallel search for quote OR backslash
    while (l_pos + chunk_size <= l_len) {
        VECTOR_TYPE chunk = SIMD_LOAD(l_input + l_pos);
        
        // Find quote OR backslash (vector-based)
        COMPARISON_RESULT_TYPE has_quote = SIMD_CMP_EQ(chunk, v_quote);
        COMPARISON_RESULT_TYPE has_backslash = SIMD_CMP_EQ(chunk, v_backslash);
        
        // Convert to bitmasks for analysis

        // SSE2/AVX2/NEON: convert vectors to bitmasks
        MASK_TYPE quote_mask = (MASK_TYPE)_mm_movemask_epi8(has_quote);
        MASK_TYPE backslash_mask = (MASK_TYPE)_mm_movemask_epi8(has_backslash);

        
        // Fast path: quote found, no escapes before it
        // Use CTZ (Count Trailing Zeros) to find first set bit
        if (quote_mask) {
            int quote_offset = __builtin_ctzll(quote_mask);
            if (!backslash_mask || __builtin_ctzll(backslash_mask) > quote_offset) {
                return l_pos + quote_offset + 1;  // After closing quote
            }
        }
        
        // Escape found - fallback to scalar
        if (backslash_mask) {
            goto slow_path;
        }
        
        l_pos += chunk_size;
    }

    
slow_path:
    // ========================================================================
    // Slow path: Escape sequences detected OR tail bytes
    // Fallback to reference scanner (handles \uXXXX, validation, etc)
    // Performance: ~1% of strings hit this path
    // ========================================================================
    return dap_json_stage1_scan_string_ref(a_stage1, a_start_pos);
}


/**
 * @brief Helper: Add token with capacity check (inline for speed)
 */
static inline int s_add_token_sse2(
    dap_json_stage1_t *a_stage1, uint32_t a_pos, uint32_t a_len,
    dap_json_token_type_t a_type, uint8_t a_char)
{
    // Ensure capacity
    if (__builtin_expect(a_stage1->indices_count >= a_stage1->indices_capacity, 0)) {
        size_t new_capacity = a_stage1->indices_capacity * 2;
        dap_json_struct_index_t *new_indices = DAP_NEW_SIZE(dap_json_struct_index_t,
                                                             new_capacity * sizeof(dap_json_struct_index_t));
        if (!new_indices) {
            return STAGE1_ERROR_OUT_OF_MEMORY;
        }
        memcpy(new_indices, a_stage1->indices,
               a_stage1->indices_count * sizeof(dap_json_struct_index_t));
        DAP_DELETE(a_stage1->indices);
        a_stage1->indices = new_indices;
        a_stage1->indices_capacity = new_capacity;
    }
    
    // Add token
    a_stage1->indices[a_stage1->indices_count].position = a_pos;
    a_stage1->indices[a_stage1->indices_count].length = a_len;
    a_stage1->indices[a_stage1->indices_count].type = a_type;
    a_stage1->indices[a_stage1->indices_count].character = a_char;
    a_stage1->indices_count++;
    
    return STAGE1_SUCCESS;
}

/* ========================================================================== */
/*                    MAIN TOKENIZATION - SSE2                       */
/* ========================================================================== */

/**
 * @brief Full SIMD-optimized Stage 1 tokenization (SSE2)
 * @details Three-phase processing:
 *          Phase 1: SIMD chunk classification + structural extraction
 *          Phase 2: Sequential value token extraction (with SIMD hints)
 *          Phase 3: Tail processing
 * 
 * Performance: 1+ GB/s (single-core)
 */

int dap_json_stage1_run_sse2(dap_json_stage1_t *a_stage1)
{
    if (!a_stage1 || !a_stage1->input) {
        return STAGE1_ERROR_INVALID_INPUT;
    }
    
    const uint8_t *input = a_stage1->input;
    const size_t input_len = a_stage1->input_len;
    
    // Reset state
    a_stage1->indices_count = 0;
    a_stage1->current_pos = 0;
    a_stage1->in_string = false;
    a_stage1->escape_next = false;
    a_stage1->string_count = 0;
    a_stage1->number_count = 0;
    a_stage1->literal_count = 0;
    a_stage1->string_chars = 0;
    a_stage1->whitespace_chars = 0;
    a_stage1->structural_chars = 0;
    a_stage1->error_code = STAGE1_SUCCESS;
    a_stage1->error_position = 0;
    a_stage1->error_message[0] = '\0';
    
    debug_if(dap_json_get_debug(), "Starting SSE2 SimdJSON Stage 1 tokenization (%zu bytes)", input_len);
    
    // Phase 1 & 2: SIMD-accelerated chunk processing
    size_t pos = 0;
    const size_t chunk_size = CHUNK_SIZE_VALUE;  // Cache for performance (const in loop)
    const size_t chunk_end = (input_len / chunk_size) * chunk_size;
    
    while (pos < chunk_end) {
        // SIMD: Classify chunk in parallel
        dap_json_bitmaps_sse2_t bitmaps = s_classify_chunk_sse2(input + pos);
        
        // Process chunk sequentially in position order, using bitmaps as hints
        size_t chunk_pos = pos;
        size_t chunk_limit = pos + chunk_size;
        
        // CRITICAL: Clamp chunk_limit to input_len to avoid reading beyond buffer
        if (chunk_limit > input_len) {
            chunk_limit = input_len;
        }
        
        while (chunk_pos < chunk_limit) {
            uint8_t c = input[chunk_pos];
            size_t bit_offset = chunk_pos - pos;
            
            // Fast path: Check bitmap for whitespace (skip without token)
            if (bit_offset < chunk_size && (bitmaps.whitespace & (((MASK_TYPE)1) << bit_offset))) {
                chunk_pos++;
                continue;
            }
            
            // Fast path: Check bitmap for structural (add token immediately)
            if (bit_offset < chunk_size && (bitmaps.structural & (((MASK_TYPE)1) << bit_offset))) {
                int ret = s_add_token_sse2(a_stage1, (uint32_t)chunk_pos, 0, TOKEN_TYPE_STRUCTURAL, c);
                if (ret != STAGE1_SUCCESS) return ret;
                a_stage1->structural_chars++;
                chunk_pos++;
                continue;
            }
            
            // Slow path: Skip whitespace (not in chunk or missed by bitmap)
            if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
                a_stage1->whitespace_chars++;
                chunk_pos++;
                continue;
            }
            
            // String (can span beyond chunk)
            if (c == '"') {
                size_t end = s_scan_string_fast_sse2(a_stage1, chunk_pos);
                if (end == chunk_pos) return a_stage1->error_code;
                
                size_t str_len = end - chunk_pos;
                int ret = s_add_token_sse2(a_stage1, (uint32_t)chunk_pos, (uint32_t)str_len,
                                     TOKEN_TYPE_STRING, 0);
                if (ret != STAGE1_SUCCESS) return ret;
                
                a_stage1->string_count++;
                a_stage1->string_chars += str_len;
                
                // Handle spanning
                if (end >= chunk_limit) {
                    pos = end;
                    chunk_pos = chunk_limit;
                } else {
                    chunk_pos = end;
                }
                continue;
            }
            
            // Number (can span beyond chunk)
            if (c == '-' || (c >= '0' && c <= '9')) {
                size_t end = dap_json_stage1_scan_number_ref(a_stage1, chunk_pos);
                if (end == chunk_pos) return a_stage1->error_code;
                
                size_t num_len = end - chunk_pos;
                int ret = s_add_token_sse2(a_stage1, (uint32_t)chunk_pos, (uint32_t)num_len,
                                     TOKEN_TYPE_NUMBER, 0);
                if (ret != STAGE1_SUCCESS) return ret;
                
                a_stage1->number_count++;
                
                if (end >= chunk_limit) {
                    pos = end;
                    chunk_pos = chunk_limit;
                } else {
                    chunk_pos = end;
                }
                continue;
            }
            
            // Literal (can span beyond chunk)
            if (c == 't' || c == 'f' || c == 'n') {
                size_t end = dap_json_stage1_scan_literal_ref(a_stage1, chunk_pos);
                if (end == chunk_pos) return a_stage1->error_code;
                
                // Determine literal type from first character
                uint8_t lit_type = DAP_JSON_LITERAL_UNKNOWN;
                if (c == 't') lit_type = DAP_JSON_LITERAL_TRUE;
                else if (c == 'f') lit_type = DAP_JSON_LITERAL_FALSE;
                else if (c == 'n') lit_type = DAP_JSON_LITERAL_NULL;
                
                size_t lit_len = end - chunk_pos;
                int ret = s_add_token_sse2(a_stage1, (uint32_t)chunk_pos, (uint32_t)lit_len,
                                     TOKEN_TYPE_LITERAL, lit_type);
                if (ret != STAGE1_SUCCESS) return ret;
                
                a_stage1->literal_count++;
                
                if (end >= chunk_limit) {
                    pos = end;
                    chunk_pos = chunk_limit;
                } else {
                    chunk_pos = end;
                }
                continue;
            }
            
            // Invalid character
            a_stage1->error_code = STAGE1_ERROR_INVALID_UTF8;
            a_stage1->error_position = chunk_pos;
            snprintf(a_stage1->error_message, sizeof(a_stage1->error_message),
                     "Invalid character 0x%02X at position %zu", c, chunk_pos);
            return STAGE1_ERROR_INVALID_UTF8;
        }
        
        // Move to next chunk (if not already moved by spanning token)
        if (pos < chunk_limit) {
            pos = chunk_limit;
        }
    }
    
    // Phase 3: Tail processing (< chunk_size bytes)
    while (pos < input_len) {
        // Skip whitespace
        while (pos < input_len && (input[pos] == ' ' || input[pos] == '\t' ||
                                   input[pos] == '\r' || input[pos] == '\n')) {
            a_stage1->whitespace_chars++;
            pos++;
        }
        
        if (pos >= input_len) break;
        
        uint8_t c = input[pos];
        
        // Structural
        if (c == '{' || c == '}' || c == '[' || c == ']' || c == ':' || c == ',') {
            int ret = s_add_token_sse2(a_stage1, (uint32_t)pos, 0, TOKEN_TYPE_STRUCTURAL, c);
            if (ret != STAGE1_SUCCESS) return ret;
            a_stage1->structural_chars++;
            pos++;
        }
        // String
        else if (c == '"') {
            size_t end = s_scan_string_fast_sse2(a_stage1, pos);
            if (end == pos) return a_stage1->error_code;
            
            size_t str_len = end - pos;
            int ret = s_add_token_sse2(a_stage1, (uint32_t)pos, (uint32_t)str_len,
                                 TOKEN_TYPE_STRING, 0);
            if (ret != STAGE1_SUCCESS) return ret;
            
            a_stage1->string_count++;
            a_stage1->string_chars += str_len;
            pos = end;
        }
        // Number
        else if (c == '-' || (c >= '0' && c <= '9')) {
            size_t end = dap_json_stage1_scan_number_ref(a_stage1, pos);
            if (end == pos) return a_stage1->error_code;
            
            size_t num_len = end - pos;
            int ret = s_add_token_sse2(a_stage1, (uint32_t)pos, (uint32_t)num_len,
                                 TOKEN_TYPE_NUMBER, 0);
            if (ret != STAGE1_SUCCESS) return ret;
            
            a_stage1->number_count++;
            pos = end;
        }
        // Literal
        else if (c == 't' || c == 'f' || c == 'n') {
            size_t end = dap_json_stage1_scan_literal_ref(a_stage1, pos);
            if (end == pos) return a_stage1->error_code;
            
            // Determine literal type from first character
            uint8_t lit_type = DAP_JSON_LITERAL_UNKNOWN;
            if (c == 't') lit_type = DAP_JSON_LITERAL_TRUE;
            else if (c == 'f') lit_type = DAP_JSON_LITERAL_FALSE;
            else if (c == 'n') lit_type = DAP_JSON_LITERAL_NULL;
            
            size_t lit_len = end - pos;
            int ret = s_add_token_sse2(a_stage1, (uint32_t)pos, (uint32_t)lit_len,
                                 TOKEN_TYPE_LITERAL, lit_type);
            if (ret != STAGE1_SUCCESS) return ret;
            
            a_stage1->literal_count++;
            pos = end;
        }
        else {
            a_stage1->error_code = STAGE1_ERROR_INVALID_UTF8;
            a_stage1->error_position = pos;
            snprintf(a_stage1->error_message, sizeof(a_stage1->error_message),
                     "Invalid character 0x%02X at position %zu", c, pos);
            return STAGE1_ERROR_INVALID_UTF8;
        }
    }
    
    debug_if(dap_json_get_debug(), "SSE2 SimdJSON Stage 1 complete: %zu tokens (%zu structural, %zu strings, %zu numbers, %zu literals)",
             a_stage1->indices_count, a_stage1->structural_chars, a_stage1->string_count,
             a_stage1->number_count, a_stage1->literal_count);
    
    return STAGE1_SUCCESS;
}

/**
 * @brief Enable/disable detailed debug logging for SSE2 implementation
 * @param a_enable true to enable detailed logging
 */
void dap_json_stage1_sse2_set_debug(bool a_enable)
{
    // SSE2 now uses global dap_json_get_debug(), no local flag needed
    (void)a_enable;
}

