/*
 * Precomputed tables for secp256k1 ECDSA operations
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: generate_precomputed.py
 * 
 * Configuration:
 *   WINDOW_G = 15
 *   Table size = 8192 points per table
 *   Memory usage = ~1024 KB (two tables)
 */

#ifndef ECDSA_PRECOMPUTED_ECMULT_H
#define ECDSA_PRECOMPUTED_ECMULT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Window size for G multiplication (larger = faster, more memory)
#define ECDSA_WINDOW_G 15

// Number of points in each table: 2^(WINDOW_G - 2)
#define ECDSA_ECMULT_TABLE_SIZE (1 << (ECDSA_WINDOW_G - 2))

// Compact storage format for affine points (64 bytes each)
typedef struct {
    uint64_t x[4];
    uint64_t y[4];
} ecdsa_ge_storage_t;

// Precomputed table for G: pre_g[i] = (2*i + 1) * G
extern const ecdsa_ge_storage_t ecdsa_pre_g[ECDSA_ECMULT_TABLE_SIZE];

// Precomputed table for G*2^128: pre_g_128[i] = (2*i + 1) * (2^128 * G)
extern const ecdsa_ge_storage_t ecdsa_pre_g_128[ECDSA_ECMULT_TABLE_SIZE];

#ifdef __cplusplus
}
#endif

#endif // ECDSA_PRECOMPUTED_ECMULT_H
