{{! x86 AVX2+AVX-512VL ML-KEM NTT — butterfly macros + function bodies }}
{{! Uses EVEX encoding for 32 YMM registers (ymm0-ymm31).           }}
{{! Requires: AVX2, AVX-512F, AVX-512VL, AVX-512BW.                 }}
{{!                                                                   }}
{{! Register allocation (outer layers):                               }}
{{!   ymm0-ymm15   coefficient vectors r0-r15                        }}
{{!   ymm16-ymm19  Montgomery scratch (lo products, hi products)     }}
{{!   ymm20         zeta broadcast                                    }}
{{!   ymm21-ymm24  Montgomery scratch group B                        }}
{{!   ymm25-ymm27  additional scratch (GS butterfly differences)     }}
{{!   ymm28         Barrett constant V=20159                          }}
{{!   ymm29         scratch                                           }}
{{!   ymm30         QINV = -3327 broadcast                            }}
{{!   ymm31         Q = 3329 broadcast                                }}
/*
 * x86 AVX2+AVX-512VL ML-KEM NTT — AUTO-GENERATED by dap_tpl
 *
 * Architecture: hybrid approach
 *   Outer layers (7-4): fully unrolled, all 16 data in ymm0-15
 *   Inner layers (3-1): looped per register pair with integrated shuffles
 *
 * Forward NTT: ~1.5 KB code (vs 5.7 KB fully unrolled)
 * Inverse NTT: ~1.8 KB code (vs 7.7 KB fully unrolled)
 *
 * @generated
 */

/* ═══════════════════════════════════════════════════════════════════
 * MACROS
 * ═══════════════════════════════════════════════════════════════════ */

/*
 * CT butterfly: t = fqmul(z, b);  a' = a+t;  b' = a-t
 * Scratch: ymm16, ymm17
 */
.macro CT_BF a, b, z
    vpmullw \z, \b, %ymm16
    vpmulhw \z, \b, %ymm17
    vpmullw %ymm30, %ymm16, %ymm16
    vpmulhw %ymm31, %ymm16, %ymm16
    vpsubw  %ymm16, %ymm17, %ymm16
    vpsubw  %ymm16, \a, \b
    vpaddw  %ymm16, \a, \a
.endm

/*
 * 4-wide interleaved CT butterfly (same zeta).
 * Scratch: ymm16-ymm19, ymm21-ymm24
 */
.macro CT_BF4 a0, b0, a1, b1, a2, b2, a3, b3, z
    vpmullw \z, \b0, %ymm16
    vpmullw \z, \b1, %ymm17
    vpmullw \z, \b2, %ymm18
    vpmullw \z, \b3, %ymm19
    vpmulhw \z, \b0, %ymm21
    vpmulhw \z, \b1, %ymm22
    vpmulhw \z, \b2, %ymm23
    vpmulhw \z, \b3, %ymm24
    vpmullw %ymm30, %ymm16, %ymm16
    vpmullw %ymm30, %ymm17, %ymm17
    vpmullw %ymm30, %ymm18, %ymm18
    vpmullw %ymm30, %ymm19, %ymm19
    vpmulhw %ymm31, %ymm16, %ymm16
    vpmulhw %ymm31, %ymm17, %ymm17
    vpmulhw %ymm31, %ymm18, %ymm18
    vpmulhw %ymm31, %ymm19, %ymm19
    vpsubw  %ymm16, %ymm21, %ymm16
    vpsubw  %ymm17, %ymm22, %ymm17
    vpsubw  %ymm18, %ymm23, %ymm18
    vpsubw  %ymm19, %ymm24, %ymm19
    vpsubw  %ymm16, \a0, \b0
    vpaddw  %ymm16, \a0, \a0
    vpsubw  %ymm17, \a1, \b1
    vpaddw  %ymm17, \a1, \a1
    vpsubw  %ymm18, \a2, \b2
    vpaddw  %ymm18, \a2, \a2
    vpsubw  %ymm19, \a3, \b3
    vpaddw  %ymm19, \a3, \a3
.endm

/*
 * GS butterfly: t=a-b; a'=barrett(a+b); b'=fqmul(z,t)
 * Scratch: ymm16, ymm17, ymm25
 */
.macro GS_BF a, b, z
    vpsubw  \b, \a, %ymm25
    vpaddw  \b, \a, \a
    BARRETT \a
    vpmullw \z, %ymm25, %ymm16
    vpmulhw \z, %ymm25, %ymm17
    vpmullw %ymm30, %ymm16, %ymm16
    vpmulhw %ymm31, %ymm16, %ymm16
    vpsubw  %ymm16, %ymm17, \b
.endm

/*
 * 4-wide interleaved GS butterfly.
 * Scratch: ymm16-ymm19, ymm21-ymm27, ymm29
 */
.macro GS_BF4 a0, b0, a1, b1, a2, b2, a3, b3, z
    vpsubw  \b0, \a0, %ymm25
    vpsubw  \b1, \a1, %ymm26
    vpsubw  \b2, \a2, %ymm27
    vpsubw  \b3, \a3, %ymm29
    vpaddw  \b0, \a0, \a0
    vpaddw  \b1, \a1, \a1
    vpaddw  \b2, \a2, \a2
    vpaddw  \b3, \a3, \a3
    BARRETT \a0
    BARRETT \a1
    BARRETT \a2
    BARRETT \a3
    vpmullw \z, %ymm25, %ymm16
    vpmullw \z, %ymm26, %ymm17
    vpmullw \z, %ymm27, %ymm18
    vpmullw \z, %ymm29, %ymm19
    vpmulhw \z, %ymm25, %ymm21
    vpmulhw \z, %ymm26, %ymm22
    vpmulhw \z, %ymm27, %ymm23
    vpmulhw \z, %ymm29, %ymm24
    vpmullw %ymm30, %ymm16, %ymm16
    vpmullw %ymm30, %ymm17, %ymm17
    vpmullw %ymm30, %ymm18, %ymm18
    vpmullw %ymm30, %ymm19, %ymm19
    vpmulhw %ymm31, %ymm16, %ymm16
    vpmulhw %ymm31, %ymm17, %ymm17
    vpmulhw %ymm31, %ymm18, %ymm18
    vpmulhw %ymm31, %ymm19, %ymm19
    vpsubw  %ymm16, %ymm21, \b0
    vpsubw  %ymm17, %ymm22, \b1
    vpsubw  %ymm18, %ymm23, \b2
    vpsubw  %ymm19, %ymm24, \b3
.endm

.macro BARRETT reg
    vpmulhw %ymm28, \reg, %ymm16
    vpsraw  $10, %ymm16, %ymm16
    vpmullw %ymm31, %ymm16, %ymm16
    vpsubw  %ymm16, \reg, \reg
.endm

.macro FQMUL dst, z, src
    vpmullw \z, \src, %ymm16
    vpmulhw \z, \src, %ymm17
    vpmullw %ymm30, %ymm16, %ymm16
    vpmulhw %ymm31, %ymm16, %ymm16
    vpsubw  %ymm16, %ymm17, \dst
.endm

/* Shuffle macros for inner layer transposition (hardcoded ymm2 scratch) */
.macro SHUFFLE8 a, b
    vmovdqa32 \a, %ymm2
    vshufi32x4 $0, \b, \a, \a
    vshufi32x4 $3, \b, %ymm2, \b
.endm

.macro SHUFFLE4 a, b
    vmovdqa32 \a, %ymm2
    vpunpcklqdq \b, \a, \a
    vpunpckhqdq \b, %ymm2, \b
.endm

.macro SHUFFLE2 a, b
    vmovsldup \b, %ymm2
    vpblendd $0xAA, %ymm2, \a, %ymm2
    vpsrlq  $32, \a, \a
    vpblendd $0xAA, \b, \a, \b
    vmovdqa32 %ymm2, \a
.endm

.macro SHUFFLE1 a, b
    vpslld  $16, \b, %ymm2
    vpblendw $0xAA, %ymm2, \a, %ymm2
    vpsrld  $16, \a, \a
    vpblendw $0xAA, \b, \a, \b
    vmovdqa32 %ymm2, \a
.endm

/*
 * Parametric shuffle macros using EVEX-only instructions.
 * k1 = 0xAA (dword blend mask), k2 = 0xAAAA (word blend mask).
 * Must be set up before use.
 */
.macro SH8 a, b, t
    vmovdqa32 \a, \t
    vshufi32x4 $0, \b, \a, \a
    vshufi32x4 $3, \b, \t, \b
.endm

.macro SH4 a, b, t
    vmovdqa32 \a, \t
    vpunpcklqdq \b, \a, \a
    vpunpckhqdq \b, \t, \b
.endm

.macro SH2 a, b, t
    vmovsldup \b, \t
    vpblendmd \t, \a, \t{%k1}
    vpsrlq  $32, \a, \a
    vpblendmd \b, \a, \b{%k1}
    vmovdqa32 \t, \a
.endm

.macro SH1 a, b, t
    vpslld  $16, \b, \t
    vpblendmw \t, \a, \t{%k2}
    vpsrld  $16, \a, \a
    vpblendmw \b, \a, \b{%k2}
    vmovdqa32 \t, \a
.endm


/* ═══════════════════════════════════════════════════════════════════
 * FORWARD NTT — fully in-register (no intermediate store/reload)
 * void dap_mlkem_ntt_forward_asm(int16_t coeffs[256]);
 *
 * All 7 layers execute with ymm0-15 resident in registers.
 * Inner layers (3-1) + nttpack are fully unrolled across all 8 pairs.
 * ymm25 = shuffle scratch, ymm20 = zeta, ymm28/30/31 = constants.
 * ═══════════════════════════════════════════════════════════════════ */

.text
.globl CDECL(dap_mlkem_ntt_forward_asm)
.type  CDECL(dap_mlkem_ntt_forward_asm), @function
.balign 64
CDECL(dap_mlkem_ntt_forward_asm):
    vmovdqa32 ntt_q(%rip), %ymm31
    vmovdqa32 ntt_qinv(%rip), %ymm30
    vmovdqa32 ntt_barrett_v(%rip), %ymm28
    movl    $0xAA, %eax
    kmovd   %eax, %k1
    movl    $0xAAAA, %eax
    kmovd   %eax, %k2

    /* Load 256 coefficients into ymm0-ymm15 */
    vmovdqu     (%rdi), %ymm0
    vmovdqu  32(%rdi), %ymm1
    vmovdqu  64(%rdi), %ymm2
    vmovdqu  96(%rdi), %ymm3
    vmovdqu 128(%rdi), %ymm4
    vmovdqu 160(%rdi), %ymm5
    vmovdqu 192(%rdi), %ymm6
    vmovdqu 224(%rdi), %ymm7
    vmovdqu 256(%rdi), %ymm8
    vmovdqu 288(%rdi), %ymm9
    vmovdqu 320(%rdi), %ymm10
    vmovdqu 352(%rdi), %ymm11
    vmovdqu 384(%rdi), %ymm12
    vmovdqu 416(%rdi), %ymm13
    vmovdqu 448(%rdi), %ymm14
    vmovdqu 480(%rdi), %ymm15

    /* ── Layer 7 (len=128): 1 zeta, 8 butterfly pairs ── */
    vmovdqa32 fwd_z7(%rip), %ymm20
    CT_BF4 %ymm0, %ymm8,  %ymm1, %ymm9,  %ymm2, %ymm10, %ymm3, %ymm11, %ymm20
    CT_BF4 %ymm4, %ymm12, %ymm5, %ymm13, %ymm6, %ymm14, %ymm7, %ymm15, %ymm20

    /* ── Layer 6 (len=64): 2 zetas ── */
    vmovdqa32 fwd_z6_0(%rip), %ymm20
    CT_BF4 %ymm0, %ymm4, %ymm1, %ymm5, %ymm2, %ymm6, %ymm3, %ymm7, %ymm20
    vmovdqa32 fwd_z6_1(%rip), %ymm20
    CT_BF4 %ymm8, %ymm12, %ymm9, %ymm13, %ymm10, %ymm14, %ymm11, %ymm15, %ymm20

    /* ── Layer 5 (len=32): 4 zetas ── */
    vmovdqa32 fwd_z5_0(%rip), %ymm20
    CT_BF %ymm0, %ymm2, %ymm20
    CT_BF %ymm1, %ymm3, %ymm20
    vmovdqa32 fwd_z5_1(%rip), %ymm20
    CT_BF %ymm4, %ymm6, %ymm20
    CT_BF %ymm5, %ymm7, %ymm20
    vmovdqa32 fwd_z5_2(%rip), %ymm20
    CT_BF %ymm8,  %ymm10, %ymm20
    CT_BF %ymm9,  %ymm11, %ymm20
    vmovdqa32 fwd_z5_3(%rip), %ymm20
    CT_BF %ymm12, %ymm14, %ymm20
    CT_BF %ymm13, %ymm15, %ymm20

    /* ── Layer 4 (len=16): 8 zetas ── */
    vmovdqa32 fwd_z4_0(%rip), %ymm20
    CT_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 fwd_z4_1(%rip), %ymm20
    CT_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 fwd_z4_2(%rip), %ymm20
    CT_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 fwd_z4_3(%rip), %ymm20
    CT_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 fwd_z4_4(%rip), %ymm20
    CT_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 fwd_z4_5(%rip), %ymm20
    CT_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 fwd_z4_6(%rip), %ymm20
    CT_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 fwd_z4_7(%rip), %ymm20
    CT_BF %ymm14, %ymm15, %ymm20

    /* ═══ Inner layers fully in-register (no store/reload) ═══ */

    /* ── SHUFFLE8 all 8 pairs: separate 128-bit halves ── */
    SH8 %ymm0,  %ymm1,  %ymm25
    SH8 %ymm2,  %ymm3,  %ymm25
    SH8 %ymm4,  %ymm5,  %ymm25
    SH8 %ymm6,  %ymm7,  %ymm25
    SH8 %ymm8,  %ymm9,  %ymm25
    SH8 %ymm10, %ymm11, %ymm25
    SH8 %ymm12, %ymm13, %ymm25
    SH8 %ymm14, %ymm15, %ymm25

    /* ── Layer 3 (len=8): half-broadcast zetas ── */
    leaq    fwd_inner_zetas(%rip), %rsi
    vmovdqa32    (%rsi), %ymm20
    CT_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32  96(%rsi), %ymm20
    CT_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 192(%rsi), %ymm20
    CT_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 288(%rsi), %ymm20
    CT_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 384(%rsi), %ymm20
    CT_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 480(%rsi), %ymm20
    CT_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 576(%rsi), %ymm20
    CT_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 672(%rsi), %ymm20
    CT_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE4 all 8 pairs: separate 64-bit groups ── */
    SH4 %ymm0,  %ymm1,  %ymm25
    SH4 %ymm2,  %ymm3,  %ymm25
    SH4 %ymm4,  %ymm5,  %ymm25
    SH4 %ymm6,  %ymm7,  %ymm25
    SH4 %ymm8,  %ymm9,  %ymm25
    SH4 %ymm10, %ymm11, %ymm25
    SH4 %ymm12, %ymm13, %ymm25
    SH4 %ymm14, %ymm15, %ymm25

    /* ── Layer 2 (len=4): quad-broadcast zetas ── */
    vmovdqa32  32(%rsi), %ymm20
    CT_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 128(%rsi), %ymm20
    CT_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 224(%rsi), %ymm20
    CT_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 320(%rsi), %ymm20
    CT_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 416(%rsi), %ymm20
    CT_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 512(%rsi), %ymm20
    CT_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 608(%rsi), %ymm20
    CT_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 704(%rsi), %ymm20
    CT_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE2 all 8 pairs: separate 32-bit pairs ── */
    SH2 %ymm0,  %ymm1,  %ymm25
    SH2 %ymm2,  %ymm3,  %ymm25
    SH2 %ymm4,  %ymm5,  %ymm25
    SH2 %ymm6,  %ymm7,  %ymm25
    SH2 %ymm8,  %ymm9,  %ymm25
    SH2 %ymm10, %ymm11, %ymm25
    SH2 %ymm12, %ymm13, %ymm25
    SH2 %ymm14, %ymm15, %ymm25

    /* ── Layer 1 (len=2): pair-broadcast zetas ── */
    vmovdqa32  64(%rsi), %ymm20
    CT_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 160(%rsi), %ymm20
    CT_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 256(%rsi), %ymm20
    CT_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 352(%rsi), %ymm20
    CT_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 448(%rsi), %ymm20
    CT_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 544(%rsi), %ymm20
    CT_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 640(%rsi), %ymm20
    CT_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 736(%rsi), %ymm20
    CT_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE1 all 8 pairs: nttpack transposition ── */
    SH1 %ymm0,  %ymm1,  %ymm25
    SH1 %ymm2,  %ymm3,  %ymm25
    SH1 %ymm4,  %ymm5,  %ymm25
    SH1 %ymm6,  %ymm7,  %ymm25
    SH1 %ymm8,  %ymm9,  %ymm25
    SH1 %ymm10, %ymm11, %ymm25
    SH1 %ymm12, %ymm13, %ymm25
    SH1 %ymm14, %ymm15, %ymm25

    /* ── Barrett reduce all 16 vectors ── */
    BARRETT %ymm0
    BARRETT %ymm1
    BARRETT %ymm2
    BARRETT %ymm3
    BARRETT %ymm4
    BARRETT %ymm5
    BARRETT %ymm6
    BARRETT %ymm7
    BARRETT %ymm8
    BARRETT %ymm9
    BARRETT %ymm10
    BARRETT %ymm11
    BARRETT %ymm12
    BARRETT %ymm13
    BARRETT %ymm14
    BARRETT %ymm15

    /* ── Store all 16 vectors ── */
    vmovdqu %ymm0,      (%rdi)
    vmovdqu %ymm1,   32(%rdi)
    vmovdqu %ymm2,   64(%rdi)
    vmovdqu %ymm3,   96(%rdi)
    vmovdqu %ymm4,  128(%rdi)
    vmovdqu %ymm5,  160(%rdi)
    vmovdqu %ymm6,  192(%rdi)
    vmovdqu %ymm7,  224(%rdi)
    vmovdqu %ymm8,  256(%rdi)
    vmovdqu %ymm9,  288(%rdi)
    vmovdqu %ymm10, 320(%rdi)
    vmovdqu %ymm11, 352(%rdi)
    vmovdqu %ymm12, 384(%rdi)
    vmovdqu %ymm13, 416(%rdi)
    vmovdqu %ymm14, 448(%rdi)
    vmovdqu %ymm15, 480(%rdi)

    vzeroupper
    ret
.size CDECL(dap_mlkem_ntt_forward_asm), .-CDECL(dap_mlkem_ntt_forward_asm)


/* ═══════════════════════════════════════════════════════════════════
 * INVERSE NTT — fully in-register (no intermediate store/reload)
 * void dap_mlkem_ntt_inverse_asm(int16_t coeffs[256]);
 *
 * All 7 layers execute with ymm0-15 resident in registers.
 * Inner layers (1-3) + nttunpack are fully unrolled across all 8 pairs.
 * ═══════════════════════════════════════════════════════════════════ */

.balign 64
.globl CDECL(dap_mlkem_ntt_inverse_asm)
.type  CDECL(dap_mlkem_ntt_inverse_asm), @function
CDECL(dap_mlkem_ntt_inverse_asm):
    vmovdqa32 ntt_q(%rip), %ymm31
    vmovdqa32 ntt_qinv(%rip), %ymm30
    vmovdqa32 ntt_barrett_v(%rip), %ymm28
    movl    $0xAA, %eax
    kmovd   %eax, %k1
    movl    $0xAAAA, %eax
    kmovd   %eax, %k2

    /* Load 256 coefficients into ymm0-ymm15 */
    vmovdqu     (%rdi), %ymm0
    vmovdqu  32(%rdi), %ymm1
    vmovdqu  64(%rdi), %ymm2
    vmovdqu  96(%rdi), %ymm3
    vmovdqu 128(%rdi), %ymm4
    vmovdqu 160(%rdi), %ymm5
    vmovdqu 192(%rdi), %ymm6
    vmovdqu 224(%rdi), %ymm7
    vmovdqu 256(%rdi), %ymm8
    vmovdqu 288(%rdi), %ymm9
    vmovdqu 320(%rdi), %ymm10
    vmovdqu 352(%rdi), %ymm11
    vmovdqu 384(%rdi), %ymm12
    vmovdqu 416(%rdi), %ymm13
    vmovdqu 448(%rdi), %ymm14
    vmovdqu 480(%rdi), %ymm15

    /* ═══ Inner layers fully in-register: nttunpack + layers 1→3 ═══ */

    leaq    inv_inner_zetas(%rip), %rsi

    /* ── SHUFFLE1 all 8 pairs: undo nttpack ── */
    SH1 %ymm0,  %ymm1,  %ymm25
    SH1 %ymm2,  %ymm3,  %ymm25
    SH1 %ymm4,  %ymm5,  %ymm25
    SH1 %ymm6,  %ymm7,  %ymm25
    SH1 %ymm8,  %ymm9,  %ymm25
    SH1 %ymm10, %ymm11, %ymm25
    SH1 %ymm12, %ymm13, %ymm25
    SH1 %ymm14, %ymm15, %ymm25

    /* ── Inverse layer 1 (GS, len=2): pair-broadcast zetas ── */
    vmovdqa32    (%rsi), %ymm20
    GS_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32  96(%rsi), %ymm20
    GS_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 192(%rsi), %ymm20
    GS_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 288(%rsi), %ymm20
    GS_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 384(%rsi), %ymm20
    GS_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 480(%rsi), %ymm20
    GS_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 576(%rsi), %ymm20
    GS_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 672(%rsi), %ymm20
    GS_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE2 all 8 pairs ── */
    SH2 %ymm0,  %ymm1,  %ymm25
    SH2 %ymm2,  %ymm3,  %ymm25
    SH2 %ymm4,  %ymm5,  %ymm25
    SH2 %ymm6,  %ymm7,  %ymm25
    SH2 %ymm8,  %ymm9,  %ymm25
    SH2 %ymm10, %ymm11, %ymm25
    SH2 %ymm12, %ymm13, %ymm25
    SH2 %ymm14, %ymm15, %ymm25

    /* ── Inverse layer 2 (GS, len=4): quad-broadcast zetas ── */
    vmovdqa32  32(%rsi), %ymm20
    GS_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 128(%rsi), %ymm20
    GS_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 224(%rsi), %ymm20
    GS_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 320(%rsi), %ymm20
    GS_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 416(%rsi), %ymm20
    GS_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 512(%rsi), %ymm20
    GS_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 608(%rsi), %ymm20
    GS_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 704(%rsi), %ymm20
    GS_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE4 all 8 pairs ── */
    SH4 %ymm0,  %ymm1,  %ymm25
    SH4 %ymm2,  %ymm3,  %ymm25
    SH4 %ymm4,  %ymm5,  %ymm25
    SH4 %ymm6,  %ymm7,  %ymm25
    SH4 %ymm8,  %ymm9,  %ymm25
    SH4 %ymm10, %ymm11, %ymm25
    SH4 %ymm12, %ymm13, %ymm25
    SH4 %ymm14, %ymm15, %ymm25

    /* ── Inverse layer 3 (GS, len=8): half-broadcast zetas ── */
    vmovdqa32  64(%rsi), %ymm20
    GS_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 160(%rsi), %ymm20
    GS_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 256(%rsi), %ymm20
    GS_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 352(%rsi), %ymm20
    GS_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 448(%rsi), %ymm20
    GS_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 544(%rsi), %ymm20
    GS_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 640(%rsi), %ymm20
    GS_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 736(%rsi), %ymm20
    GS_BF %ymm14, %ymm15, %ymm20

    /* ── SHUFFLE8 all 8 pairs: back to standard layout ── */
    SH8 %ymm0,  %ymm1,  %ymm25
    SH8 %ymm2,  %ymm3,  %ymm25
    SH8 %ymm4,  %ymm5,  %ymm25
    SH8 %ymm6,  %ymm7,  %ymm25
    SH8 %ymm8,  %ymm9,  %ymm25
    SH8 %ymm10, %ymm11, %ymm25
    SH8 %ymm12, %ymm13, %ymm25
    SH8 %ymm14, %ymm15, %ymm25

    /* ═══ Outer layers 4→7 (GS) ═══ */

    /* ── Layer 4 (GS, len=16): 8 zetas ── */
    vmovdqa32 inv_z4_0(%rip), %ymm20
    GS_BF %ymm0,  %ymm1,  %ymm20
    vmovdqa32 inv_z4_1(%rip), %ymm20
    GS_BF %ymm2,  %ymm3,  %ymm20
    vmovdqa32 inv_z4_2(%rip), %ymm20
    GS_BF %ymm4,  %ymm5,  %ymm20
    vmovdqa32 inv_z4_3(%rip), %ymm20
    GS_BF %ymm6,  %ymm7,  %ymm20
    vmovdqa32 inv_z4_4(%rip), %ymm20
    GS_BF %ymm8,  %ymm9,  %ymm20
    vmovdqa32 inv_z4_5(%rip), %ymm20
    GS_BF %ymm10, %ymm11, %ymm20
    vmovdqa32 inv_z4_6(%rip), %ymm20
    GS_BF %ymm12, %ymm13, %ymm20
    vmovdqa32 inv_z4_7(%rip), %ymm20
    GS_BF %ymm14, %ymm15, %ymm20

    /* ── Layer 5 (GS, len=32): 4 zetas ── */
    vmovdqa32 inv_z5_0(%rip), %ymm20
    GS_BF %ymm0,  %ymm2,  %ymm20
    GS_BF %ymm1,  %ymm3,  %ymm20
    vmovdqa32 inv_z5_1(%rip), %ymm20
    GS_BF %ymm4,  %ymm6,  %ymm20
    GS_BF %ymm5,  %ymm7,  %ymm20
    vmovdqa32 inv_z5_2(%rip), %ymm20
    GS_BF %ymm8,  %ymm10, %ymm20
    GS_BF %ymm9,  %ymm11, %ymm20
    vmovdqa32 inv_z5_3(%rip), %ymm20
    GS_BF %ymm12, %ymm14, %ymm20
    GS_BF %ymm13, %ymm15, %ymm20

    /* ── Layer 6 (GS, len=64): 2 zetas ── */
    vmovdqa32 inv_z6_0(%rip), %ymm20
    GS_BF4 %ymm0, %ymm4, %ymm1, %ymm5, %ymm2, %ymm6, %ymm3, %ymm7, %ymm20
    vmovdqa32 inv_z6_1(%rip), %ymm20
    GS_BF4 %ymm8, %ymm12, %ymm9, %ymm13, %ymm10, %ymm14, %ymm11, %ymm15, %ymm20

    /* ── Layer 7 (GS, len=128): 1 zeta ── */
    vmovdqa32 inv_z7(%rip), %ymm20
    GS_BF4 %ymm0, %ymm8,  %ymm1, %ymm9,  %ymm2, %ymm10, %ymm3, %ymm11, %ymm20
    GS_BF4 %ymm4, %ymm12, %ymm5, %ymm13, %ymm6, %ymm14, %ymm7, %ymm15, %ymm20

    /* ── Scale by f = 1441 ── */
    vmovdqa32 ntt_f_scale(%rip), %ymm20
    FQMUL %ymm0,  %ymm20, %ymm0
    FQMUL %ymm1,  %ymm20, %ymm1
    FQMUL %ymm2,  %ymm20, %ymm2
    FQMUL %ymm3,  %ymm20, %ymm3
    FQMUL %ymm4,  %ymm20, %ymm4
    FQMUL %ymm5,  %ymm20, %ymm5
    FQMUL %ymm6,  %ymm20, %ymm6
    FQMUL %ymm7,  %ymm20, %ymm7
    FQMUL %ymm8,  %ymm20, %ymm8
    FQMUL %ymm9,  %ymm20, %ymm9
    FQMUL %ymm10, %ymm20, %ymm10
    FQMUL %ymm11, %ymm20, %ymm11
    FQMUL %ymm12, %ymm20, %ymm12
    FQMUL %ymm13, %ymm20, %ymm13
    FQMUL %ymm14, %ymm20, %ymm14
    FQMUL %ymm15, %ymm20, %ymm15

    /* ── Store results ── */
    vmovdqu %ymm0,      (%rdi)
    vmovdqu %ymm1,   32(%rdi)
    vmovdqu %ymm2,   64(%rdi)
    vmovdqu %ymm3,   96(%rdi)
    vmovdqu %ymm4,  128(%rdi)
    vmovdqu %ymm5,  160(%rdi)
    vmovdqu %ymm6,  192(%rdi)
    vmovdqu %ymm7,  224(%rdi)
    vmovdqu %ymm8,  256(%rdi)
    vmovdqu %ymm9,  288(%rdi)
    vmovdqu %ymm10, 320(%rdi)
    vmovdqu %ymm11, 352(%rdi)
    vmovdqu %ymm12, 384(%rdi)
    vmovdqu %ymm13, 416(%rdi)
    vmovdqu %ymm14, 448(%rdi)
    vmovdqu %ymm15, 480(%rdi)

    vzeroupper
    ret
.size CDECL(dap_mlkem_ntt_inverse_asm), .-CDECL(dap_mlkem_ntt_inverse_asm)


/* ═══════════════════════════════════════════════════════════════════
 * NTTPACK — standalone, for use outside NTT
 * void dap_mlkem_ntt_nttpack_asm(int16_t coeffs[256]);
 * ═══════════════════════════════════════════════════════════════════ */

.balign 32
.globl CDECL(dap_mlkem_ntt_nttpack_asm)
.type  CDECL(dap_mlkem_ntt_nttpack_asm), @function
CDECL(dap_mlkem_ntt_nttpack_asm):
    vmovdqa32 nttpack_even_idx(%rip), %ymm2
    vmovdqa32 nttpack_odd_idx(%rip), %ymm3
    xorl    %ecx, %ecx
.Lpack_loop:
    vmovdqu (%rdi,%rcx), %ymm0
    vmovdqu 32(%rdi,%rcx), %ymm1
    vmovdqa32 %ymm0, %ymm4
    vpermt2w %ymm1, %ymm2, %ymm0
    vpermt2w %ymm1, %ymm3, %ymm4
    vmovdqu %ymm0, (%rdi,%rcx)
    vmovdqu %ymm4, 32(%rdi,%rcx)
    addl    $64, %ecx
    cmpl    $512, %ecx
    jl      .Lpack_loop
    vzeroupper
    ret
.size CDECL(dap_mlkem_ntt_nttpack_asm), .-CDECL(dap_mlkem_ntt_nttpack_asm)


/* ═══════════════════════════════════════════════════════════════════
 * NTTUNPACK — standalone, for use outside NTT
 * void dap_mlkem_ntt_nttunpack_asm(int16_t coeffs[256]);
 * ═══════════════════════════════════════════════════════════════════ */

.balign 32
.globl CDECL(dap_mlkem_ntt_nttunpack_asm)
.type  CDECL(dap_mlkem_ntt_nttunpack_asm), @function
CDECL(dap_mlkem_ntt_nttunpack_asm):
    vmovdqa32 nttunpack_lo_idx(%rip), %ymm2
    vmovdqa32 nttunpack_hi_idx(%rip), %ymm3
    xorl    %ecx, %ecx
.Lunpack_loop:
    vmovdqu (%rdi,%rcx), %ymm0
    vmovdqu 32(%rdi,%rcx), %ymm1
    vmovdqa32 %ymm0, %ymm4
    vpermt2w %ymm1, %ymm2, %ymm0
    vpermt2w %ymm1, %ymm3, %ymm4
    vmovdqu %ymm0, (%rdi,%rcx)
    vmovdqu %ymm4, 32(%rdi,%rcx)
    addl    $64, %ecx
    cmpl    $512, %ecx
    jl      .Lunpack_loop
    vzeroupper
    ret
.size CDECL(dap_mlkem_ntt_nttunpack_asm), .-CDECL(dap_mlkem_ntt_nttunpack_asm)


/* ═══════════════════════════════════════════════════════════════════
 * BASEMUL — single polynomial basemul_montgomery
 * void dap_mlkem_basemul_asm(int16_t *r, const int16_t *a,
 *                            const int16_t *b, const int16_t *zetas);
 *   rdi=r, rsi=a, rdx=b, rcx=zetas (ignored, embedded table used)
 * ═══════════════════════════════════════════════════════════════════ */

.balign 64
.globl CDECL(dap_mlkem_basemul_asm)
.type  CDECL(dap_mlkem_basemul_asm), @function
CDECL(dap_mlkem_basemul_asm):
    vmovdqa32 ntt_q(%rip), %ymm31
    vmovdqa32 ntt_qinv(%rip), %ymm30
    vmovdqa32 basemul_swap_mask(%rip), %ymm29

    lea basemul_zetas(%rip), %rax
    xor %r10d, %r10d

.Lbm_loop:
    vmovdqu (%rsi, %r10), %ymm0
    vmovdqu 32(%rsi, %r10), %ymm1
    vmovdqu (%rdx, %r10), %ymm2
    vmovdqu 32(%rdx, %r10), %ymm3
    vmovdqa32 (%rax, %r10), %ymm24
    vmovdqa32 32(%rax, %r10), %ymm25

    vpshufb %ymm29, %ymm2, %ymm4
    vpshufb %ymm29, %ymm3, %ymm5

    vpmullw %ymm0, %ymm2, %ymm6
    vpmullw %ymm1, %ymm3, %ymm7
    vpmulhw %ymm0, %ymm2, %ymm8
    vpmulhw %ymm1, %ymm3, %ymm9
    vpmullw %ymm30, %ymm6, %ymm6
    vpmullw %ymm30, %ymm7, %ymm7
    vpmulhw %ymm31, %ymm6, %ymm6
    vpmulhw %ymm31, %ymm7, %ymm7
    vpsubw  %ymm6, %ymm8, %ymm6
    vpsubw  %ymm7, %ymm9, %ymm7

    vpmullw %ymm0, %ymm4, %ymm8
    vpmullw %ymm1, %ymm5, %ymm9
    vpmulhw %ymm0, %ymm4, %ymm10
    vpmulhw %ymm1, %ymm5, %ymm11
    vpmullw %ymm30, %ymm8, %ymm8
    vpmullw %ymm30, %ymm9, %ymm9
    vpmulhw %ymm31, %ymm8, %ymm8
    vpmulhw %ymm31, %ymm9, %ymm9
    vpsubw  %ymm8, %ymm10, %ymm8
    vpsubw  %ymm9, %ymm11, %ymm9

    vpmullw %ymm6, %ymm24, %ymm10
    vpmullw %ymm7, %ymm25, %ymm11
    vpmulhw %ymm6, %ymm24, %ymm12
    vpmulhw %ymm7, %ymm25, %ymm13
    vpmullw %ymm30, %ymm10, %ymm10
    vpmullw %ymm30, %ymm11, %ymm11
    vpmulhw %ymm31, %ymm10, %ymm10
    vpmulhw %ymm31, %ymm11, %ymm11
    vpsubw  %ymm10, %ymm12, %ymm10
    vpsubw  %ymm11, %ymm13, %ymm11

    vpshufb %ymm29, %ymm10, %ymm12
    vpshufb %ymm29, %ymm11, %ymm13
    vpaddw  %ymm12, %ymm6, %ymm6
    vpaddw  %ymm13, %ymm7, %ymm7

    vpshufb %ymm29, %ymm8, %ymm12
    vpshufb %ymm29, %ymm9, %ymm13
    vpaddw  %ymm12, %ymm8, %ymm8
    vpaddw  %ymm13, %ymm9, %ymm9

    vpblendw $0xAA, %ymm8, %ymm6, %ymm6
    vpblendw $0xAA, %ymm9, %ymm7, %ymm7

    vmovdqu %ymm6, (%rdi, %r10)
    vmovdqu %ymm7, 32(%rdi, %r10)

    add $64, %r10d
    cmp $512, %r10d
    jl .Lbm_loop

    vzeroupper
    ret
.size CDECL(dap_mlkem_basemul_asm), .-CDECL(dap_mlkem_basemul_asm)


/* ═══════════════════════════════════════════════════════════════════
 * BASEMUL_ACC — fused K × basemul + accumulate + Barrett reduce
 * void dap_mlkem_basemul_acc_asm(int16_t *r,
 *     const int16_t * const *pa, const int16_t * const *pb,
 *     unsigned count);
 *   rdi=r, rsi=pa, rdx=pb, ecx=count
 * ═══════════════════════════════════════════════════════════════════ */

.balign 64
.globl CDECL(dap_mlkem_basemul_acc_asm)
.type  CDECL(dap_mlkem_basemul_acc_asm), @function
CDECL(dap_mlkem_basemul_acc_asm):
    vmovdqa32 ntt_q(%rip), %ymm31
    vmovdqa32 ntt_qinv(%rip), %ymm30
    vmovdqa32 basemul_swap_mask(%rip), %ymm29
    vmovdqa32 ntt_barrett_v(%rip), %ymm28

    lea basemul_zetas(%rip), %rax
    xor %r10d, %r10d

.Lacc_outer:
    vmovdqa32 (%rax, %r10), %ymm24
    vmovdqa32 32(%rax, %r10), %ymm25

    vpxord %ymm26, %ymm26, %ymm26
    vpxord %ymm27, %ymm27, %ymm27

    xor %r11d, %r11d

.Lacc_k:
    mov (%rsi, %r11, 8), %r8
    mov (%rdx, %r11, 8), %r9

    vmovdqu (%r8, %r10), %ymm0
    vmovdqu 32(%r8, %r10), %ymm1
    vmovdqu (%r9, %r10), %ymm2
    vmovdqu 32(%r9, %r10), %ymm3

    vpshufb %ymm29, %ymm2, %ymm4
    vpshufb %ymm29, %ymm3, %ymm5

    vpmullw %ymm0, %ymm2, %ymm6
    vpmullw %ymm1, %ymm3, %ymm7
    vpmulhw %ymm0, %ymm2, %ymm8
    vpmulhw %ymm1, %ymm3, %ymm9
    vpmullw %ymm30, %ymm6, %ymm6
    vpmullw %ymm30, %ymm7, %ymm7
    vpmulhw %ymm31, %ymm6, %ymm6
    vpmulhw %ymm31, %ymm7, %ymm7
    vpsubw  %ymm6, %ymm8, %ymm6
    vpsubw  %ymm7, %ymm9, %ymm7

    vpmullw %ymm0, %ymm4, %ymm8
    vpmullw %ymm1, %ymm5, %ymm9
    vpmulhw %ymm0, %ymm4, %ymm10
    vpmulhw %ymm1, %ymm5, %ymm11
    vpmullw %ymm30, %ymm8, %ymm8
    vpmullw %ymm30, %ymm9, %ymm9
    vpmulhw %ymm31, %ymm8, %ymm8
    vpmulhw %ymm31, %ymm9, %ymm9
    vpsubw  %ymm8, %ymm10, %ymm8
    vpsubw  %ymm9, %ymm11, %ymm9

    vpmullw %ymm6, %ymm24, %ymm10
    vpmullw %ymm7, %ymm25, %ymm11
    vpmulhw %ymm6, %ymm24, %ymm12
    vpmulhw %ymm7, %ymm25, %ymm13
    vpmullw %ymm30, %ymm10, %ymm10
    vpmullw %ymm30, %ymm11, %ymm11
    vpmulhw %ymm31, %ymm10, %ymm10
    vpmulhw %ymm31, %ymm11, %ymm11
    vpsubw  %ymm10, %ymm12, %ymm10
    vpsubw  %ymm11, %ymm13, %ymm11

    vpshufb %ymm29, %ymm10, %ymm12
    vpshufb %ymm29, %ymm11, %ymm13
    vpaddw  %ymm12, %ymm6, %ymm6
    vpaddw  %ymm13, %ymm7, %ymm7

    vpshufb %ymm29, %ymm8, %ymm12
    vpshufb %ymm29, %ymm9, %ymm13
    vpaddw  %ymm12, %ymm8, %ymm8
    vpaddw  %ymm13, %ymm9, %ymm9

    vpblendw $0xAA, %ymm8, %ymm6, %ymm6
    vpblendw $0xAA, %ymm9, %ymm7, %ymm7

    vpaddw  %ymm6, %ymm26, %ymm26
    vpaddw  %ymm7, %ymm27, %ymm27

    inc %r11d
    cmp %ecx, %r11d
    jl .Lacc_k

    vpmulhw %ymm28, %ymm26, %ymm16
    vpmulhw %ymm28, %ymm27, %ymm17
    vpsraw  $10, %ymm16, %ymm16
    vpsraw  $10, %ymm17, %ymm17
    vpmullw %ymm31, %ymm16, %ymm16
    vpmullw %ymm31, %ymm17, %ymm17
    vpsubw  %ymm16, %ymm26, %ymm26
    vpsubw  %ymm17, %ymm27, %ymm27

    vmovdqu32 %ymm26, (%rdi, %r10)
    vmovdqu32 %ymm27, 32(%rdi, %r10)

    add $64, %r10d
    cmp $512, %r10d
    jl .Lacc_outer

    vzeroupper
    ret
.size CDECL(dap_mlkem_basemul_acc_asm), .-CDECL(dap_mlkem_basemul_acc_asm)
