/**
 * @file dap_keccak_ref.c
 * @brief DAP Keccak-p[1600] reference implementation
 * @details Pure C reference implementation written from scratch.
 *          Based on Keccak specification, NOT copied from XKCP.
 *
 * Keccak-p[1600] permutation consists of 24 rounds, each with 5 steps:
 *   θ (theta) - column parity mixing
 *   ρ (rho)   - lane rotation
 *   π (pi)    - lane permutation  
 *   χ (chi)   - nonlinear mixing
 *   ι (iota)  - round constant XOR
 *
 * @author DAP SDK Team
 * @copyright DeM Labs Inc. 2026
 * @license GNU GPL v3
 */

#include <string.h>
#include "dap_hash_keccak.h"

// ============================================================================
// Compile-time constants
// ============================================================================

/**
 * Round constants for ι (iota) step
 * Generated by LFSR in GF(2) with polynomial x^8 + x^6 + x^5 + x^4 + 1
 */
static const uint64_t s_round_constants[DAP_KECCAK_ROUNDS] = {
    0x0000000000000001ULL, 0x0000000000008082ULL,
    0x800000000000808aULL, 0x8000000080008000ULL,
    0x000000000000808bULL, 0x0000000080000001ULL,
    0x8000000080008081ULL, 0x8000000000008009ULL,
    0x000000000000008aULL, 0x0000000000000088ULL,
    0x0000000080008009ULL, 0x000000008000000aULL,
    0x000000008000808bULL, 0x800000000000008bULL,
    0x8000000000008089ULL, 0x8000000000008003ULL,
    0x8000000000008002ULL, 0x8000000000000080ULL,
    0x000000000000800aULL, 0x800000008000000aULL,
    0x8000000080008081ULL, 0x8000000000008080ULL,
    0x0000000080000001ULL, 0x8000000080008008ULL
};

/**
 * Rotation offsets for ρ (rho) step
 * Index: (x + 5*y), values computed from (t+1)(t+2)/2 mod 64
 */
static const unsigned s_rho_offsets[25] = {
    /*       x=0   x=1   x=2   x=3   x=4  */
    /* y=0 */  0,   1,  62,  28,  27,
    /* y=1 */ 36,  44,   6,  55,  20,
    /* y=2 */  3,  10,  43,  25,  39,
    /* y=3 */ 41,  45,  15,  21,   8,
    /* y=4 */ 18,   2,  61,  56,  14
};

// ============================================================================
// Helper macros
// ============================================================================

// State indexing: state[x + 5*y] for position (x, y)
#define IDX(x, y)  ((x) + 5 * (y))

// Rotate left 64-bit
#define ROL64(x, n) (((x) << (n)) | ((x) >> (64 - (n))))

// ============================================================================
// Core Keccak permutation - Reference Implementation
// ============================================================================

void dap_hash_keccak_state_init_ref(dap_hash_keccak_state_t *state)
{
    memset(state->lanes, 0, sizeof(state->lanes));
}

/**
 * @brief θ (theta) step - column parity mixing
 */
static inline void s_theta(uint64_t *lanes)
{
    uint64_t C[5], D[5];
    
    // Compute column parities
    for (int x = 0; x < 5; x++) {
        C[x] = lanes[IDX(x,0)] ^ lanes[IDX(x,1)] ^ lanes[IDX(x,2)] 
             ^ lanes[IDX(x,3)] ^ lanes[IDX(x,4)];
    }
    
    // Compute D[x] = C[x-1] ^ ROL64(C[x+1], 1)
    for (int x = 0; x < 5; x++) {
        D[x] = C[(x + 4) % 5] ^ ROL64(C[(x + 1) % 5], 1);
    }
    
    // XOR D into all lanes
    for (int x = 0; x < 5; x++) {
        for (int y = 0; y < 5; y++) {
            lanes[IDX(x,y)] ^= D[x];
        }
    }
}

/**
 * @brief ρ (rho) step - lane rotation
 */
static inline void s_rho(uint64_t *lanes)
{
    for (int i = 0; i < 25; i++) {
        if (s_rho_offsets[i] != 0) {
            lanes[i] = ROL64(lanes[i], s_rho_offsets[i]);
        }
    }
}

/**
 * @brief π (pi) step - lane permutation
 */
static inline void s_pi(uint64_t *lanes)
{
    uint64_t temp[25];
    
    for (int x = 0; x < 5; x++) {
        for (int y = 0; y < 5; y++) {
            int new_x = y;
            int new_y = (2 * x + 3 * y) % 5;
            temp[IDX(new_x, new_y)] = lanes[IDX(x, y)];
        }
    }
    
    memcpy(lanes, temp, sizeof(temp));
}

/**
 * @brief χ (chi) step - nonlinear mixing
 */
static inline void s_chi(uint64_t *lanes)
{
    for (int y = 0; y < 5; y++) {
        uint64_t row[5];
        
        for (int x = 0; x < 5; x++) {
            row[x] = lanes[IDX(x, y)];
        }
        
        for (int x = 0; x < 5; x++) {
            lanes[IDX(x, y)] = row[x] ^ ((~row[(x + 1) % 5]) & row[(x + 2) % 5]);
        }
    }
}

/**
 * @brief ι (iota) step - round constant XOR
 */
static inline void s_iota(uint64_t *lanes, unsigned round)
{
    lanes[0] ^= s_round_constants[round];
}

void dap_hash_keccak_permute_rounds_ref(dap_hash_keccak_state_t *state, unsigned rounds)
{
    if (rounds > DAP_KECCAK_ROUNDS) {
        rounds = DAP_KECCAK_ROUNDS;
    }
    
    for (unsigned i = 0; i < rounds; i++) {
        s_theta(state->lanes);
        s_rho(state->lanes);
        s_pi(state->lanes);
        s_chi(state->lanes);
        s_iota(state->lanes, i);
    }
}

void dap_hash_keccak_permute_ref(dap_hash_keccak_state_t *state)
{
    dap_hash_keccak_permute_rounds_ref(state, DAP_KECCAK_ROUNDS);
}

// ============================================================================
// Utility functions for state manipulation
// ============================================================================

void dap_hash_keccak_xor_bytes(dap_hash_keccak_state_t *state, const uint8_t *data, size_t len)
{
    if (len > DAP_KECCAK_STATE_BYTES)
        len = DAP_KECCAK_STATE_BYTES;
    size_t n_words = len / 8;
    for (size_t i = 0; i < n_words; i++) {
        uint64_t w;
        memcpy(&w, data + i * 8, 8);
        state->lanes[i] ^= w;
    }
    uint8_t *state_bytes = (uint8_t *)state->lanes;
    for (size_t i = n_words * 8; i < len; i++)
        state_bytes[i] ^= data[i];
}

void dap_hash_keccak_extract_bytes(const dap_hash_keccak_state_t *state, uint8_t *out, size_t len)
{
    if (len > DAP_KECCAK_STATE_BYTES)
        len = DAP_KECCAK_STATE_BYTES;
    size_t n_words = len / 8;
    for (size_t i = 0; i < n_words; i++)
        memcpy(out + i * 8, &state->lanes[i], 8);
    const uint8_t *state_bytes = (const uint8_t *)state->lanes;
    for (size_t i = n_words * 8; i < len; i++)
        out[i] = state_bytes[i];
}

// ============================================================================
// Sponge Construction
// ============================================================================

void dap_hash_keccak_sponge_init(dap_hash_keccak_ctx_t *ctx, size_t rate, uint8_t suffix)
{
    dap_hash_keccak_state_init_ref(&ctx->state);
    ctx->rate = rate;
    ctx->block_idx = 0;
    ctx->suffix = suffix;
    ctx->absorbing = 1;
}

void dap_hash_keccak_sponge_absorb(dap_hash_keccak_ctx_t *ctx, const uint8_t *data, size_t len)
{
    if (!ctx->absorbing)
        return;

    uint8_t *state_bytes = (uint8_t *)ctx->state.lanes;

    while (len > 0) {
        size_t remaining = ctx->rate - ctx->block_idx;
        size_t to_absorb = (len < remaining) ? len : remaining;
        size_t off = ctx->block_idx;
        size_t i = 0;

        while (i < to_absorb && (off + i) % 8 != 0)
            state_bytes[off + i] ^= data[i], i++;

        for (; i + 8 <= to_absorb; i += 8) {
            uint64_t w;
            memcpy(&w, data + i, 8);
            ctx->state.lanes[(off + i) / 8] ^= w;
        }

        for (; i < to_absorb; i++)
            state_bytes[off + i] ^= data[i];

        ctx->block_idx += to_absorb;
        data += to_absorb;
        len -= to_absorb;

        if (ctx->block_idx == ctx->rate) {
            dap_hash_keccak_permute(&ctx->state);
            ctx->block_idx = 0;
        }
    }
}

void dap_hash_keccak_sponge_finalize(dap_hash_keccak_ctx_t *ctx)
{
    if (!ctx->absorbing) {
        return;
    }
    
    uint8_t *state_bytes = (uint8_t *)ctx->state.lanes;
    
    // Apply domain separation suffix and padding (pad10*1)
    state_bytes[ctx->block_idx] ^= ctx->suffix;
    state_bytes[ctx->rate - 1] ^= 0x80;
    
    dap_hash_keccak_permute(&ctx->state);
    
    ctx->block_idx = 0;
    ctx->absorbing = 0;
}

void dap_hash_keccak_sponge_squeeze(dap_hash_keccak_ctx_t *ctx, uint8_t *out, size_t len)
{
    if (ctx->absorbing) {
        dap_hash_keccak_sponge_finalize(ctx);
    }
    
    const uint8_t *state_bytes = (const uint8_t *)ctx->state.lanes;
    
    while (len > 0) {
        size_t remaining = ctx->rate - ctx->block_idx;
        size_t to_squeeze = (len < remaining) ? len : remaining;
        
        memcpy(out, state_bytes + ctx->block_idx, to_squeeze);
        
        ctx->block_idx += to_squeeze;
        out += to_squeeze;
        len -= to_squeeze;
        
        if (len > 0 && ctx->block_idx == ctx->rate) {
            dap_hash_keccak_permute(&ctx->state);
            ctx->block_idx = 0;
        }
    }
}
