{{! dap_keccak_f1600_asm.S.tpl — Keccak-f[1600] permutation in assembly }}
{{! 100% native dap_tpl — zero AWK blocks }}
{{! Arch-agnostic: instruction mnemonics from ENVIRON (CMake ARGS / .env) }}
{{! To add NEON/SVE: create a new .env + adjust wrappers }}
{{#set LANES=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24}}
{{#set ROUNDS=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23}}
{{#set COLS=0|1|2|3|4}}
{{! Rho rotation offsets per logical lane }}
{{#set RHO=0|1|62|28|27|36|44|6|55|20|3|10|43|25|39|41|45|15|21|8|18|2|61|56|14}}
{{! Chi row groups (logical lane indices for each of 5 rows) }}
{{#set CHI_ROW_0=0|6|12|18|24}}
{{#set CHI_ROW_1=3|9|10|16|22}}
{{#set CHI_ROW_2=1|7|13|19|20}}
{{#set CHI_ROW_3=4|5|11|17|23}}
{{#set CHI_ROW_4=2|8|14|15|21}}
{{! Precomputed Pi^(-r) register mappings for all 24 rounds (Pi^24 = identity) }}
{{#set MAP_0=0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24}}
{{#set MAP_1=0|6|12|18|24|3|9|10|16|22|1|7|13|19|20|4|5|11|17|23|2|8|14|15|21}}
{{#set MAP_2=0|9|13|17|21|18|22|1|5|14|6|10|19|23|2|24|3|7|11|15|12|16|20|4|8}}
{{#set MAP_3=0|22|19|11|8|17|14|6|3|20|9|1|23|15|12|21|18|10|7|4|13|5|2|24|16}}
{{#set MAP_4=0|14|23|7|16|11|20|9|18|2|22|6|15|4|13|8|17|1|10|24|19|3|12|21|5}}
{{#set MAP_5=0|20|15|10|5|7|2|22|17|12|14|9|4|24|19|16|11|6|1|21|23|18|13|8|3}}
{{#set MAP_6=0|2|4|1|3|10|12|14|11|13|20|22|24|21|23|5|7|9|6|8|15|17|19|16|18}}
{{#set MAP_7=0|12|24|6|18|1|13|20|7|19|2|14|21|8|15|3|10|22|9|16|4|11|23|5|17}}
{{#set MAP_8=0|13|21|9|17|6|19|2|10|23|12|20|8|16|4|18|1|14|22|5|24|7|15|3|11}}
{{#set MAP_9=0|19|8|22|11|9|23|12|1|15|13|2|16|5|24|17|6|20|14|3|21|10|4|18|7}}
{{#set MAP_10=0|23|16|14|7|22|15|13|6|4|19|12|5|3|21|11|9|2|20|18|8|1|24|17|10}}
{{#set MAP_11=0|15|5|20|10|14|4|19|9|24|23|13|3|18|8|7|22|12|2|17|16|6|21|11|1}}
{{#set MAP_12=0|4|3|2|1|20|24|23|22|21|15|19|18|17|16|10|14|13|12|11|5|9|8|7|6}}
{{#set MAP_13=0|24|18|12|6|2|21|15|14|8|4|23|17|11|5|1|20|19|13|7|3|22|16|10|9}}
{{#set MAP_14=0|21|17|13|9|12|8|4|20|16|24|15|11|7|3|6|2|23|19|10|18|14|5|1|22}}
{{#set MAP_15=0|8|11|19|22|13|16|24|2|5|21|4|7|10|18|9|12|15|23|1|17|20|3|6|14}}
{{#set MAP_16=0|16|7|23|14|19|5|21|12|3|8|24|10|1|17|22|13|4|15|6|11|2|18|9|20}}
{{#set MAP_17=0|5|10|15|20|23|3|8|13|18|16|21|1|6|11|14|19|24|4|9|7|12|17|22|2}}
{{#set MAP_18=0|3|1|4|2|15|18|16|19|17|5|8|6|9|7|20|23|21|24|22|10|13|11|14|12}}
{{#set MAP_19=0|18|6|24|12|4|17|5|23|11|3|16|9|22|10|2|15|8|21|14|1|19|7|20|13}}
{{#set MAP_20=0|17|9|21|13|24|11|3|15|7|18|5|22|14|1|12|4|16|8|20|6|23|10|2|19}}
{{#set MAP_21=0|11|22|8|19|21|7|18|4|10|17|3|14|20|6|13|24|5|16|2|9|15|1|12|23}}
{{#set MAP_22=0|7|14|16|23|8|10|17|24|1|11|18|20|2|9|19|21|3|5|12|22|4|6|13|15}}
{{#set MAP_23=0|10|20|5|15|16|1|11|21|6|7|17|2|12|22|23|8|18|3|13|14|24|9|19|4}}
{{#set RC_LIST=0x0000000000000001|0x0000000000008082|0x800000000000808a|0x8000000080008000|0x000000000000808b|0x0000000080000001|0x8000000080008081|0x8000000000008009|0x000000000000008a|0x0000000000000088|0x0000000080008009|0x000000008000000a|0x000000008000808b|0x800000000000008b|0x8000000000008089|0x8000000000008003|0x8000000000008002|0x8000000000000080|0x000000000000800a|0x800000008000000a|0x8000000080008081|0x8000000000008080|0x0000000080000001|0x8000000080008008}}
/*
 * dap_keccak_f1600_{{FUNC_SUFFIX}}.S — AUTO-GENERATED by dap_tpl
 *
 * Fully-unrolled Keccak-f[1600] with Pi absorbed into register addressing.
 * Zero Pi rename moves across all 24 rounds.
 *
 * Key techniques:
 *   - {{INSN_XOR3}} for 3-way XOR (Theta)
 *   - {{INSN_CHI}} for Chi: a ^ (~b & c)
 *   - {{INSN_ROL64}} for Rho rotations
 *   - 32 YMM registers via EVEX — zero spills
 *
 * Copyright: DeM Labs Inc. 2026
 * License: GNU GPL v3
 * @generated
 */

.text

{{! ===== 1x permutation wrapper ===== }}
.globl  dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.type   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_1X}}   ({{STRIDE_1X}}*{{i}})(%rdi),  {{REG_1X_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_1X}}   {{REG_1X_PREFIX}}{{i}},  ({{STRIDE_1X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_hash_keccak_permute_{{FUNC_SUFFIX}}, .-dap_hash_keccak_permute_{{FUNC_SUFFIX}}

{{! ===== 4x permutation wrapper (interleaved layout) ===== }}
.globl  dap_keccak_x4_permute_{{FUNC_SUFFIX}}
.type   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, @function
.balign 32
dap_keccak_x4_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    {{INSN_LOAD_4X}}   ({{STRIDE_4X}}*{{i}})(%rdi),  {{REG_PREFIX}}{{i}}
{{/for}}
    pushq   %rdi
    call    .Lpermute_f1600
    popq    %rdi
{{#for i in LANES}}
    {{INSN_STORE_4X}}   {{REG_PREFIX}}{{i}},  ({{STRIDE_4X}}*{{i}})(%rdi)
{{/for}}
    ret
.size   dap_keccak_x4_permute_{{FUNC_SUFFIX}}, .-dap_keccak_x4_permute_{{FUNC_SUFFIX}}

{{! ===== Core permutation: 24 fully-unrolled rounds ===== }}
{{! Pi absorbed into precomputed MAP_N register mappings }}
.balign 64
.Lpermute_f1600:
{{#for rnd in ROUNDS}}
{{#set M}}{{rnd|resolve|MAP_}}{{/set}}
    /* ---- Round {{rnd}} ---- */
{{! == Theta step 1: C[x] = lane[0+x] ^ lane[5+x] ^ lane[10+x] == }}
{{#for x in COLS}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{M|at|x}}, {{REG_PREFIX}}{{x|math|$+25}}
    {{INSN_XOR3}}, {{REG_PREFIX}}{{M|at|x+5}}, {{REG_PREFIX}}{{M|at|x+10}}, {{REG_PREFIX}}{{x|math|$+25}}
{{/for}}
{{! == Theta step 2: C[x] ^= lane[15+x] ^ lane[20+x] == }}
{{#for x in COLS}}
    {{INSN_XOR3}}, {{REG_PREFIX}}{{M|at|x+15}}, {{REG_PREFIX}}{{M|at|x+20}}, {{REG_PREFIX}}{{x|math|$+25}}
{{/for}}
{{! == Theta step 3: D[x] = C[(x+4)%5] ^ ROL(C[(x+1)%5], 1); state ^= D == }}
{{#for x in COLS}}
    {{INSN_ROL64}}      $1, {{REG_PREFIX}}{{x|math|($+1)%5+25}}, {{REG_PREFIX}}30
{{#for y in COLS}}
    {{INSN_XOR3}}, {{REG_PREFIX}}30, {{REG_PREFIX}}{{x|math|($+4)%5+25}}, {{REG_PREFIX}}{{M|at|x+5*y}}
{{/for}}
{{/for}}
{{! == Rho: rotate each lane by its fixed offset == }}
{{#for p in LANES}}
{{#set rho_val}}{{RHO|at|p}}{{/set}}{{#if rho_val != 0}}
    {{INSN_ROL64}}      ${{rho_val}}, {{REG_PREFIX}}{{M|at|p}}, {{REG_PREFIX}}{{M|at|p}}
{{/if}}
{{/for}}
{{! == Chi: a[x] ^= ~a[x+1] & a[x+2], row by row == }}
{{#for ri in COLS}}
{{#set ROW}}{{ri|resolve|CHI_ROW_}}{{/set}}
{{#set L0}}{{ROW|at|0}}{{/set}}{{#set L1}}{{ROW|at|1}}{{/set}}{{#set L2}}{{ROW|at|2}}{{/set}}{{#set L3}}{{ROW|at|3}}{{/set}}{{#set L4}}{{ROW|at|4}}{{/set}}
{{#set ra}}{{M|at|L0}}{{/set}}{{#set rb}}{{M|at|L1}}{{/set}}{{#set rc}}{{M|at|L2}}{{/set}}{{#set rd}}{{M|at|L3}}{{/set}}{{#set re}}{{M|at|L4}}{{/set}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}30
    {{INSN_CHI}}, {{REG_PREFIX}}{{rc}}, {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}30
{{#if ri == 0}}
    {{INSN_XOR_BC}}      .Lrc+{{rnd|math|$*8}}(%rip){{RC_BC_SUFFIX}}, {{REG_PREFIX}}30, {{REG_PREFIX}}30
{{/if}}
    {{INSN_MOV}}   {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}31
    {{INSN_CHI}}, {{REG_PREFIX}}{{rd}}, {{REG_PREFIX}}{{rc}}, {{REG_PREFIX}}31
    {{INSN_CHI}}, {{REG_PREFIX}}{{re}}, {{REG_PREFIX}}{{rd}}, {{REG_PREFIX}}{{rc}}
    {{INSN_CHI}}, {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}{{re}}, {{REG_PREFIX}}{{rd}}
    {{INSN_CHI}}, {{REG_PREFIX}}{{rb}}, {{REG_PREFIX}}{{ra}}, {{REG_PREFIX}}{{re}}
    {{INSN_MOV}}   {{REG_PREFIX}}30, {{REG_PREFIX}}{{ra}}
    {{INSN_MOV}}   {{REG_PREFIX}}31, {{REG_PREFIX}}{{rb}}
{{/for}}
{{/for}}
    ret
.size   .Lpermute_f1600, .-.Lpermute_f1600

{{! ===== Round constants ===== }}
.section .rodata
.balign 64
.Lrc:
{{#for rc in RC_LIST}}
    .quad   {{rc}}
{{/for}}

.section .note.GNU-stack,"",@progbits
