// Auto-generated main include file for all custom mocks
// Generated by dap_mock_autowrap.sh
// Do not modify manually

#include "{{BASENAME}}_mock_macros.h"

{{#if CUSTOM_MOCKS_LIST}}
    {{#for line in CUSTOM_MOCKS_LIST}}
        {{line|split|pipe}}
        {{#set func_name={{line|part|1}}}}
        {{#if func_name != ""}}
#include "custom_mocks/{{func_name}}_mock.h"
        {{/if}}
    {{/for}}
{{/if}}

