// Auto-generated main include file for all custom mocks
// Generated by dap_mock_autowrap.sh
// Do not modify manually

#include "{{BASENAME}}_mock_macros.h"

{{#if CUSTOM_MOCK_FUNC_NAMES}}
    {{#for func_name in CUSTOM_MOCK_FUNC_NAMES|newline}}
        {{#if func_name != ""}}
#include "custom_mocks/{{func_name}}_mock.h"
        {{/if}}
    {{/for}}
{{/if}}

