# CMake generated Testfile for 
# Source directory: /mnt/store/work/dap-sdk/tests/unit/json
# Build directory: /mnt/store/work/dap-sdk/build.debug/tests/unit/json
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_json_unicode "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_unicode")
set_tests_properties(test_json_unicode PROPERTIES  LABELS "unit;json;unicode;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;27;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_numeric_edge_cases "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_numeric_edge_cases")
set_tests_properties(test_json_numeric_edge_cases PROPERTIES  LABELS "unit;json;numeric;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;54;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_invalid "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_invalid")
set_tests_properties(test_json_invalid PROPERTIES  LABELS "unit;json;invalid;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;78;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_boundary "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_boundary")
set_tests_properties(test_json_boundary PROPERTIES  LABELS "unit;json;boundary;critical" TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;102;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_unicode_escape_boundary "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_unicode_escape_boundary")
set_tests_properties(test_unicode_escape_boundary PROPERTIES  LABELS "unit;json;unicode;boundary;edge_case;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;127;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_benchmark "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_benchmark")
set_tests_properties(test_json_benchmark PROPERTIES  LABELS "unit;json;benchmark;performance" TIMEOUT "600" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;151;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_manual_arch_selection "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_manual_arch_selection")
set_tests_properties(test_manual_arch_selection PROPERTIES  LABELS "unit;json;arch;selection;api;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;175;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_stage1_ref "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_stage1_ref")
set_tests_properties(test_json_stage1_ref PROPERTIES  LABELS "unit;json;stage1;reference;critical" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;199;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_stage1_simd_correctness "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_stage1_simd_correctness")
set_tests_properties(test_json_stage1_simd_correctness PROPERTIES  LABELS "unit;json;stage1;simd;correctness;critical" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;228;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_stage1_sse2_debug "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_stage1_sse2_debug")
set_tests_properties(test_json_stage1_sse2_debug PROPERTIES  LABELS "unit;json;stage1;sse2;debug" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;254;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_simd_string_spanning "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_simd_string_spanning")
set_tests_properties(test_simd_string_spanning PROPERTIES  LABELS "unit;json;stage1;simd;regression;critical;universal" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;280;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_simdjson_stage1 "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_simdjson_stage1")
set_tests_properties(test_simdjson_stage1 PROPERTIES  LABELS "unit;json;stage1;simdjson;phase2;performance;critical" TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;344;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_memory_dos "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_memory_dos")
set_tests_properties(test_memory_dos PROPERTIES  LABELS "unit;json;security;dos;critical;phase1.8" TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;370;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_simd_chunk_boundaries "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_simd_chunk_boundaries")
set_tests_properties(test_simd_chunk_boundaries PROPERTIES  LABELS "unit;json;simd;boundaries;critical;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;394;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_concurrency "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_concurrency")
set_tests_properties(test_concurrency PROPERTIES  LABELS "unit;json;concurrency;thread-safety;critical;phase1.8" TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;427;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_numeric_refined "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_numeric_refined")
set_tests_properties(test_numeric_refined PROPERTIES  LABELS "unit;json;numeric;refined;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;444;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_string_edges "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_string_edges")
set_tests_properties(test_string_edges PROPERTIES  LABELS "unit;json;string;edges;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;454;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_whitespace_edges "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_whitespace_edges")
set_tests_properties(test_whitespace_edges PROPERTIES  LABELS "unit;json;whitespace;edges;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;464;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_array_edges "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_array_edges")
set_tests_properties(test_array_edges PROPERTIES  LABELS "unit;json;array;edges;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;474;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_object_edges "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_object_edges")
set_tests_properties(test_object_edges PROPERTIES  LABELS "unit;json;object;edges;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;484;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_literal_edges "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_literal_edges")
set_tests_properties(test_literal_edges PROPERTIES  LABELS "unit;json;literal;edges;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;494;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_serialization_roundtrip "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_serialization_roundtrip")
set_tests_properties(test_serialization_roundtrip PROPERTIES  LABELS "unit;json;serialization;roundtrip;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;504;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_platform_specific "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_platform_specific")
set_tests_properties(test_platform_specific PROPERTIES  LABELS "unit;json;platform;specific;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;514;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json5_features "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json5_features")
set_tests_properties(test_json5_features PROPERTIES  LABELS "unit;json;json5;features;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;524;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_jsonc_comments "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_jsonc_comments")
set_tests_properties(test_jsonc_comments PROPERTIES  LABELS "unit;json;jsonc;comments;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;531;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_streaming_api "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_streaming_api")
set_tests_properties(test_streaming_api PROPERTIES  LABELS "unit;json;streaming;api;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;538;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_api_mutations "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_api_mutations")
set_tests_properties(test_api_mutations PROPERTIES  LABELS "unit;json;api;mutations;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;545;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_real_world_data "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_real_world_data")
set_tests_properties(test_real_world_data PROPERTIES  LABELS "unit;json;real;world;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;564;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_perf_edge_cases "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_perf_edge_cases")
set_tests_properties(test_perf_edge_cases PROPERTIES  LABELS "unit;json;performance;edge;phase1.8" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;571;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_jsonpath_queries "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_jsonpath_queries")
set_tests_properties(test_jsonpath_queries PROPERTIES  LABELS "unit;json;jsonpath;queries;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;578;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_json_schema "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_json_schema")
set_tests_properties(test_json_schema PROPERTIES  LABELS "unit;json;schema;validation;phase1.8" TIMEOUT "60" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;585;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(benchmark_deep_nesting "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/benchmark_deep_nesting")
set_tests_properties(benchmark_deep_nesting PROPERTIES  LABELS "unit;json;benchmark;phase2.4" TIMEOUT "120" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;605;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_reference_scanner_64 "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_reference_scanner_64")
set_tests_properties(test_reference_scanner_64 PROPERTIES  LABELS "unit;json;debug;reference" TIMEOUT "10" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;613;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_chunk_boundary_escapes "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_chunk_boundary_escapes")
set_tests_properties(test_chunk_boundary_escapes PROPERTIES  LABELS "unit;json;simd;boundary;escape;critical" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;626;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_64byte_simple "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_64byte_simple")
set_tests_properties(test_64byte_simple PROPERTIES  LABELS "unit;json;debug;64byte" TIMEOUT "10" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;637;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
add_test(test_bitmap_classification "/mnt/store/work/dap-sdk/build.debug/tests/unit/json/test_bitmap_classification")
set_tests_properties(test_bitmap_classification PROPERTIES  LABELS "unit;json;debug;verification" TIMEOUT "10" _BACKTRACE_TRIPLES "/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;648;add_test;/mnt/store/work/dap-sdk/tests/unit/json/CMakeLists.txt;0;")
