{{! AArch64 SHA3 Keccak-f[1600] — arch-specific assembly }}
{{! Uses eor3/bcax/xar/rax1 — Apple Silicon M1+ and ARMv8.2-SHA3 }}
{{! Fused Theta+Rho via xar: fewer instructions than x86 variant }}
/*
 * dap_keccak_f1600_{{FUNC_SUFFIX}}.S — AUTO-GENERATED by dap_tpl
 *
 * AArch64 Keccak-f[1600] using ARMv8.2-SHA3 crypto extensions.
 * Fully unrolled, Pi absorbed into register addressing.
 *
 * Key instructions:
 *   eor3 — 3-way XOR (Theta column parity)
 *   bcax — bit-clear and XOR: d = a ^ (~b & c)  (Chi)
 *   rax1 — XOR + ROL(x, 1)  (Theta D computation)
 *   xar  — XOR + rotate right (fused Theta D-application + Rho)
 *
 * Register allocation (32 v-regs, zero spills):
 *   v0 – v24 : 25 state lanes
 *   v25– v29 : 5 temporaries (C[0..4] for Theta)
 *   v30, v31 : 2 temporaries (Chi row processing)
 *
 * Copyright: DeM Labs Inc. 2026
 * License: GNU GPL v3
 * @generated
 */

.text

/* ===== 1x permutation: scalar 64-bit lanes in d-registers ===== */
.globl  _dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.globl  dap_hash_keccak_permute_{{FUNC_SUFFIX}}
.p2align 4
_dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
dap_hash_keccak_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    ldr     d{{i}}, [x0, #{{i|math|$*8}}]
{{/for}}
    stp     x0, x30, [sp, #-16]!
    bl      .Lpermute_f1600_arm
    ldp     x0, x30, [sp], #16
{{#for i in LANES}}
    str     d{{i}}, [x0, #{{i|math|$*8}}]
{{/for}}
    ret

/* ===== 2x permutation: 128-bit NEON lanes (2 parallel states) ===== */
.globl  _dap_keccak_x2_permute_{{FUNC_SUFFIX}}
.globl  dap_keccak_x2_permute_{{FUNC_SUFFIX}}
.p2align 4
_dap_keccak_x2_permute_{{FUNC_SUFFIX}}:
dap_keccak_x2_permute_{{FUNC_SUFFIX}}:
{{#for i in LANES}}
    ldr     q{{i}}, [x0, #{{i|math|$*16}}]
{{/for}}
    stp     x0, x30, [sp, #-16]!
    bl      .Lpermute_f1600_arm
    ldp     x0, x30, [sp], #16
{{#for i in LANES}}
    str     q{{i}}, [x0, #{{i|math|$*16}}]
{{/for}}
    ret

/* ===== Core permutation — shared by 1x and 2x ===== */
/* eor3/bcax/rax1/xar operate on .16b/.2d regardless of active width */
.p2align 6
.Lpermute_f1600_arm:
    adrp    x9, .Lrc_arm@PAGE
    add     x9, x9, .Lrc_arm@PAGEOFF
{{#for rnd in ROUNDS}}
{{#set M}}{{rnd|resolve|MAP_}}{{/set}}
    /* ---- Round {{rnd}} ---- */

    /* == Theta step 1: C[x] = eor3(lane[x], lane[x+5], lane[x+10]) == */
{{#for x in COLS}}
    eor3    v{{x|math|$+25}}.16b, v{{M|at|x}}.16b, v{{M|at|x+5}}.16b, v{{M|at|x+10}}.16b
{{/for}}
    /* == Theta step 2: C[x] = eor3(C[x], lane[x+15], lane[x+20]) == */
{{#for x in COLS}}
    eor3    v{{x|math|$+25}}.16b, v{{x|math|$+25}}.16b, v{{M|at|x+15}}.16b, v{{M|at|x+20}}.16b
{{/for}}
    /* == Theta step 3 + Rho: column-by-column D via rax1, fused with xar rotation == */
{{#for x in COLS}}
    rax1    v30.2d, v{{x|math|($+4)%5+25}}.2d, v{{x|math|($+1)%5+25}}.2d
{{#for y in COLS}}
{{#set rho_val}}{{RHO|at|x+5*y}}{{/set}}
{{#set reg}}{{M|at|x+5*y}}{{/set}}
{{#if rho_val == 0}}
    eor     v{{reg}}.16b, v{{reg}}.16b, v30.16b
{{/if}}
{{#if rho_val != 0}}
    xar     v{{reg}}.2d, v{{reg}}.2d, v30.2d, #{{rho_val|math|64-$}}
{{/if}}
{{/for}}
{{/for}}
    /* == Chi: bcax Vd, Va, Vc, Vb  =>  Va ^ (~Vb & Vc) == */
{{#for ri in COLS}}
{{#set ROW}}{{ri|resolve|CHI_ROW_}}{{/set}}
{{#set L0}}{{ROW|at|0}}{{/set}}{{#set L1}}{{ROW|at|1}}{{/set}}{{#set L2}}{{ROW|at|2}}{{/set}}{{#set L3}}{{ROW|at|3}}{{/set}}{{#set L4}}{{ROW|at|4}}{{/set}}
{{#set ra}}{{M|at|L0}}{{/set}}{{#set rb}}{{M|at|L1}}{{/set}}{{#set rc}}{{M|at|L2}}{{/set}}{{#set rd}}{{M|at|L3}}{{/set}}{{#set re}}{{M|at|L4}}{{/set}}
    mov     v30.16b, v{{ra}}.16b
    mov     v31.16b, v{{rb}}.16b
    bcax    v{{ra}}.16b, v30.16b, v{{rc}}.16b, v{{rb}}.16b
    bcax    v{{rb}}.16b, v31.16b, v{{rd}}.16b, v{{rc}}.16b
    bcax    v{{rc}}.16b, v{{rc}}.16b, v{{re}}.16b, v{{rd}}.16b
    bcax    v{{rd}}.16b, v{{rd}}.16b, v30.16b, v{{re}}.16b
    bcax    v{{re}}.16b, v{{re}}.16b, v31.16b, v30.16b
{{#if ri == 0}}
    add     x10, x9, #{{rnd|math|$*8}}
    ld1r    {v30.2d}, [x10]
    eor     v{{ra}}.16b, v{{ra}}.16b, v30.16b
{{/if}}
{{/for}}
{{/for}}
    ret

/* ===== Round constants ===== */
.section .rodata
.p2align 6
.Lrc_arm:
{{#for rc in RC_LIST}}
    .quad   {{rc}}
{{/for}}

#if !defined(__APPLE__)
.section .note.GNU-stack,"",@progbits
#endif
