{{! x86 AVX-512VL ChaCha20 — dual-block (2×8) assembly, 32 YMM regs }}
{{! Uses vprold (EVEX rotate), vpxord, vpbroadcastd from AVX-512VL. }}
{{! Constants (SIGMA, DR, CTR_INC) come from root dap_chacha20_asm.S.tpl. }}
/*
 * dap_chacha20_encrypt_asm — AVX-512VL ChaCha20 (generated by dap_tpl)
 *
 * 2×8 dual-block: 32 YMM regs, zero QR spills, 20 rounds unrolled.
 * Tail: delegates to dap_chacha20_encrypt_avx2_512vl (C SIMD).
 *
 * void dap_chacha20_encrypt_asm(
 *     uint8_t *out,       // rdi
 *     const uint8_t *in,  // rsi
 *     size_t len,         // rdx
 *     const uint8_t key[32],   // rcx
 *     const uint8_t nonce[12], // r8
 *     uint32_t counter);       // r9d
 *
 * @generated
 */

#define STKOFF_S0       (0*32)
#define STKOFF_S1       (1*32)
#define STKOFF_S2       (2*32)
#define STKOFF_S3       (3*32)
#define STKOFF_S4       (4*32)
#define STKOFF_S5       (5*32)
#define STKOFF_S6       (6*32)
#define STKOFF_S7       (7*32)
#define STKOFF_S8       (8*32)
#define STKOFF_S9       (9*32)
#define STKOFF_S10      (10*32)
#define STKOFF_S11      (11*32)
#define STKOFF_S13      (12*32)
#define STKOFF_S14      (13*32)
#define STKOFF_S15      (14*32)
#define STKOFF_A12      (15*32)
#define STKOFF_B12      (16*32)
#define STKOFF_BSAVE    (17*32)
#define STKOFF_KEYPTR   (33*32)
#define STKOFF_NONCEPTR (33*32+8)
#define STACK_SIZE      (34*32)

{{#include ASM_MACROS}}

SECTION_RODATA
.balign 64
.Lsigma:
    .long {{SIGMA_0}}, {{SIGMA_1}}, {{SIGMA_2}}, {{SIGMA_3}}
.Lctr_inc:
{{#for ci in CTR_INC}}
    .long {{ci}}
{{/for}}

.text

/* Dual-block interleaved quarter-round: a += b; d ^= a; d <<<= {16,12,8,7} */
.macro QR_PAIR a0 a1 a2 a3 b0 b1 b2 b3
    vpaddd  \a1, \a0, \a0
    vpaddd  \b1, \b0, \b0
    vpxord  \a0, \a3, \a3
    vpxord  \b0, \b3, \b3
    vprold  $16, \a3, \a3
    vprold  $16, \b3, \b3
    vpaddd  \a3, \a2, \a2
    vpaddd  \b3, \b2, \b2
    vpxord  \a2, \a1, \a1
    vpxord  \b2, \b1, \b1
    vprold  $12, \a1, \a1
    vprold  $12, \b1, \b1
    vpaddd  \a1, \a0, \a0
    vpaddd  \b1, \b0, \b0
    vpxord  \a0, \a3, \a3
    vpxord  \b0, \b3, \b3
    vprold  $8, \a3, \a3
    vprold  $8, \b3, \b3
    vpaddd  \a3, \a2, \a2
    vpaddd  \b3, \b2, \b2
    vpxord  \a2, \a1, \a1
    vpxord  \b2, \b1, \b1
    vprold  $7, \a1, \a1
    vprold  $7, \b1, \b1
.endm

/* 8×8 transpose stages 1+2 (register-only) */
.macro TRANSPOSE8_INTERLEAVE v0 v1 v2 v3 v4 v5 v6 v7 t0 t1 t2 t3 t4 t5 t6 t7
    vpunpckldq  \v1, \v0, \t0
    vpunpckhdq  \v1, \v0, \t1
    vpunpckldq  \v3, \v2, \t2
    vpunpckhdq  \v3, \v2, \t3
    vpunpckldq  \v5, \v4, \t4
    vpunpckhdq  \v5, \v4, \t5
    vpunpckldq  \v7, \v6, \t6
    vpunpckhdq  \v7, \v6, \t7
    vpunpcklqdq \t2, \t0, \v0
    vpunpckhqdq \t2, \t0, \v1
    vpunpcklqdq \t3, \t1, \v2
    vpunpckhqdq \t3, \t1, \v3
    vpunpcklqdq \t6, \t4, \v4
    vpunpckhqdq \t6, \t4, \v5
    vpunpcklqdq \t7, \t5, \v6
    vpunpckhqdq \t7, \t5, \v7
.endm

/* Stage 3: 128-bit lane swap + XOR plaintext + store */
.macro LANE_XOR_STORE dst imm va vb off out_r in_r
    vshufi32x4  \imm, \va, \vb, \dst
    vpxord      \off(\in_r), \dst, \dst
    vmovdqu64   \dst, \off(\out_r)
.endm

/* Full stage 3: 8 lane pairs (low 4 + high 4) */
/* Pre-compute offsets via .set to avoid GAS (expr)(%reg) parsing issue */
.macro TRANSPOSE_STORE v0 v1 v2 v3 v4 v5 v6 v7 t0 t1 t2 t3 t4 t5 t6 t7 boff out_r in_r
    .set .Lts_o0, \boff + 0*64
    .set .Lts_o1, \boff + 1*64
    .set .Lts_o2, \boff + 2*64
    .set .Lts_o3, \boff + 3*64
    .set .Lts_o4, \boff + 4*64
    .set .Lts_o5, \boff + 5*64
    .set .Lts_o6, \boff + 6*64
    .set .Lts_o7, \boff + 7*64
    LANE_XOR_STORE \t0 $0 \v4 \v0 .Lts_o0 \out_r \in_r
    LANE_XOR_STORE \t1 $0 \v5 \v1 .Lts_o1 \out_r \in_r
    LANE_XOR_STORE \t2 $0 \v6 \v2 .Lts_o2 \out_r \in_r
    LANE_XOR_STORE \t3 $0 \v7 \v3 .Lts_o3 \out_r \in_r
    LANE_XOR_STORE \t4 $3 \v4 \v0 .Lts_o4 \out_r \in_r
    LANE_XOR_STORE \t5 $3 \v5 \v1 .Lts_o5 \out_r \in_r
    LANE_XOR_STORE \t6 $3 \v6 \v2 .Lts_o6 \out_r \in_r
    LANE_XOR_STORE \t7 $3 \v7 \v3 .Lts_o7 \out_r \in_r
.endm

/* ══════════════════════════════════════════════════════════════════ */

.globl  dap_chacha20_encrypt_asm
FUNC_TYPE(dap_chacha20_encrypt_asm)
.balign 64
dap_chacha20_encrypt_asm:
    pushq   %rbx
    pushq   %r12
    pushq   %r13
    pushq   %r14
    pushq   %r15
    pushq   %rbp
    movq    %rsp, %rbp
    andq    $-64, %rsp
    subq    $STACK_SIZE, %rsp

    movq    %rdi, %r12
    movq    %rsi, %r13
    movq    %rdx, %r14
    movl    %r9d, %r15d
    movq    %rcx, STKOFF_KEYPTR(%rsp)
    movq    %r8,  STKOFF_NONCEPTR(%rsp)

    vpbroadcastd    .Lsigma+0(%rip), %ymm0
    vpbroadcastd    .Lsigma+4(%rip), %ymm1
    vpbroadcastd    .Lsigma+8(%rip), %ymm2
    vpbroadcastd    .Lsigma+12(%rip), %ymm3
    vmovdqa64   %ymm0,  STKOFF_S0(%rsp)
    vmovdqa64   %ymm1,  STKOFF_S1(%rsp)
    vmovdqa64   %ymm2,  STKOFF_S2(%rsp)
    vmovdqa64   %ymm3,  STKOFF_S3(%rsp)

{{#for kw in KEY_WORDS}}
    vpbroadcastd    {{kw|math|$*4}}(%rcx), %ymm{{kw}}
{{/for}}
{{#for kw in KEY_WORDS}}
    vmovdqa64   %ymm{{kw}},  STKOFF_S{{kw|math|$+4}}(%rsp)
{{/for}}

    vpbroadcastd    0(%r8), %ymm0
    vpbroadcastd    4(%r8), %ymm1
    vpbroadcastd    8(%r8), %ymm2
    vmovdqa64   %ymm0,  STKOFF_S13(%rsp)
    vmovdqa64   %ymm1,  STKOFF_S14(%rsp)
    vmovdqa64   %ymm2,  STKOFF_S15(%rsp)

    cmpq    $1024, %r14
    jb      .Ltail

/* ══════════════════════════════════════════════════════════════════ */
/* Dual-block main loop: 2×8 blocks = 1024 bytes per iteration      */
/* ══════════════════════════════════════════════════════════════════ */
.balign 64
.Ldual_loop:
    vmovdqa64   STKOFF_S0(%rsp),  %ymm0
    vmovdqa64   STKOFF_S1(%rsp),  %ymm1
    vmovdqa64   STKOFF_S2(%rsp),  %ymm2
    vmovdqa64   STKOFF_S3(%rsp),  %ymm3
    vmovdqa64   STKOFF_S4(%rsp),  %ymm4
    vmovdqa64   STKOFF_S5(%rsp),  %ymm5
    vmovdqa64   STKOFF_S6(%rsp),  %ymm6
    vmovdqa64   STKOFF_S7(%rsp),  %ymm7
    vmovdqa64   STKOFF_S8(%rsp),  %ymm8
    vmovdqa64   STKOFF_S9(%rsp),  %ymm9
    vmovdqa64   STKOFF_S10(%rsp), %ymm10
    vmovdqa64   STKOFF_S11(%rsp), %ymm11
    vpbroadcastd    %r15d, %ymm12
    vpaddd      .Lctr_inc(%rip), %ymm12, %ymm12
    vmovdqa64   %ymm12, STKOFF_A12(%rsp)
    vmovdqa64   STKOFF_S13(%rsp), %ymm13
    vmovdqa64   STKOFF_S14(%rsp), %ymm14
    vmovdqa64   STKOFF_S15(%rsp), %ymm15

    vmovdqa64   STKOFF_S0(%rsp),  %ymm16
    vmovdqa64   STKOFF_S1(%rsp),  %ymm17
    vmovdqa64   STKOFF_S2(%rsp),  %ymm18
    vmovdqa64   STKOFF_S3(%rsp),  %ymm19
    vmovdqa64   STKOFF_S4(%rsp),  %ymm20
    vmovdqa64   STKOFF_S5(%rsp),  %ymm21
    vmovdqa64   STKOFF_S6(%rsp),  %ymm22
    vmovdqa64   STKOFF_S7(%rsp),  %ymm23
    vmovdqa64   STKOFF_S8(%rsp),  %ymm24
    vmovdqa64   STKOFF_S9(%rsp),  %ymm25
    vmovdqa64   STKOFF_S10(%rsp), %ymm26
    vmovdqa64   STKOFF_S11(%rsp), %ymm27
    leal    8(%r15d), %eax
    vpbroadcastd    %eax, %ymm28
    vpaddd      .Lctr_inc(%rip), %ymm28, %ymm28
    vmovdqa64   %ymm28, STKOFF_B12(%rsp)
    vmovdqa64   STKOFF_S13(%rsp), %ymm29
    vmovdqa64   STKOFF_S14(%rsp), %ymm30
    vmovdqa64   STKOFF_S15(%rsp), %ymm31

    /* 20 rounds: 10 double-rounds, fully unrolled via dap_tpl */
{{#for dr in DR}}
    /* ── Double-round {{dr}} ── */
    QR_PAIR %ymm0 %ymm4 %ymm8  %ymm12 %ymm16 %ymm20 %ymm24 %ymm28
    QR_PAIR %ymm1 %ymm5 %ymm9  %ymm13 %ymm17 %ymm21 %ymm25 %ymm29
    QR_PAIR %ymm2 %ymm6 %ymm10 %ymm14 %ymm18 %ymm22 %ymm26 %ymm30
    QR_PAIR %ymm3 %ymm7 %ymm11 %ymm15 %ymm19 %ymm23 %ymm27 %ymm31
    QR_PAIR %ymm0 %ymm5 %ymm10 %ymm15 %ymm16 %ymm21 %ymm26 %ymm31
    QR_PAIR %ymm1 %ymm6 %ymm11 %ymm12 %ymm17 %ymm22 %ymm27 %ymm28
    QR_PAIR %ymm2 %ymm7 %ymm8  %ymm13 %ymm18 %ymm23 %ymm24 %ymm29
    QR_PAIR %ymm3 %ymm4 %ymm9  %ymm14 %ymm19 %ymm20 %ymm25 %ymm30
{{/for}}

    /* ═══════════════════════════════════════════════════════════ */
    /* Phase 2: save block B, finalize+transpose+store A then B  */
    /* ═══════════════════════════════════════════════════════════ */

    vmovdqa64   %ymm16, (STKOFF_BSAVE + 0*32)(%rsp)
    vmovdqa64   %ymm17, (STKOFF_BSAVE + 1*32)(%rsp)
    vmovdqa64   %ymm18, (STKOFF_BSAVE + 2*32)(%rsp)
    vmovdqa64   %ymm19, (STKOFF_BSAVE + 3*32)(%rsp)
    vmovdqa64   %ymm20, (STKOFF_BSAVE + 4*32)(%rsp)
    vmovdqa64   %ymm21, (STKOFF_BSAVE + 5*32)(%rsp)
    vmovdqa64   %ymm22, (STKOFF_BSAVE + 6*32)(%rsp)
    vmovdqa64   %ymm23, (STKOFF_BSAVE + 7*32)(%rsp)
    vmovdqa64   %ymm24, (STKOFF_BSAVE + 8*32)(%rsp)
    vmovdqa64   %ymm25, (STKOFF_BSAVE + 9*32)(%rsp)
    vmovdqa64   %ymm26, (STKOFF_BSAVE + 10*32)(%rsp)
    vmovdqa64   %ymm27, (STKOFF_BSAVE + 11*32)(%rsp)
    vmovdqa64   %ymm28, (STKOFF_BSAVE + 12*32)(%rsp)
    vmovdqa64   %ymm29, (STKOFF_BSAVE + 13*32)(%rsp)
    vmovdqa64   %ymm30, (STKOFF_BSAVE + 14*32)(%rsp)
    vmovdqa64   %ymm31, (STKOFF_BSAVE + 15*32)(%rsp)

    /* Finalize block A */
    vpaddd  STKOFF_S0(%rsp),  %ymm0,  %ymm0
    vpaddd  STKOFF_S1(%rsp),  %ymm1,  %ymm1
    vpaddd  STKOFF_S2(%rsp),  %ymm2,  %ymm2
    vpaddd  STKOFF_S3(%rsp),  %ymm3,  %ymm3
    vpaddd  STKOFF_S4(%rsp),  %ymm4,  %ymm4
    vpaddd  STKOFF_S5(%rsp),  %ymm5,  %ymm5
    vpaddd  STKOFF_S6(%rsp),  %ymm6,  %ymm6
    vpaddd  STKOFF_S7(%rsp),  %ymm7,  %ymm7
    vpaddd  STKOFF_S8(%rsp),  %ymm8,  %ymm8
    vpaddd  STKOFF_S9(%rsp),  %ymm9,  %ymm9
    vpaddd  STKOFF_S10(%rsp), %ymm10, %ymm10
    vpaddd  STKOFF_S11(%rsp), %ymm11, %ymm11
    vpaddd  STKOFF_A12(%rsp), %ymm12, %ymm12
    vpaddd  STKOFF_S13(%rsp), %ymm13, %ymm13
    vpaddd  STKOFF_S14(%rsp), %ymm14, %ymm14
    vpaddd  STKOFF_S15(%rsp), %ymm15, %ymm15

    /* Block A words 0-7: transpose + XOR + store (byte_off=0, base_off=0) */
    TRANSPOSE8_INTERLEAVE %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 %ymm16 %ymm17 %ymm18 %ymm19 %ymm20 %ymm21 %ymm22 %ymm23
    TRANSPOSE_STORE %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 %ymm16 %ymm17 %ymm18 %ymm19 %ymm20 %ymm21 %ymm22 %ymm23 0 %r12 %r13

    /* Block A words 8-15: transpose + XOR + store (byte_off=32, base_off=0) */
    TRANSPOSE8_INTERLEAVE %ymm8 %ymm9 %ymm10 %ymm11 %ymm12 %ymm13 %ymm14 %ymm15 %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7
    TRANSPOSE_STORE %ymm8 %ymm9 %ymm10 %ymm11 %ymm12 %ymm13 %ymm14 %ymm15 %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 32 %r12 %r13

    /* Load + finalize block B */
    vmovdqa64   (STKOFF_BSAVE + 0*32)(%rsp),  %ymm0
    vmovdqa64   (STKOFF_BSAVE + 1*32)(%rsp),  %ymm1
    vmovdqa64   (STKOFF_BSAVE + 2*32)(%rsp),  %ymm2
    vmovdqa64   (STKOFF_BSAVE + 3*32)(%rsp),  %ymm3
    vmovdqa64   (STKOFF_BSAVE + 4*32)(%rsp),  %ymm4
    vmovdqa64   (STKOFF_BSAVE + 5*32)(%rsp),  %ymm5
    vmovdqa64   (STKOFF_BSAVE + 6*32)(%rsp),  %ymm6
    vmovdqa64   (STKOFF_BSAVE + 7*32)(%rsp),  %ymm7
    vmovdqa64   (STKOFF_BSAVE + 8*32)(%rsp),  %ymm8
    vmovdqa64   (STKOFF_BSAVE + 9*32)(%rsp),  %ymm9
    vmovdqa64   (STKOFF_BSAVE + 10*32)(%rsp), %ymm10
    vmovdqa64   (STKOFF_BSAVE + 11*32)(%rsp), %ymm11
    vmovdqa64   (STKOFF_BSAVE + 12*32)(%rsp), %ymm12
    vmovdqa64   (STKOFF_BSAVE + 13*32)(%rsp), %ymm13
    vmovdqa64   (STKOFF_BSAVE + 14*32)(%rsp), %ymm14
    vmovdqa64   (STKOFF_BSAVE + 15*32)(%rsp), %ymm15

    vpaddd  STKOFF_S0(%rsp),  %ymm0,  %ymm0
    vpaddd  STKOFF_S1(%rsp),  %ymm1,  %ymm1
    vpaddd  STKOFF_S2(%rsp),  %ymm2,  %ymm2
    vpaddd  STKOFF_S3(%rsp),  %ymm3,  %ymm3
    vpaddd  STKOFF_S4(%rsp),  %ymm4,  %ymm4
    vpaddd  STKOFF_S5(%rsp),  %ymm5,  %ymm5
    vpaddd  STKOFF_S6(%rsp),  %ymm6,  %ymm6
    vpaddd  STKOFF_S7(%rsp),  %ymm7,  %ymm7
    vpaddd  STKOFF_S8(%rsp),  %ymm8,  %ymm8
    vpaddd  STKOFF_S9(%rsp),  %ymm9,  %ymm9
    vpaddd  STKOFF_S10(%rsp), %ymm10, %ymm10
    vpaddd  STKOFF_S11(%rsp), %ymm11, %ymm11
    vpaddd  STKOFF_B12(%rsp), %ymm12, %ymm12
    vpaddd  STKOFF_S13(%rsp), %ymm13, %ymm13
    vpaddd  STKOFF_S14(%rsp), %ymm14, %ymm14
    vpaddd  STKOFF_S15(%rsp), %ymm15, %ymm15

    /* Block B words 0-7: transpose + XOR + store (byte_off=0, base_off=512) */
    TRANSPOSE8_INTERLEAVE %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 %ymm16 %ymm17 %ymm18 %ymm19 %ymm20 %ymm21 %ymm22 %ymm23
    TRANSPOSE_STORE %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 %ymm16 %ymm17 %ymm18 %ymm19 %ymm20 %ymm21 %ymm22 %ymm23 512 %r12 %r13

    /* Block B words 8-15: transpose + XOR + store (byte_off=32, base_off=512) */
    TRANSPOSE8_INTERLEAVE %ymm8 %ymm9 %ymm10 %ymm11 %ymm12 %ymm13 %ymm14 %ymm15 %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7
    TRANSPOSE_STORE %ymm8 %ymm9 %ymm10 %ymm11 %ymm12 %ymm13 %ymm14 %ymm15 %ymm0 %ymm1 %ymm2 %ymm3 %ymm4 %ymm5 %ymm6 %ymm7 544 %r12 %r13

    addq    $1024, %r12
    addq    $1024, %r13
    subq    $1024, %r14
    addl    $16,   %r15d

    cmpq    $1024, %r14
    jae     .Ldual_loop

/* ══════════════════════════════════════════════════════════════════ */
/* Tail: delegate remaining bytes to C SIMD fallback via tail-call  */
/* ══════════════════════════════════════════════════════════════════ */
.Ltail:
    testq   %r14, %r14
    jz      .Lexit

    movq    %r12, %rdi
    movq    %r13, %rsi
    movq    %r14, %rdx
    movq    STKOFF_KEYPTR(%rsp), %rcx
    movq    STKOFF_NONCEPTR(%rsp), %r8
    movl    %r15d, %r9d

    vzeroupper
    movq    %rbp, %rsp
    popq    %rbp
    popq    %r15
    popq    %r14
    popq    %r13
    popq    %r12
    popq    %rbx
    jmp     dap_chacha20_encrypt_avx2_512vl

.Lexit:
    vzeroupper
    movq    %rbp, %rsp
    popq    %rbp
    popq    %r15
    popq    %r14
    popq    %r13
    popq    %r12
    popq    %rbx
    ret

FUNC_SIZE(dap_chacha20_encrypt_asm)

GNU_STACK
